set(CASE_NAME cwhip_reports_uncaught_array_index_bounds)
set(CASE_FIXTURE negative_array_bounds_uncaught.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_reports_uncaught_array_index_bounds.stdout")
set(CASE_EXPECT_RUNTIME_FAILURE [==[ON]==])
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC [==[uncaught runtime exception at .*negative_array_bounds_uncaught.cw:4:17: list index out of bounds]==])
