set(CASE_NAME cwhip_compile_and_run_object_cast_statement)
set(CASE_FIXTURE positive_object_cast_statement.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_object_cast_statement.stdout")
