set(CASE_NAME cwhip_reports_map_extraction_mismatch)
set(CASE_FIXTURE negative_map_extraction_mismatch.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_reports_map_extraction_mismatch.stdout")
set(CASE_EXPECT_RUNTIME_FAILURE [==[ON]==])
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC [==[uncaught runtime exception at .*negative_map_extraction_mismatch.cw:4:26: 'any' value does not hold a dict reference]==])
