set(CASE_NAME cwhip_compile_and_run_exception_bindings)
set(CASE_FIXTURE positive_exception_binding.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_exception_bindings.stdout")
