set(CASE_NAME cwhip_compile_and_run_inherited_destructors)
set(CASE_FIXTURE positive_inherited_destructors.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_inherited_destructors.stdout")
