set(CASE_NAME cwhip_namespace_out_of_line_method)
set(CASE_FIXTURE positive_namespace_out_of_line.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_namespace_out_of_line_method.stdout")
