set(CASE_NAME cwhip_compile_and_run_mixed_member_visibility)
set(CASE_FIXTURE positive_mixed_member_visibility.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_mixed_member_visibility.stdout")
