set(CASE_NAME cwhip_compile_and_run_direct_constructor_declarations)
set(CASE_FIXTURE positive_direct_constructor_declarations.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_direct_constructor_declarations.stdout")
