set(CASE_NAME cwhip_compile_and_run_runtime_exceptions)
set(CASE_FIXTURE positive_runtime_exceptions.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_runtime_exceptions.stdout")
