set(CASE_NAME cwhip_compile_and_run_protected_base_lifecycle)
set(CASE_FIXTURE positive_protected_base_lifecycle.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_protected_base_lifecycle.stdout")
