set(CASE_NAME cwhip_compile_and_run_protected_base_example)
set(CASE_FIXTURE positive_protected_base_example.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_protected_base_example.stdout")
