set(CASE_NAME cwhip_compile_and_run_method_overloads)
set(CASE_FIXTURE positive_method_overloads.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_method_overloads.stdout")
