set(CASE_NAME cwhip_compile_and_run_scalar_compound_assignments)
set(CASE_FIXTURE positive_scalar_compound_assignments.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_scalar_compound_assignments.stdout")
