set(CASE_NAME cwhip_compile_and_run_string_methods)
set(CASE_FIXTURE positive_string_methods.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_string_methods.stdout")
