set(CASE_NAME cwhip_compile_and_run_newline_statements)
set(CASE_FIXTURE positive_newline_statements.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_newline_statements.stdout")
