set(CASE_NAME cwhip_package_version_pins)
set(CASE_FIXTURE positive_package_version_pins.cw)
set(CASE_MODULE_ROOT packages)
set(CASE_MODULE_ROOT_SOURCE env)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_package_version_pins.stdout")
