set(CASE_NAME cwhip_compile_and_run_bare_method_calls)
set(CASE_FIXTURE positive_bare_method_calls.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_bare_method_calls.stdout")
