set(CASE_NAME cwhip_stdlib_process_abort)
set(CASE_FIXTURE positive_stdlib_process_abort.cw)
set(CASE_EXPECT_RUNTIME_FAILURE ON)
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC "Cwhip abort: fatal error")
set(CASE_EXPECT_EMPTY_OUTPUT ON)
