set(CASE_NAME cwhip_compile_and_run_slice_bounds_and_steps)
set(CASE_FIXTURE positive_slice_bounds_and_steps.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_slice_bounds_and_steps.stdout")
