set(CASE_NAME cwhip_reports_compound_division_overflow)
set(CASE_FIXTURE negative_compound_division_overflow.cw)
set(CASE_EXPECT_RUNTIME_FAILURE ON)
set(CASE_EXPECT_EMPTY_OUTPUT ON)
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC [==[cwhip: uncaught runtime exception at .*negative_compound_division_overflow.cw:4:11: integer overflow]==])
