set(CASE_NAME cwhip_compile_and_run_checked_extractions)
set(CASE_FIXTURE positive_checked_extractions.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_checked_extractions.stdout")
