set(CASE_NAME cwhip_reports_uncaught_negative_buffer_index)
set(CASE_FIXTURE negative_buffer_index_bounds_uncaught.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_reports_uncaught_map_slice_bounds.stdout")
set(CASE_EXPECT_RUNTIME_FAILURE [==[ON]==])
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC [==[uncaught runtime exception at .*negative_buffer_index_bounds_uncaught.cw:4:[0-9]+: buffer index out of bounds]==])
