set(CASE_NAME cwhip_compile_and_run_typed_exceptions)
set(CASE_FIXTURE positive_typed_exceptions.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_typed_exceptions.stdout")
