set(CASE_NAME cwhip_namespace_qualified_construction_and_call)
set(CASE_FIXTURE positive_namespace_qualified_call.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_namespace_qualified_construction_and_call.stdout")
