set(CASE_NAME cwhip_positive_inline_array_capture)
set(CASE_FIXTURE positive_inline_array_capture.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_positive_inline_array_capture.stdout")
