set(CASE_NAME cwhip_namespace_distinct_short_names)
set(CASE_FIXTURE positive_namespace_collisions.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_namespace_distinct_short_names.stdout")
