set(CASE_NAME cwhip_namespace_across_included_source)
set(CASE_FIXTURE positive_namespace_include.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_namespace_across_included_source.stdout")
