set(CASE_NAME cwhip_stdlib_synchronization_contention)
set(CASE_FIXTURE positive_stdlib_synchronization_contention.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_stdlib_synchronization_contention.stdout")
