set(CASE_NAME cwhip_compile_and_run_checked_integer_casts)
set(CASE_FIXTURE positive_checked_integer_casts.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_checked_integer_casts.stdout")
