set(CASE_NAME cwhip_debug_info)
set(CASE_FIXTURE positive_debug_info.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_debug_info.stdout")
set(CASE_DEBUG_INFO ON)
set(CASE_DEBUG_LINE 3)
set(CASE_DEBUG_LOCAL debugger_local)
