set(CASE_NAME cwhip_reports_uncaught_runtime_stack_trace)
set(CASE_FIXTURE negative_uncaught_runtime_stack_trace.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_reports_uncaught_runtime_stack_trace.stdout")
set(CASE_EXPECT_RUNTIME_FAILURE [==[ON]==])
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC [==[cwhip: uncaught runtime exception at .*negative_uncaught_runtime_stack_trace.cw:[0-9]+:[0-9]+: division by zero]==])
set(CASE_EXPECT_RUNTIME_FRAMES [==[at Worker.inner|at Worker.middle|at Worker.outer|at start]==])
