set(CASE_NAME cwhip_rejects_sqlite_statement_handle_constructor)
set(CASE_FIXTURE negative_sqlite_statement_handle_constructor.cw)
set(CASE_MODULE_ROOT_SOURCE stdlib)
set(CASE_MODULE_ROOT "${CWHIP_STAGE_PREFIX}/${CMAKE_INSTALL_DATADIR}/cwhip/modules")
set(CASE_EXPECTED_DIAGNOSTIC "constructor argument count does not match class 'SQLite.Statement'")
