set(CASE_NAME cwhip_compile_and_run_imported_class_integer_enums)
set(CASE_FIXTURE positive_imported_class_integer_enums.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_imported_class_integer_enums.stdout")
set(CASE_MODULE_ROOT packages)
