set(CASE_NAME cwhip_compile_and_run_return_parentheses)
set(CASE_FIXTURE positive_return_parentheses.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_return_parentheses.stdout")
