set(CASE_NAME cwhip_compile_and_run_print_no_newline)
set(CASE_FIXTURE positive_print_no_newline.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_print_no_newline.stdout")
