set(CASE_NAME cwhip_compile_and_run_nested_returns)
set(CASE_FIXTURE positive_nested_returns.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_compile_and_run_nested_returns.stdout")
