set(CASE_NAME cwhip_rejects_missing_cli_module_root)
set(CASE_FIXTURE positive_package_version_pins.cw)
set(CASE_MODULE_ROOT_SOURCE cli)
set(CASE_MODULE_ROOT_MISSING [==[ON]==])
set(CASE_EXPECTED_DIAGNOSTIC [==[module directory from -M/--module-dir does not exist or is not a directory: <MODULE_ROOT>]==])
