set(CASE_NAME cwhip_reports_uncaught_runtime_exception)
set(CASE_FIXTURE negative_uncaught_exception.cw)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/cwhip_reports_uncaught_runtime_exception.stdout")
set(CASE_EXPECT_RUNTIME_FAILURE [==[ON]==])
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC [==[cwhip: uncaught runtime exception at .*negative_uncaught_exception.cw:3:3: uncaught sentinel]==])
