set(CASE_NAME simp_compile_and_run_runtime_exceptions)
set(CASE_FIXTURE positive_runtime_exceptions.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_runtime_exceptions.stdout")
