set(CASE_NAME simp_compile_and_run_utf8_string_format)
set(CASE_FIXTURE positive_string_format.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_utf8_string_format.stdout")
