set(CASE_NAME simp_compile_and_run_string_invalid_utf8)
set(CASE_FIXTURE positive_string_invalid_utf8.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_string_invalid_utf8.stdout")
