set(CASE_NAME simp_compile_and_run_include_relative_path)
set(CASE_FIXTURE positive_include_relative_path.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_include_relative_path.stdout")
