set(CASE_NAME simp_compile_and_run_return_parentheses)
set(CASE_FIXTURE positive_return_parentheses.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_return_parentheses.stdout")
