set(CASE_NAME simp_compile_and_run_object_identity)
set(CASE_FIXTURE positive_object_identity.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_object_identity.stdout")
