set(CASE_NAME simp_reports_uncaught_missing_map_key)
set(CASE_FIXTURE negative_map_missing_key.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_reports_uncaught_missing_map_key.stdout")
set(CASE_EXPECT_RUNTIME_FAILURE [==[ON]==])
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC [==[uncaught runtime exception at .*negative_map_missing_key.simp:4:17: dict key not found]==])
