set(CASE_NAME simp_compile_and_run_exception_bindings)
set(CASE_FIXTURE positive_exception_binding.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_exception_bindings.stdout")
