set(CASE_NAME simp_compile_and_run_newline_statements)
set(CASE_FIXTURE positive_newline_statements.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_newline_statements.stdout")
