set(CASE_NAME simp_compile_and_run_implicit_imported_base)
set(CASE_FIXTURE positive_implicit_imported_base.simp)
set(CASE_MODULE_PACKAGES ON)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_implicit_imported_base.stdout")
