set(CASE_NAME simp_compile_and_run_class_integer_enums)
set(CASE_FIXTURE positive_class_integer_enums.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_class_integer_enums.stdout")
