set(CASE_NAME simp_reports_uncaught_runtime_operator_location)
set(CASE_FIXTURE negative_uncaught_division.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_reports_uncaught_runtime_operator_location.stdout")
set(CASE_EXPECT_RUNTIME_FAILURE [==[ON]==])
set(CASE_EXPECT_RUNTIME_DIAGNOSTIC [==[simp: uncaught runtime exception at .*negative_uncaught_division.simp:3:11: division by zero]==])
