set(CASE_NAME simp_compile_and_run_transitive_virtual_bases)
set(CASE_FIXTURE positive_transitive_virtual_bases.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_transitive_virtual_bases.stdout")
