set(CASE_NAME simp_namespace_out_of_line_method)
set(CASE_FIXTURE positive_namespace_out_of_line.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_namespace_out_of_line_method.stdout")
