set(CASE_NAME simp_compile_and_run_direct_constructor_declarations)
set(CASE_FIXTURE positive_direct_constructor_declarations.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_direct_constructor_declarations.stdout")
