set(CASE_NAME simp_compile_and_run_constructor_overloads_out_of_line)
set(CASE_FIXTURE positive_constructor_overloads_out_of_line.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_constructor_overloads_out_of_line.stdout")
