set(CASE_NAME simp_namespace_qualified_construction_and_call)
set(CASE_FIXTURE positive_namespace_qualified_call.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_namespace_qualified_construction_and_call.stdout")
