set(CASE_NAME simp_compile_and_run_checked_integer_casts)
set(CASE_FIXTURE positive_checked_integer_casts.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_checked_integer_casts.stdout")
