set(CASE_NAME simp_compile_and_run_integer_control_flow)
set(CASE_FIXTURE positive_integer_control_flow.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_integer_control_flow.stdout")
