set(CASE_NAME simp_compile_and_run_string_methods)
set(CASE_FIXTURE positive_string_methods.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_string_methods.stdout")
