set(CASE_NAME simp_compile_and_run_method_overloads)
set(CASE_FIXTURE positive_method_overloads.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_method_overloads.stdout")
