set(CASE_NAME simp_namespace_across_included_source)
set(CASE_FIXTURE positive_namespace_include.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_namespace_across_included_source.stdout")
