set(CASE_NAME simp_compile_and_run_include_namespace_merge)
set(CASE_FIXTURE positive_include_namespace_merge.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_include_namespace_merge.stdout")
