set(CASE_NAME simp_module_root_package_environment_is_deprecated)
set(CASE_FIXTURE positive_package_version_pins.simp)
set(CASE_MODULE_ROOT packages)
set(CASE_MODULE_ROOT_SOURCE package-env)
set(CASE_EXPECT_WARNING [==[simp: warning: SIMP_PACKAGE_PATH is deprecated]==])
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_package_version_pins.stdout")
