set(CASE_NAME simp_compile_and_run_string_conversion)
set(CASE_FIXTURE positive_string_conversion.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_string_conversion.stdout")
