set(CASE_NAME simp_compile_and_run_scalar_compound_assignments)
set(CASE_FIXTURE positive_scalar_compound_assignments.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_scalar_compound_assignments.stdout")
