set(CASE_NAME simp_positive_inline_array_capture)
set(CASE_FIXTURE positive_inline_array_capture.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_positive_inline_array_capture.stdout")
