set(CASE_NAME simp_package_version_pins)
set(CASE_FIXTURE positive_package_version_pins.simp)
set(CASE_PACKAGE_FIXTURE "${CMAKE_CURRENT_LIST_DIR}/../functional/modules/packages")
set(CASE_PACKAGE_ENVIRONMENT [==[ON]==])
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_package_version_pins.stdout")
