set(CASE_NAME simp_compile_and_run_scalar_cast_boundaries)
set(CASE_FIXTURE positive_scalar_cast_boundaries.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_scalar_cast_boundaries.stdout")
