set(CASE_NAME simp_compile_and_run_parameterized_virtual_base)
set(CASE_FIXTURE positive_parameterized_virtual_base.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_parameterized_virtual_base.stdout")
