set(CASE_NAME simp_compile_and_run_implicit_base_members)
set(CASE_FIXTURE positive_implicit_base_members.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_implicit_base_members.stdout")
