set(CASE_NAME simp_cli_requires_input_without_print_paths)
set(CASE_FIXTURE positive_integer_output.simp)
set(CASE_NO_SOURCE [==[ON]==])
set(CASE_ARGUMENTS --check-only)
set(CASE_EXPECTED_DIAGNOSTIC [==[simp: required argument not found: input]==])
