set(CASE_NAME simp_compile_and_run_nested_returns)
set(CASE_FIXTURE positive_nested_returns.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_nested_returns.stdout")
