set(CASE_NAME simp_compile_and_run_virtual_base_inheritance)
set(CASE_FIXTURE positive_virtual_base_inheritance.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_virtual_base_inheritance.stdout")
