set(CASE_NAME simp_namespace_distinct_short_names)
set(CASE_FIXTURE positive_namespace_collisions.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_namespace_distinct_short_names.stdout")
