set(CASE_NAME simp_compile_and_run_typed_exceptions)
set(CASE_FIXTURE positive_typed_exceptions.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_typed_exceptions.stdout")
