set(CASE_NAME simp_compile_and_run_qualified_secondary_base_dispatch)
set(CASE_FIXTURE positive_qualified_secondary_base_dispatch.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_qualified_secondary_base_dispatch.stdout")
