set(CASE_NAME simp_compile_and_run_constructor_overloads)
set(CASE_FIXTURE positive_constructor_overloads.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_constructor_overloads.stdout")
