set(CASE_NAME simp_compile_and_run_inherited_destructors)
set(CASE_FIXTURE positive_inherited_destructors.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_inherited_destructors.stdout")
