set(CASE_NAME simp_compile_and_run_slice_bounds_and_steps)
set(CASE_FIXTURE positive_slice_bounds_and_steps.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_slice_bounds_and_steps.stdout")
