set(CASE_NAME simp_module_root_standard_modules)
set(CASE_FIXTURE positive_package_version_pins.simp)
set(CASE_MODULE_ROOT packages)
set(CASE_MODULE_ROOT_SOURCE stdlib)
set(CASE_REJECT_COMPILE_OUTPUT [==[warning]==])
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_package_version_pins.stdout")
