set(CASE_NAME simp_module_selection_environment_root)
set(CASE_FIXTURE positive_package_version_pins.simp)
set(CASE_MODULE_ROOT packages)
set(CASE_MODULE_POLICY policy/version-order.toml)
set(CASE_MODULE_ROOT_SOURCE env)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_package_version_pins.stdout")
