set(CASE_NAME simp_compile_and_run_multiple_inheritance)
set(CASE_FIXTURE positive_multiple_inheritance.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_multiple_inheritance.stdout")
