set(CASE_NAME simp_compile_and_run_overload_out_of_line)
set(CASE_FIXTURE positive_overload_out_of_line.simp)
set(CASE_EXPECTED_OUTPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/simp_compile_and_run_overload_out_of_line.stdout")
