/**
 * @file RuntimeDemoShims.h
 * @brief Demonstration C shims for out-of-line native-bound methods.
 * @author Generated by GitHub Copilot
 *
 * These functions exist solely to exercise the native-bound method ABI
 * (see CWHIP-LANGUAGE-NOTES.md, "Out-of-line methods and native C
 * bindings") end-to-end in tests/functional/positive/positive_extern_functions.cw.
 * They are not part of the language runtime proper and are not meant to be
 * called from real Cwhip programs; they live in their own translation
 * unit, separate from the GC/runtime core in RuntimeGc.c, purely for
 * clarity.
 */
#ifndef CWHIP_RUNTIME_DEMO_SHIMS_H
#define CWHIP_RUNTIME_DEMO_SHIMS_H

#include "cwhip/RuntimeGc.h"

/* Every shim receives its Cwhip receiver first, followed by its declared
 * parameters, and validates that the receiver is a live 'Native' instance
 * with the expected marker value before doing any work. This ensures the
 * end-to-end test fails if a generated call omits or misorders the implicit
 * receiver argument. */
int64_t cwhip_method_demo_abs(void *receiver, int64_t value);
void cwhip_method_demo_ignore(void *receiver, int64_t value);
int64_t cwhip_method_demo_string_length(void *receiver, void *text);
void *cwhip_method_demo_string_identity(void *receiver, void *text);
void *cwhip_method_demo_identity(void *receiver, void *object);
int64_t cwhip_method_demo_exception_identity(void *receiver, void *left, void *right);
void *cwhip_method_demo_handle_create(void *receiver);
void cwhip_method_demo_handle_consume(void *receiver, void *handle);
void *cwhip_method_demo_handle_identity(void *receiver, void *handle);

#endif /* CWHIP_RUNTIME_DEMO_SHIMS_H */
