/**
 * @file SemanticAnalyzer.hpp
 * @brief Type, name, and definite-initialization checks for Cwhip.
 * @author Generated by GitHub Copilot
 */
#pragma once

#include "cwhip/Ast.hpp"

#include <cstddef>
#include <filesystem>
#include <iosfwd>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace cwhip {

struct SymbolInfo {
    std::string name;
    std::string type;
    bool initialized = false;
    SourceLocation location;
    bool readOnly = false;
};

class SemanticAnalyzer {
public:
    void analyze(Program& program);
    void dumpSymbolTable(std::ostream& output) const;
    /// Overrides the String builtin source; defaults to the resolved resource path.
    void setBuiltinSource(std::filesystem::path path);

private:
    using Scope = std::unordered_map<std::string, std::size_t>;
    struct ImportBinding {
        std::string qualifiedName;
        std::string moduleName;
    };

    const ClassDeclaration* findClass(const std::string& name,
                                      const SourceLocation& location) const;
    std::string resolveClassName(const std::string& name,
                                 const std::vector<std::string>& namespacePath,
                                 const SourceLocation& location) const;
    std::optional<std::string> lookupClassName(
        const std::string& name, const std::vector<std::string>& namespacePath,
        std::string& diagnostic) const;
    bool hasNamespaceOrClass(const std::string& name,
                             const std::vector<std::string>& namespacePath) const;
    std::string qualify(const std::vector<std::string>& path,
                        const std::string& name) const;
    const std::unordered_map<std::string, ImportBinding>& activeImports() const;
    void normalizeType(std::string& type, const std::vector<std::string>& namespacePath,
                       const SourceLocation& location) const;
    void normalizeStatements(std::vector<Statement>& statements,
                             const std::vector<std::string>& namespacePath);
    void normalizeExpression(Expression& expression,
                             const std::vector<std::string>& namespacePath);
    const FieldDeclaration* findField(const ClassDeclaration& declaration,
                                      const std::string& name) const;
    std::size_t countFields(const ClassDeclaration& declaration,
                            const std::string& name) const;
    const EnumMemberDeclaration* findEnumMember(const ClassDeclaration& declaration,
                                                const std::string& name) const;
    std::size_t countEnumMembers(const ClassDeclaration& declaration,
                                 const std::string& name) const;
    void resolveEnumConstants(Program& program);
    std::int64_t resolveEnumValue(ClassDeclaration& declaration, std::size_t index);
    std::int64_t evaluateEnumExpression(Expression& expression,
                                        ClassDeclaration& declaration,
                                        std::size_t memberIndex);
    const MethodDeclaration* findMethod(const ClassDeclaration& declaration,
                                        const std::string& name) const;
    std::vector<const MethodDeclaration*> findOverloads(const ClassDeclaration& declaration,
                                                        const std::string& name) const;
    const MethodDeclaration* selectOverload(
        const std::vector<const MethodDeclaration*>& candidates,
        const std::vector<std::unique_ptr<Expression>>& arguments,
        const std::vector<std::string>& argumentTypes, bool& ambiguous);
    std::string overloadArgumentType(Expression& argument,
        const std::vector<const MethodDeclaration*>& candidates, std::size_t index);
    int conversionRank(const std::string& target, const std::string& source,
                       const Expression& argument) const;
    std::size_t countMethods(const ClassDeclaration& declaration,
                             const std::string& name) const;
    std::vector<std::string> virtualBaseNames(const ClassDeclaration& declaration) const;
    std::size_t accessibleMemberCount(const ClassDeclaration& declaration,
                                      const std::string& name, bool method) const;
    void addImplicitBaseReceiver(Expression& receiver);
    bool resolveBaseQualifier(Expression& receiver, Expression*& root,
                             const ClassDeclaration*& view,
                             std::vector<std::string>& path);
    bool memberAccessible(const ClassDeclaration& owner, const std::string& name,
                          bool method) const;
    bool memberAccessible(const ClassDeclaration& owner,
                          const MethodDeclaration& method) const;
    bool memberAccessibleThrough(const ClassDeclaration& owner,
                                 const MethodDeclaration& method) const;
    bool basePathAccessible(const ClassDeclaration& owner,
                            const std::vector<std::string>& path) const;
    bool isAssignable(const std::string& target, const std::string& source) const;
    bool isSubclassOf(const std::string& type, const std::string& base) const;
    std::vector<const FieldDeclaration*> inheritedFields(const ClassDeclaration& declaration) const;
    std::string analyzeExpression(Expression& expression,
                                  const std::string& expectedType = {});
    std::string analyzeLValue(Expression& expression);
    void analyzeStatements(std::vector<Statement>& statements);
    void analyzeStatement(Statement& statement);
    std::size_t findSymbolIndex(const std::string& name) const;
    void analyzeMethod(const ClassDeclaration& owner, MethodDeclaration& method);
    void validateType(const std::string& type, const SourceLocation& location,
                      bool allowVoid = false) const;
    void validateExternalMethodType(const std::string& type, const SourceLocation& location,
                                    bool allowVoid) const;
    std::vector<bool> initializationState() const;
    void restoreInitializationState(const std::vector<bool>& state);

    std::vector<Scope> scopes_;
    std::vector<SymbolInfo> symbols_;
    std::unordered_set<std::string> namespaces_;
    std::unordered_map<std::string, std::string> namespaceOwners_;
    std::unordered_map<std::string, ClassDeclaration*> classes_;
    std::unordered_map<std::string, OutOfLineMethodDefinition*> methodDefinitions_;
    const ClassDeclaration* currentClass_ = nullptr;
    const MethodDeclaration* currentMethod_ = nullptr;
    std::vector<std::string> currentNamespace_;
    std::string currentModule_;
    std::size_t loopDepth_ = 0;
    std::size_t exceptionHandlerDepth_ = 0;
    std::size_t finallyDepth_ = 0;
    std::optional<std::filesystem::path> builtinSource_;
    std::unordered_map<std::string,
        std::unordered_map<std::string, ImportBinding>> importAliases_;
};

} // namespace cwhip
