/**
 * @file json_lite.hpp
 * @brief Minimal JSON parser for per-fixture .simp.json objects with string
 *        and boolean fields. This is intentionally not a general-purpose
 *        JSON library (no numbers or Unicode escapes); the test driver uses
 *        it without vendoring a third-party dependency.
 * @author Generated by GitHub Copilot
 */
#pragma once

#include <cctype>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace simp_test_json {

/// Thrown for any malformed or unsupported JSON input. Kept distinct from
/// std::runtime_error only in name, so callers can catch either.
class JsonError : public std::runtime_error {
public:
    explicit JsonError(const std::string& message) : std::runtime_error(message) {}
};

enum class JsonType { Object, Array, String, Boolean };

struct JsonValue {
    JsonType type = JsonType::Object;
    std::string stringValue;
    bool boolValue = false;
    std::vector<JsonValue> arrayValue;
    std::vector<std::pair<std::string, JsonValue>> objectValue;

    /// Looks up a required object field, throwing a clear error if absent.
    const JsonValue& at(const std::string& key) const {
        for (const auto& entry : objectValue) {
            if (entry.first == key) {
                return entry.second;
            }
        }
        throw JsonError("missing required JSON field: " + key);
    }
};

/// Recursive-descent parser for the restricted JSON subset described above.
class JsonParser {
public:
    explicit JsonParser(const std::string& text) : text_(text) {}

    JsonValue parse() {
        skipWhitespace();
        JsonValue value = parseValue();
        skipWhitespace();
        if (pos_ != text_.size()) {
            fail("unexpected trailing content after JSON value");
        }
        return value;
    }

private:
    std::string text_;
    std::size_t pos_ = 0;

    [[noreturn]] void fail(const std::string& message) const {
        throw JsonError(message + " (offset " + std::to_string(pos_) + ")");
    }

    void skipWhitespace() {
        while (pos_ < text_.size() &&
               std::isspace(static_cast<unsigned char>(text_[pos_]))) {
            ++pos_;
        }
    }

    void expect(char c) {
        if (pos_ >= text_.size() || text_[pos_] != c) {
            fail(std::string("expected '") + c + "'");
        }
        ++pos_;
    }

    JsonValue parseValue() {
        skipWhitespace();
        if (pos_ >= text_.size()) {
            fail("unexpected end of input while parsing a value");
        }
        switch (text_[pos_]) {
            case '{': return parseObject();
            case '[': return parseArray();
            case '"': return parseString();
            case 't':
            case 'f': return parseBoolean();
            default:
                fail("unsupported JSON value; only objects, arrays, strings, "
                     "and booleans are supported");
        }
    }

    JsonValue parseObject() {
        JsonValue value;
        value.type = JsonType::Object;
        expect('{');
        skipWhitespace();
        if (pos_ < text_.size() && text_[pos_] == '}') {
            ++pos_;
            return value;
        }
        while (true) {
            skipWhitespace();
            JsonValue key = parseString();
            skipWhitespace();
            expect(':');
            JsonValue fieldValue = parseValue();
            value.objectValue.emplace_back(std::move(key.stringValue), std::move(fieldValue));
            skipWhitespace();
            if (pos_ < text_.size() && text_[pos_] == ',') {
                ++pos_;
                continue;
            }
            break;
        }
        skipWhitespace();
        expect('}');
        return value;
    }

    JsonValue parseArray() {
        JsonValue value;
        value.type = JsonType::Array;
        expect('[');
        skipWhitespace();
        if (pos_ < text_.size() && text_[pos_] == ']') {
            ++pos_;
            return value;
        }
        while (true) {
            value.arrayValue.push_back(parseValue());
            skipWhitespace();
            if (pos_ < text_.size() && text_[pos_] == ',') {
                ++pos_;
                continue;
            }
            break;
        }
        skipWhitespace();
        expect(']');
        return value;
    }

    JsonValue parseString() {
        expect('"');
        std::string result;
        while (true) {
            if (pos_ >= text_.size()) {
                fail("unterminated string literal");
            }
            char c = text_[pos_++];
            if (c == '"') {
                break;
            }
            if (c == '\\') {
                if (pos_ >= text_.size()) {
                    fail("unterminated escape sequence");
                }
                char escaped = text_[pos_++];
                switch (escaped) {
                    case '"': result += '"'; break;
                    case '\\': result += '\\'; break;
                    case '/': result += '/'; break;
                    case 'n': result += '\n'; break;
                    case 't': result += '\t'; break;
                    case 'r': result += '\r'; break;
                    default:
                        fail(std::string("unsupported escape sequence '\\") + escaped + "'");
                }
            } else {
                result += c;
            }
        }
        JsonValue value;
        value.type = JsonType::String;
        value.stringValue = std::move(result);
        return value;
    }

    JsonValue parseBoolean() {
        JsonValue value;
        value.type = JsonType::Boolean;
        if (text_.compare(pos_, 4, "true") == 0) {
            value.boolValue = true;
            pos_ += 4;
        } else if (text_.compare(pos_, 5, "false") == 0) {
            value.boolValue = false;
            pos_ += 5;
        } else {
            fail("expected boolean literal 'true' or 'false'");
        }
        return value;
    }
};

} // namespace simp_test_json
