/**
 * @file test_gc_runtime.c
 * @brief Direct tests for precise root frames and object graph tracing.
 * @author Generated by GitHub Copilot
 */
#include "simp/RuntimeGc.h"

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct TestNode {
    const SimpClassMeta *metadata;
    struct TestNode *next;
    int value;
} TestNode;

static const uint64_t reference_offsets[] = {offsetof(TestNode, next)};
static const SimpClassMeta node_metadata = {
    "TestNode", 8, 2, NULL, 0, sizeof(TestNode), 1, reference_offsets, NULL, 0, NULL
};

typedef struct FinalizeNode {
    const SimpClassMeta *metadata;
    int value;
} FinalizeNode;

static int finalizer_count = 0;
static FinalizeNode **resurrection_slot = NULL;
static int resurrect_during_finalization = 0;

static void count_finalizer(void *object) {
    FinalizeNode *node = (FinalizeNode *)object;
    if (node->value != 73) abort();
    ++finalizer_count;
    if (resurrect_during_finalization) *resurrection_slot = node;
}

static const SimpClassMeta finalize_metadata = {
    "FinalizeNode", 12, 1, NULL, 0, sizeof(FinalizeNode), 0, NULL, count_finalizer, 0, NULL
};

static int fail(const char *message) {
    fprintf(stderr, "GC test failed: %s\n", message);
    return 1;
}

int main(void) {
    SimpRootFrame outer = {0};
    SimpRootFrame inner = {0};
    TestNode *head = NULL;
    TestNode *tail = NULL;
    void *head_slots[] = {&head};
    void *tail_slots[] = {&tail};
    SimpRootFrame invalid = {0};

    if (simp_gc_push(NULL, NULL, 0)) {
        return fail("null frame push was accepted");
    }
    if (simp_gc_push(&invalid, NULL, 1)) {
        return fail("missing slot descriptor was accepted");
    }
    void *invalid_slots[] = {NULL};
    if (simp_gc_push(&invalid, invalid_slots, 1)) {
        return fail("null root slot was accepted");
    }
    if (!simp_gc_push(&outer, head_slots, 1)) {
        return fail("could not push outer root frame");
    }
    if (simp_gc_push(&outer, head_slots, 1)) {
        return fail("duplicate active frame was accepted");
    }
    if (!simp_gc_push(&inner, tail_slots, 1)) {
        return fail("could not push inner root frame");
    }
    if (simp_gc_pop(&outer)) {
        return fail("out-of-order pop was accepted");
    }
    if (simp_gc_pop(NULL)) {
        return fail("null frame pop was accepted");
    }
    head = (TestNode *)simp_gc_alloc(&node_metadata);
    head->value = 1;
    tail = (TestNode *)simp_gc_alloc(&node_metadata);
    tail->value = 2;
    head->next = tail;
    tail = NULL;
    simp_gc_collect();
    if (simp_gc_heap_count() != 2 || head->next->value != 2) {
        return fail("reachable object in a reference field was not preserved");
    }

    tail = head->next;
    head->next = NULL;
    simp_gc_collect();
    if (simp_gc_heap_count() != 2 || tail->value != 2) {
        return fail("root in a nested frame was not preserved");
    }
    if (!simp_gc_pop(&inner)) {
        return fail("could not pop inner root frame");
    }
    tail = NULL;
    simp_gc_collect();
    if (simp_gc_heap_count() != 1) {
        return fail("object held only by the popped frame was not reclaimed");
    }

    head = NULL;
    simp_gc_collect();
    if (simp_gc_heap_count() != 0) {
        return fail("unreachable objects were not reclaimed");
    }
    void *unlisted = simp_gc_alloc(&node_metadata);
    volatile uintptr_t unlisted_address = (uintptr_t)unlisted;
    unlisted = NULL;
    simp_gc_collect();
    if (unlisted_address == 0 || simp_gc_heap_count() != 0) {
        return fail("object outside explicit root descriptors was retained");
    }
    if (!simp_gc_pop(&outer)) {
        return fail("could not pop outer root frame");
    }

    SimpRootFrame finalizer_frame = {0};
    FinalizeNode *rooted = NULL;
    void *finalizer_slots[] = {&rooted};
    if (!simp_gc_push(&finalizer_frame, finalizer_slots, 1)) {
        return fail("could not push finalizer test root");
    }
    rooted = (FinalizeNode *)simp_gc_alloc(&finalize_metadata);
    rooted->value = 73;
    simp_gc_collect();
    if (finalizer_count != 0 || simp_gc_heap_count() != 1) {
        return fail("reachable object was finalized");
    }
    rooted = NULL;
    simp_gc_collect();
    if (finalizer_count != 1 || simp_gc_heap_count() != 0) {
        return fail("unreachable object was not finalized and reclaimed exactly once");
    }

    rooted = (FinalizeNode *)simp_gc_alloc(&finalize_metadata);
    rooted->value = 73;
    resurrection_slot = &rooted;
    resurrect_during_finalization = 1;
    rooted = NULL;
    simp_gc_collect();
    resurrect_during_finalization = 0;
    if (finalizer_count != 2 || simp_gc_heap_count() != 1 || rooted == NULL) {
        return fail("resurrected object was not retained after one finalizer call");
    }
    rooted = NULL;
    simp_gc_collect();
    if (finalizer_count != 2 || simp_gc_heap_count() != 0) {
        return fail("resurrected destroyed object was finalized twice or not reclaimed");
    }

    rooted = (FinalizeNode *)simp_gc_alloc(&finalize_metadata);
    rooted->value = 73;
    simp_gc_begin_destroy(rooted, "runtime-test.simp", 17, 4, 2);
    simp_gc_end_destroy(rooted);
    rooted = NULL;
    simp_gc_collect();
    if (finalizer_count != 2 || simp_gc_heap_count() != 0) {
        return fail("explicit destruction did not suppress GC finalization");
    }
    if (!simp_gc_pop(&finalizer_frame)) {
        return fail("could not pop finalizer test root");
    }

    SimpRootFrame map_frame = {0};
    SimpMap *map = NULL;
    SimpMap *slice = NULL;
    void *map_slots[] = {&map, &slice};
    if (!simp_gc_push(&map_frame, map_slots, 2)) {
        return fail("could not push map test roots");
    }
    map = (SimpMap *)simp_gc_alloc_map();
    for (int index = 0; index < 64; ++index) {
        char key[8];
        const int key_length = snprintf(key, sizeof(key), "k%02d", index);
        SimpArrayValue value = {SIMP_ARRAY_INTEGER, index, NULL, 0};
        simp_map_set(map, key, (uint64_t)key_length, &value,
                     "runtime-test.simp", 17, 1, 1);
    }
    for (int index = 0; index < 64; ++index) {
        char key[8];
        const int key_length = snprintf(key, sizeof(key), "k%02d", index);
        SimpArrayValue *value = (SimpArrayValue *)simp_map_get(
            map, key, (uint64_t)key_length, "runtime-test.simp", 17, 1, 1);
        if (value->tag != SIMP_ARRAY_INTEGER || value->integer != index) {
            return fail("hashed map lookup returned the wrong insertion");
        }
    }
    if (simp_map_remove(map, "k20", 3, "runtime-test.simp", 17, 1, 1) != 1 ||
        simp_map_remove(map, "absent", 6, "runtime-test.simp", 17, 1, 1) != 0 ||
        map->length != 63) {
        return fail("map removal returned an invalid result or length");
    }
    SimpArrayValue tail_value = {SIMP_ARRAY_INTEGER, 99, NULL, 0};
    simp_map_set(map, "tail", 4, &tail_value, "runtime-test.simp", 17, 1, 1);
    const SimpMapEntry *first = (const SimpMapEntry *)simp_map_entry_at(
        map, 20, "runtime-test.simp", 17, 1, 1);
    if (first->key_length != 3 || memcmp(first->key, "k21", 3) != 0) {
        return fail("map removal did not preserve insertion-order iteration");
    }
    slice = (SimpMap *)simp_map_slice(map, 10, 12, "runtime-test.simp", 17, 1, 1);
    const SimpMapEntry *slice_first = (const SimpMapEntry *)simp_map_entry_at(
        slice, 0, "runtime-test.simp", 17, 1, 1);
    if (slice->length != 2 || slice_first->key_length != 3 ||
        memcmp(slice_first->key, "k10", 3) != 0) {
        return fail("map slice did not make an insertion-order shallow copy");
    }
    SimpArray *nested = (SimpArray *)simp_gc_alloc_array(0);
    SimpArrayValue nested_value = {SIMP_ARRAY_ARRAY, 0, nested, 0};
    simp_map_set(map, "nested", 6, &nested_value, "runtime-test.simp", 17, 1, 1);
    nested = NULL;
    simp_gc_collect();
    if (simp_gc_heap_count() != 3) {
        return fail("map did not retain a nested array through GC tracing");
    }
    if (simp_map_remove(map, "nested", 6, "runtime-test.simp", 17, 1, 1) != 1) {
        return fail("map could not remove its nested array value");
    }
    simp_gc_collect();
    if (simp_gc_heap_count() != 2) {
        return fail("removed collection value remained reachable through its map");
    }
    map = NULL;
    slice = NULL;
    simp_gc_collect();
    if (simp_gc_heap_count() != 0 || !simp_gc_pop(&map_frame)) {
        return fail("map and slice roots were not released cleanly");
    }
    SimpRootFrame tagged_frame = {0};
    SimpArrayValue dynamic_value = {0};
    void *dynamic_slots[] = {&dynamic_value.pointer};
    const uint64_t *dynamic_tags[] = {&dynamic_value.tag};
    simp_gc_push_tagged_or_abort(&tagged_frame, dynamic_slots, dynamic_tags, 1);
    dynamic_value.tag = SIMP_ARRAY_BUFFER;
    dynamic_value.pointer = simp_buffer_new(2, "runtime-test.simp", 17, 1, 1);
    simp_gc_collect();
    const SimpBuffer *buffer = (const SimpBuffer *)dynamic_value.pointer;
    if (simp_gc_heap_count() != 1 || buffer->length != 2 ||
        buffer->data[0] != 0 || buffer->data[1] != 0) {
        return fail("tagged roots did not preserve a zero-filled buffer");
    }
    dynamic_value.tag = SIMP_ARRAY_HANDLE;
    dynamic_value.pointer = simp_gc_alloc(&node_metadata);
    simp_gc_collect();
    if (simp_gc_heap_count() != 0) {
        return fail("opaque handle payload was traced as a GC reference");
    }
    simp_gc_pop_or_abort(&tagged_frame);
    puts("PASS precise roots, reclamation, finalization, destruction, and frame lifecycle");
    return 0;
}
