/**
 * @file test_driver.cpp
 * @brief Standard-library-only lexer, parser, diagnostic, and program tests.
 * @author Generated by GitHub Copilot
 */
#include "simp/Ast.hpp"
#include "simp/Diagnostic.hpp"
#include "simp/Lexer.hpp"
#include "simp/Parser.hpp"
#include "simp/SemanticAnalyzer.hpp"
#include "simp/Token.hpp"

#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace {

using Test = std::pair<std::string, std::function<void()>>;

struct FunctionalCase {
    const char* description;
    const char* fixture;
    const char* expectedDiagnostic;
};

void require(bool condition, const std::string& message) {
    if (!condition) {
        throw std::runtime_error(message);
    }
}

std::string readFile(const std::string& path) {
    std::ifstream input(path);
    if (!input) {
        throw std::runtime_error("cannot read test program: " + path);
    }
    return {std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>()};
}

simp::Program parse(const std::string& source, const std::string& name = "test.simp") {
    simp::Lexer lexer(source, name);
    auto program = simp::Parser(lexer.tokenize()).parseProgram();
    simp::SemanticAnalyzer analyzer;
    analyzer.analyze(program);
    return program;
}

void expectDiagnostic(const std::string& source, const std::string& expected) {
    try {
        parse(source);
    } catch (const simp::DiagnosticError& error) {
        require(std::string(error.what()).find(expected) != std::string::npos,
                "diagnostic did not contain: " + expected + "; got: " + error.what());
        return;
    }
    throw std::runtime_error("expected diagnostic containing: " + expected);
}

void runFunctional(const std::string& filename, const std::string& expectedError = "") {
    const auto path = std::string(SIMP_TEST_SOURCE_DIR) + "/" + filename;
    try {
        parse(readFile(path), path);
    } catch (const simp::DiagnosticError& error) {
        if (expectedError.empty()) {
            throw;
        }
        require(std::string(error.what()).find(expectedError) != std::string::npos,
                "unexpected diagnostic: " + std::string(error.what()));
        return;
    }
    require(expectedError.empty(), "expected functional program to fail: " + filename);
}

void expectValid(const std::string& source) {
    parse(source);
}

} // namespace

int main() {
    std::vector<Test> tests{
        {"lexer keywords and strings", [] {
             simp::Lexer lexer("StArT {\n INT n = 12\n string s = \"a\\n\"\n}", "lexer.simp");
             const auto tokens = lexer.tokenize();
             require(tokens[0].type == simp::TokenType::Start, "START keyword not recognized");
             require(tokens[3].type == simp::TokenType::Int, "INT keyword not recognized");
             require(tokens[5].type == simp::TokenType::Equal, "assignment token missing");
             require(tokens[6].type == simp::TokenType::Integer && tokens[6].text == "12",
                     "integer token incorrect");
             require(tokens[11].type == simp::TokenType::String &&
                         tokens[11].text == "a\n" && tokens[11].formattedString,
                     "escaped formatted string incorrect");
         }},
        {"single-quoted strings are literal", [] {
             simp::Lexer lexer("start {\n print('a\\n')\n}", "single-quoted.simp");
             const auto tokens = lexer.tokenize();
             require(tokens[5].type == simp::TokenType::String, "single-quoted token missing");
             require(tokens[5].text == "a\\n", "single-quoted backslash was interpreted");
             require(!tokens[5].formattedString, "single-quoted token was marked formatted");
         }},
        {"semicolon line comments", [] {
             simp::Lexer lexer("start {\n print(1) ; comment to newline\n print(2)\n}",
                               "semicolon-comment.simp");
             const auto tokens = lexer.tokenize();
             std::size_t integers = 0;
             for (const auto& token : tokens) {
                 if (token.type == simp::TokenType::Integer) ++integers;
             }
             require(integers == 2, "semicolon comment swallowed the following line");
         }},
        {"hash line comments", [] {
             simp::Lexer lexer("start {\n # comment\n print(2)\n}", "hash-comment.simp");
             const auto tokens = lexer.tokenize();
             bool foundPrint = false;
             for (const auto& token : tokens) foundPrint |= token.type == simp::TokenType::Print;
             require(foundPrint,
                     "hash comment did not preserve the following line");
         }},
        {"slash line comments", [] {
             simp::Lexer lexer("start {\n // comment\n print(2)\n}", "slash-comment.simp");
             const auto tokens = lexer.tokenize();
             bool foundPrint = false;
             for (const auto& token : tokens) foundPrint |= token.type == simp::TokenType::Print;
             require(foundPrint,
                     "slash comment did not preserve the following line");
         }},
        {"block comments preserve statement boundaries", [] {
             simp::Lexer lexer("start {\n int value = 1 /* comment\ncontinued */\n print(value)\n}",
                               "block-comment.simp");
             const auto tokens = lexer.tokenize();
             std::size_t newlines = 0;
             for (const auto& token : tokens) {
                 if (token.type == simp::TokenType::Newline) ++newlines;
             }
             require(newlines >= 3, "block comment swallowed statement-boundary newlines");
         }},
        {"unterminated block comment diagnostic", [] {
             expectDiagnostic("start {\n /* comment", "unterminated block comment");
         }},
        {"reserved keywords", [] {
             expectDiagnostic("start {\n int While = 0\n}", "keywords are reserved");
         }},
        {"import keyword is case-insensitive and reserved", [] {
             simp::Lexer lexer("IMPORT network AS Net\nstart {}", "import-keyword.simp");
             const auto tokens = lexer.tokenize();
             require(tokens[0].type == simp::TokenType::Import &&
                         tokens[2].type == simp::TokenType::As,
                     "import keywords were not recognized case-insensitively");
         }},
        {"top-level import syntax is represented in the AST", [] {
             simp::Lexer lexer("import network as Net\nstart {}", "import.simp");
             auto program = simp::Parser(lexer.tokenize()).parseProgram();
             require(program.imports.size() == 1 &&
                         program.imports.front().moduleName == "network" &&
                         program.imports.front().alias == "Net",
                     "import module name or alias missing from AST");
         }},
        {"import requires an alias", [] {
             expectDiagnostic("import network\nstart {}", "expected 'as' after module name");
         }},
        {"import is rejected in declaration and function bodies", [] {
             expectDiagnostic("namespace Hidden { import network as Net }\nstart {}",
                              "'import' is only allowed at top level");
             expectDiagnostic("class Hidden { import network as Net }\nstart {}",
                              "'import' is only allowed at top level");
             expectDiagnostic("start { import network as Net }",
                              "'import' is only allowed at top level");
         }},
        {"create is no longer a reserved keyword", [] {
             simp::Lexer lexer("start {\n int create = 1\n print(create)\n}", "identifier.simp");
             const auto tokens = lexer.tokenize();
             require(tokens[4].type == simp::TokenType::Identifier &&
                         tokens[4].text == "create",
                     "create should be lexed as an identifier");
         }},
        {"class-name constructor syntax", [] {
             const auto program = parse(
                 "class Box { Box() {} }\nstart { Box box = Box() }");
             std::ostringstream output;
             simp::dumpAst(program, output);
             require(output.str().find("ConstructorCall [Box]") != std::string::npos,
                     "class-name constructor call missing from AST");
         }},
        {"single inheritance and base constructor syntax", [] {
             const auto program = parse(
                 "class Base { Base(int value) {} }\n"
                 "class Child : Base { Child(int value) { super.Base(value) } }\n"
                 "start { Child child = Child(1) }");
             std::ostringstream output;
             simp::dumpAst(program, output);
             require(output.str().find("Class [Child : public Base]") != std::string::npos,
                     "base class missing from AST");
             require(output.str().find("Super constructor [Base]") != std::string::npos,
                     "explicit base constructor missing from AST");
         }},
        {"virtual base initializer syntax", [] {
             const auto program = parse(
                 "class Root { Root(int value) {} }\n"
                 "class Leaf : virtual Root {\n"
                 "  Leaf(int value) { super.virtual Root(value) }\n"
                 "}\n"
                 "start { Leaf leaf = Leaf(1) }");
             std::ostringstream output;
             simp::dumpAst(program, output);
             require(output.str().find("Super virtual constructor [Root]") !=
                         std::string::npos,
                     "virtual base initializer missing from AST");
         }},
        {"virtual base syntax is retained in AST", [] {
             const auto program = parse(
                 "class Root {}\n"
                 "class Left : public virtual Root {}\n"
                 "class Other : virtual public Root {}\n"
                 "start {}");
             std::ostringstream output;
             simp::dumpAst(program, output);
             require(output.str().find("Class [Left : public virtual Root]") !=
                         std::string::npos,
                     "virtual base modifier missing from AST");
             require(output.str().find("Class [Other : public virtual Root]") !=
                         std::string::npos,
                     "virtual/access modifier ordering was not accepted");
         }},
        {"parser precedence and AST", [] {
             const auto program = parse("start {\n int x = 1 + 2 * 3\n print(x)\n}");
             require(program.statements.size() == 2, "expected declaration and print");
             std::ostringstream output;
             simp::dumpAst(program, output);
             const auto tree = output.str();
             require(tree.find("Binary [+]") != std::string::npos, "addition absent from AST");
             require(tree.find("Binary [*]") != std::string::npos, "multiplication absent from AST");
         }},
        {"map literals are represented in the AST", [] {
             const auto program = parse(
                 "start {\n map values = {\"answer\": 42}\n}");
             std::ostringstream output;
             simp::dumpAst(program, output);
             require(output.str().find("MapLiteral") != std::string::npos,
                     "map literal missing from AST");
         }},
        {"raise, catch-all, and finally syntax", [] {
             const auto program = parse(
                 "start {\n"
                 "  try { raise \"failure\" } except { print(\"caught\") } "
                 "finally { print(\"done\") }\n"
                 "}");
             std::ostringstream output;
             simp::dumpAst(program, output);
             require(output.str().find("Try") != std::string::npos &&
                         output.str().find("Raise") != std::string::npos &&
                         output.str().find("Except") != std::string::npos &&
                         output.str().find("Finally") != std::string::npos,
                     "exception constructs missing from AST");
         }},
        {"except may bind a read-only exception string", [] {
             const auto program = parse(
                 "start {\n try { raise \"message\" } except error { print(error) }\n}");
             require(program.statements.front().hasExceptionBinding &&
                         program.statements.front().name == "error",
                     "except binding missing from AST");
         }},
        {"try requires a handler or finally", [] {
             expectDiagnostic("start { try { print(1) } }",
                              "requires an 'except' or 'finally' block");
         }},
        {"raise requires string", [] {
             expectDiagnostic("start { raise 42 }", "raise requires a string expression");
         }},
        {"newline statement boundaries", [] {
             const auto program = parse(
                 "class Base {\n"
                 "  int value\n"
                 "  Base(int initial) {\n"
                 "    value = initial\n"
                 "  }\n"
                 "}\n"
                 "class Child : Base {\n"
                 "  Child(int initial) {\n"
                 "    super.Base(initial)\n"
                 "  }\n"
                 "  int read() {\n"
                 "    return value\n"
                 "  }\n"
                 "}\n"
                 "start {\n"
                 "  Child child = Child(40)\n"
                 "  child.value = child.read() + 2\n"
                 "  print(child.value)\n"
                 "}");
             require(program.statements.size() == 3,
                     "expected semicolon-free declarations, assignment, and print");
         }},
        {"adjacent statements without a boundary are rejected", [] {
             expectDiagnostic("start {\n int first = 1 int second = 2\n}",
                              "expected newline after statement");
         }},
        {"parser trace", [] {
             simp::Lexer lexer("start {}", "trace.simp");
             std::ostringstream trace;
             simp::Parser parser(lexer.tokenize(), &trace);
             parser.parseProgram();
             require(trace.str().find("[parser]") != std::string::npos, "parser trace was empty");
         }},
        {"diagnostic source location", [] {
             try {
                 simp::Lexer lexer("start {\n @\n}", "location.simp");
                 lexer.tokenize();
             } catch (const simp::DiagnosticError& error) {
                 require(std::string(error.what()).find("location.simp:2:2: error:") == 0,
                         "diagnostic location was incorrect");
                 return;
             }
             throw std::runtime_error("invalid character did not produce a diagnostic");
         }},
        {"invalid UTF-8 string rejected", [] {
             std::string source = "start { print(\"";
             source.push_back(static_cast<char>(0xc0));
             source += "\"); }";
             try {
                 simp::Lexer lexer(source, "invalid-utf8.simp");
                 lexer.tokenize();
             } catch (const simp::DiagnosticError& error) {
                 require(std::string(error.what()).find("string literal is not valid UTF-8") !=
                             std::string::npos,
                         "invalid UTF-8 diagnostic was missing");
                 return;
             }
             throw std::runtime_error("invalid UTF-8 string was accepted");
         }},
        {"formatted print arity", [] {
             expectDiagnostic("start {\n print(\"value: {}\"(1, 2))\n}",
                              "one '{}' placeholder per argument");
         }},
        {"formatted print malformed brace", [] {
             expectDiagnostic("start {\n print(\"value: {x}\"(1))\n}",
                              "only '{}' placeholders are supported");
         }},
        {"single-quoted string format arguments", [] {
             expectDiagnostic("start {\n print('value: {}'(1))\n}",
                              "format arguments require a double-quoted string literal");
         }},
        {"string condition rejected", [] {
             expectDiagnostic("start { if (\"not a condition\") { } }",
                              "if condition must have type int");
         }},
        {"string equality rejected", [] {
             expectDiagnostic("start {\n string a = \"a\"\n print(a == \"a\")\n}",
                              "equality is implemented only for int values");
         }},
        {"semantic type mismatch", [] {
             expectDiagnostic("start {\n int value = \"wrong\"\n}",
                              "cannot initialize int variable with string");
         }},
        {"semantic assignment type mismatch", [] {
             expectDiagnostic("start {\n int value = 1\n value = \"wrong\"\n}",
                              "cannot assign string to int variable 'value'");
         }},
        {"semantic undefined variable", [] {
             expectDiagnostic("start {\n print(missing)\n}", "undefined variable 'missing'");
         }},
        {"semantic definite initialization", [] {
             expectDiagnostic("start {\n int value\n print(value)\n}",
                              "variable 'value' may be uninitialized");
         }},
        {"semantic branch initialization", [] {
             expectDiagnostic("start {\n int value\n if (1) { value = 1 }\n print(value)\n}",
                              "variable 'value' may be uninitialized");
         }},
        {"semantic initialized in both branches", [] {
             const auto program = parse(
                 "start {\n int value\n if (1) { value = 1 } else { value = 2 }\n print(value)\n}");
             require(program.statements.size() == 3, "expected declaration, if, and print");
         }},
        {"virtual-base initializer rejected outside constructors", [] {
             expectDiagnostic(
                 "class Root { Root(int value) {} }\n"
                 "class Leaf : virtual Root {\n"
                 "  void method() { super.virtual Root(1) }\n"
                 "}\n"
                 "start {}",
                 "super initializers must be direct leading constructor statements");
         }},
        {"out-of-line method body completes an in-class declaration", [] {
             expectValid(
                 "class Foo {\n  int compute(int x)\n}\n"
                 "int Foo.compute(int x) {\n  return x * 2\n}\n"
                 "start {\n  print(Foo().compute(5))\n}");
         }},
        {"external method validates and calls through ordinary method syntax", [] {
             expectValid(
                 "class Native {\n  int absolute(int value)\n}\n"
                 "int Native.absolute(int value) from \"simp_method_demo_abs\"\n"
                 "start {\n  print(Native().absolute(5))\n}");
         }},
        {"external method argument count is validated", [] {
             expectDiagnostic(
                 "class Native {\n  int absolute(int value)\n}\n"
                 "int Native.absolute(int value) from \"simp_method_demo_abs\"\n"
                 "start {\n  print(Native().absolute(1, 2))\n}",
                 "method 'absolute' argument count mismatch");
         }},
        {"external method argument type is validated", [] {
             expectDiagnostic(
                 "class Native {\n  int absolute(int value)\n}\n"
                 "int Native.absolute(int value) from \"simp_method_demo_abs\"\n"
                 "start {\n  string text = \"x\"\n  print(Native().absolute(text))\n}",
                 "method argument type does not match parameter 'value'");
         }},
        {"external method rejects 'any' parameters", [] {
             expectDiagnostic(
                 "class Native {\n  int use(any value)\n}\n"
                 "int Native.use(any value) from \"symbol\"\n"
                 "start {\n  print(1)\n}",
                 "'any' is not supported in external method signatures");
         }},
        {"external method rejects 'any' returns", [] {
             expectDiagnostic(
                 "class Native {\n  any dynamicValue(int value)\n}\n"
                 "any Native.dynamicValue(int value) from \"symbol\"\n"
                 "start {\n  print(1)\n}",
                 "'any' is not supported in external method signatures");
         }},
        {"external method requires a non-empty C symbol", [] {
             expectDiagnostic(
                 "class Native {\n  int value()\n}\n"
                 "int Native.value() from \"\"\n"
                 "start {\n  print(1)\n}",
                 "native-bound method must name a non-empty C symbol");
         }},
        {"out-of-line method signature must match its declaration", [] {
             expectDiagnostic(
                 "class Native {\n  int absolute(int value)\n}\n"
                 "string Native.absolute(string value) from \"symbol\"\n"
                 "start {\n  print(1)\n}",
                 "out-of-line definition signature does not match declaration");
         }},
        {"out-of-line method definition must be unique", [] {
             expectDiagnostic(
                 "class Native {\n  int absolute(int value)\n}\n"
                 "int Native.absolute(int value) from \"symbol\"\n"
                 "int Native.absolute(int value) from \"symbol\"\n"
                 "start {\n  print(1)\n}",
                 "duplicate out-of-line definition for method 'Native.absolute'");
         }},
        {"out-of-line methods require an in-class declaration", [] {
             expectDiagnostic(
                 "class Native {\n}\n"
                 "int Native.absolute(int value) from \"symbol\"\n"
                 "start {\n  print(1)\n}",
                 "has no in-class declaration for method 'absolute'");
         }},
        {"bodyless method declarations require a definition", [] {
             expectDiagnostic(
                 "class Native {\n  int absolute(int value)\n}\n"
                 "start {\n  print(1)\n}",
                 "is declared but has no out-of-line definition");
         }},
        {"external symbols require ABI-compatible method signatures", [] {
             expectDiagnostic(
                 "class Native {\n"
                 "  int integerValue(int value)\n"
                 "  string stringValue(string value)\n"
                 "}\n"
                 "int Native.integerValue(int value) from \"same_symbol\"\n"
                 "string Native.stringValue(string value) from \"same_symbol\"\n"
                 "start {\n  print(1)\n}",
                 "is reused with an incompatible method signature");
         }},
        {"legacy top-level extern declaration syntax is rejected", [] {
             expectDiagnostic(
                 "extern int c_abs(int value) from \"abs\"\n"
                 "start {\n  print(1)\n}",
                 "program must contain exactly one top-level 'start' block");
         }},
        {"array literals accept mixed int, string, and class values", [] {
             expectValid(
                 "class Widget {\n  int id\n  Widget(int initial) { id = initial }\n}\n"
                 "start {\n"
                 "  array bag = [1, \"two\", Widget(3), null]\n"
                 "  print(bag.length)\n"
                 "}");
         }},
        {"'list' is an alias for the 'array' type", [] {
             expectValid("start {\n"
                         "  list values = [1, \"two\"]\n"
                         "  array alias = values\n"
                         "  print(alias.length)\n"
                         "}");
         }},
        {"array element reads yield 'any' and can be extracted by type", [] {
             expectValid("start {\n"
                         "  array bag = [1, \"two\"]\n"
                         "  any first = bag[0]\n"
                         "  int extracted = first\n"
                         "  string second = bag[1]\n"
                         "  print(extracted)\n"
                         "  print(second)\n"
                         "}");
         }},
        {"array element assignment accepts any supported value type", [] {
             expectValid("start {\n"
                         "  array bag = [1, \"two\"]\n"
                         "  bag[0] = \"now a string\"\n"
                         "  bag[1] = 42\n"
                         "  print(bag.length)\n"
                         "}");
         }},
        {"legacy 'int[]' array syntax is rejected", [] {
             expectDiagnostic("start {\n  int[] values = [1, 2]\n}",
                              "expected identifier (keywords are reserved)");
         }},
        {"legacy 'string[]' array syntax is rejected", [] {
             expectDiagnostic("start {\n  string[] values = [\"a\"]\n}",
                              "expected identifier (keywords are reserved)");
         }},
        {"legacy 'Class[]' array syntax is rejected", [] {
             expectDiagnostic(
                 "class Widget {\n  int id\n  Widget(int initial) { id = initial }\n}\n"
                 "start {\n  Widget[] values = [Widget(1)]\n}",
                 "expected expression");
         }},
        {"nested array literals are accepted", [] {
             expectValid("start {\n  array inner = [2, 3]\n"
                         "  array bag = [1, inner, [4, 5]]\n}");
         }},
        {"'any' has no members until extracted", [] {
             expectDiagnostic("start {\n  array bag = [1]\n  any first = bag[0]\n"
                              "  print(first.length)\n}",
                              "'any' has no members; assign it to a typed variable first to "
                              "extract its value");
         }},
        {"array and 'any' equality is rejected", [] {
             expectDiagnostic("start {\n  array bag = [1]\n  array other = [1]\n"
                              "  int same = bag == other\n}",
                              "equality is implemented only for int values");
         }},
        {"map type and literal keys are accepted", [] {
             expectValid("start {\n"
                         "  dict values = {\"answer\": 42, 'label': \"ok\"}\n"
                         "  map alias = values\n"
                         "  any result = alias[\"answer\"]\n"
                         "  alias[\"answer\"] = \"changed\"\n"
                         "  print(alias.length)\n"
                         "}");
         }},
        {"map indexing accepts string expressions", [] {
             expectValid("start {\n map values = {}\n string key = \"x\"\n"
                         " any value = values[key]\n}");
         }},
        {"map literal keys must be string literals", [] {
             expectDiagnostic("start { map values = {1: \"value\"} }",
                              "map keys must have type string");
         }},
        {"map length is read-only", [] {
             expectDiagnostic("start {\n map values = {}\n values.length = 1\n}",
                              "map length is read-only");
         }},
        {"map equality is rejected", [] {
             expectDiagnostic("start {\n map values = {}\n map other = {}\n"
                              " int same = values == other\n}",
                              "equality is implemented only for int values");
         }},
        {"'any' equality is rejected", [] {
             expectDiagnostic("start {\n any value = 1\n"
                              " int same = value == value\n}",
                              "equality is implemented only for int values");
         }},
        {"map slicing accepts integer insertion-order bounds", [] {
             expectValid("start {\n map values = {\"a\": 1, \"b\": 2}\n"
                         " map copy = values[0:1]\n"
                         " print(copy.length)\n}");
         }},
        {"map removal accepts one string key", [] {
             expectValid("start {\n map values = {\"a\": 1}\n"
                         " int removed = values.remove(\"a\")\n"
                         " print(removed)\n}");
         }},
        {"map removal rejects a non-string key", [] {
             expectDiagnostic("start {\n map values = {}\n"
                              " int removed = values.remove(1)\n}",
                              "map key must have type string");
         }},
        {"map removal rejects incorrect arity", [] {
             expectDiagnostic("start {\n map values = {}\n"
                              " int removed = values.remove()\n}",
                              "map 'remove' expects one string key");
         }},
        {"map slice bounds require integers", [] {
             expectDiagnostic("start {\n map values = {}\n"
                              " map copy = values[\"a\":\"z\"]\n}",
                              "map index and slice bounds must be int");
         }},
         {"map contains and collection iteration are accepted", [] {
              expectValid("start {\n"
                          "  map values = {\"one\": 1}\n"
                          "  string key = \"one\"\n"
                          "  int present = values.contains(key)\n"
                          "  for (name, value in values) { print(name) }\n"
                          "  array items = [1, \"two\"]\n"
                          "  for (item in items) { print(item) }\n"
                          "}");
         }},
         {"map iteration supports value-only and key/value bindings", [] {
              expectValid("start {\n"
                          "  map values = {\"one\": 1}\n"
                          "  for (value in values) { print(value) }\n"
                          "  for (key, value in values) { print(key) }\n"
                          "}");
         }},
         {"array iteration accepts one value variable", [] {
              expectDiagnostic("start {\n array values = []\n"
                               " for (key, value in values) { print(value) }\n}",
                               "array iteration accepts one value variable");
         }},
         {"map keys must be statically typed strings", [] {
              expectDiagnostic("start {\n map values = {}\n any key = \"x\"\n"
                               " any value = values[key]\n}",
                               "map keys must have type string");
         }},
         {"namespace keyword is case-insensitive and reserved", [] {
              simp::Lexer lexer("NaMeSpAcE Foo { class Thing {} }\nstart {}",
                                "namespace-keyword.simp");
              const auto tokens = lexer.tokenize();
              require(tokens.front().type == simp::TokenType::Namespace,
                      "namespace keyword was not recognized case-insensitively");
              expectDiagnostic("start {\n int Namespace = 1\n}",
                               "keywords are reserved");
         }},
         {"namespace declarations require single identifiers and reopen", [] {
              const auto program = parse(
                  "namespace Alpha { namespace Beta { class First {} } }\n"
                  "namespace Alpha { namespace Beta { class Second {} } }\n"
                  "start {}");
              require(program.classes.size() == 2 &&
                          program.classes[0].name == "Alpha.Beta.First" &&
                          program.classes[1].name == "Alpha.Beta.Second",
                      "reopened nested namespace class paths were not merged");
              expectDiagnostic("namespace Alpha.Beta { }\nstart {}",
                               "expected '{' after namespace name");
         }},
         {"out-of-line methods resolve within their namespace", [] {
              expectValid(
                  "namespace Remote {\n"
                  "  class Method { int value() }\n"
                  "  int Method.value() { return 42 }\n"
                  "}\n"
                  "start { print(Remote.Method().value()) }");
         }},
         {"unqualified class names resolve through enclosing namespaces", [] {
              const auto program = parse(
                  "namespace Outer {\n"
                  "  class Common {}\n"
                  "  namespace Inner {\n"
                  "    class Consumer {\n"
                  "      Common dependency\n"
                  "      Common create() { return Common() }\n"
                  "    }\n"
                  "  }\n"
                  "}\n"
                  "start {}");
              require(program.classes[1].fields.front().type == "Outer.Common" &&
                          program.classes[1].methods.front().returnType == "Outer.Common" &&
                          program.classes[1].methods.front().body.front()
                                  .expressions.front()->value == "Outer.Common",
                      "unqualified nested type did not resolve to its enclosing namespace");
         }},
         {"qualified construction lowers to a constructor AST node", [] {
              const auto program = parse(
                  "namespace Foo { class Bar { int method() { return 42 } } }\n"
                  "start { print(Foo.Bar().method()) }");
              std::ostringstream output;
              simp::dumpAst(program, output);
              require(output.str().find("ConstructorCall [Foo.Bar]") != std::string::npos,
                      "qualified constructor call was not resolved in the AST");
         }},
         {"namespace start declarations are rejected", [] {
              expectDiagnostic("namespace Hidden { start {} }",
                               "'start' cannot be declared inside a namespace");
         }},
         {"namespace statement bodies are rejected", [] {
              expectDiagnostic("namespace Hidden { print(1) }",
                               "namespace body may contain only namespace and class declarations");
         }},
         {"unresolved qualified class names are rejected", [] {
              expectDiagnostic(
                  "namespace Known { class Present {} }\n"
                  "start { Known.Missing value = Known.Missing() }",
                  "unknown qualified class 'Known.Missing'");
         }}
    };

    const std::vector<FunctionalCase> functionalCases{
        {"functional valid control flow", "positive/positive_control_flow.simp", ""},
        {"functional newline-only statements", "positive/positive_newline_statements.simp", ""},
        {"functional adjacent statements rejected", "negative/negative_adjacent_statements.simp",
         "expected newline after statement"},
        {"functional secondary-base construction and dispatch",
         "positive/positive_secondary_bases.simp", ""},
        {"functional secondary-base constructor initialization required",
         "negative/negative_secondary_base_constructor.simp",
         "derived constructor must initialize base 'Secondary'"},
        {"functional virtual-base construction and shared identity",
         "positive/positive_virtual_base_inheritance.simp", ""},
        {"functional parameterized virtual-base arguments in a diamond",
         "positive/positive_parameterized_virtual_base.simp", ""},
        {"functional parameterized virtual base rejected",
         "negative/negative_virtual_base_constructor_args.simp",
         "most-derived constructor must initialize virtual base 'Root'"},
        {"functional missing virtual-base initializer rejected",
         "negative/negative_virtual_base_missing_initializer.simp",
         "most-derived constructor must initialize virtual base 'Root'"},
        {"functional duplicate virtual-base initializer rejected",
         "negative/negative_virtual_base_duplicate_initializer.simp",
         "virtual base 'Root' is initialized more than once"},
        {"functional virtual-base initializer type checked",
         "negative/negative_virtual_base_initializer_type.simp",
         "virtual base constructor argument type does not match"},
        {"functional virtual-base initializer arity checked",
         "negative/negative_virtual_base_initializer_arity.simp",
         "virtual base constructor argument count does not match"},
        {"functional virtual-base initializer order checked",
         "negative/negative_virtual_base_initializer_order.simp",
         "virtual base initializers must precede direct base"},
        {"functional intermediate virtual-base initializer rejected",
         "negative/negative_virtual_base_initializer_in_intermediate.simp",
         "virtual base initializers are only allowed in most-derived classes"},
        {"functional transitive virtual-base inheritance",
         "positive/positive_transitive_virtual_bases.simp", ""},
        {"functional transitive virtual-base initializer order",
         "negative/negative_transitive_virtual_base_initializer_order.simp",
         "virtual base initializers must follow virtual-base construction order"},
        {"functional ambiguous virtual/non-virtual conversion rejected",
         "negative/negative_transitive_ambiguous_conversion.simp",
         "cannot initialize Ancestor variable with Diamond"},
        {"functional ambiguous virtual/non-virtual field rejected",
         "negative/negative_transitive_ambiguous_field.simp",
         "ambiguous inherited field 'value'"},
        {"functional ambiguous virtual/non-virtual method rejected",
         "negative/negative_transitive_ambiguous_method.simp",
         "ambiguous inherited method 'read'"},
        {"functional explicit virtual-base constructor call rejected",
         "negative/negative_virtual_base_explicit_super.simp",
         "virtual base constructors must use super.virtual"},
        {"functional exception binding is read-only",
         "negative/negative_exception_binding_assignment.simp",
         "exception binding 'message' is read-only"},
        {"functional missing start", "negative/negative_missing_start.simp",
         "exactly one top-level 'start' block"},
        {"functional duplicate start", "negative/negative_duplicate_start.simp",
         "more than one top-level 'start' block"},
        {"functional conditional else", "negative/negative_conditional_else.simp",
         "unconditional 'else' cannot have a condition"},
        {"functional reserved identifier", "negative/negative_keyword_identifier.simp",
         "keywords are reserved"},
        {"functional out-of-line native method example compiles and runs",
         "positive/positive_extern_functions.simp", ""},
        {"functional native method missing symbol fails at link time",
         "negative/negative_extern_missing_symbol.simp", ""},
    };
    for (const auto& functionalCase : functionalCases) {
        tests.emplace_back(functionalCase.description, [functionalCase] {
            runFunctional(functionalCase.fixture, functionalCase.expectedDiagnostic);
        });
    }

    std::size_t failures = 0;
    for (const auto& test : tests) {
        try {
            test.second();
            std::cout << "PASS " << test.first << '\n';
        } catch (const std::exception& error) {
            ++failures;
            std::cerr << "FAIL " << test.first << ": " << error.what() << '\n';
        }
    }
    std::cout << tests.size() - failures << "/" << tests.size() << " tests passed\n";
    return failures == 0 ? 0 : 1;
}
