/**
 * @file CodeGenerator.hpp
 * @brief Textual LLVM IR generation for integer control flow and byte strings.
 * @author Generated by GitHub Copilot
 */
#pragma once

#include "simp/Ast.hpp"

#include <iosfwd>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace simp {

class CodeGenerator {
public:
    explicit CodeGenerator(std::string targetTriple);
    std::string generate(const Program& program);

private:
    struct Binding {
        std::string type;
        std::string pointer;
        std::vector<std::size_t> fieldPath;
        bool field = false;
        bool readOnly = false;
    };
    struct Value {
        std::string type;
        std::string operand;
    };
    using Scope = std::unordered_map<std::string, Binding>;

    void emitClassTypesAndMetadata(const Program& program);
    void emitClassMethods(const Program& program);
    void emitMethod(const ClassDeclaration& owner, const MethodDeclaration& method,
                    const std::string& symbolOverride = {});
    void emitMain(const Program& program);
    void emitStatements(const std::vector<Statement>& statements);
    void emitStatement(const Statement& statement);
    void emitTry(const Statement& statement);
    Value emitExpression(const Expression& expression, const std::string& expectedType = {});
    Value emitIntegerExpression(const Expression& expression);
    void emitArrayElementStore(const std::string& valuePointer, Value value,
                               const SourceLocation& location);
    void emitMapElementStore(const std::string& mapPointer, Value key, Value value,
                             const SourceLocation& location);
    Value buildDynamicValue(Value value, const SourceLocation& location);
    Value extractTypedValue(Value value, const std::string& expectedType,
                            const SourceLocation& location);
    Value rootObjectValue(Value value, const SourceLocation& location);
    void registerRootSlot(const std::string& pointer, const std::string& type);
    std::string rootFrameInitialization() const;
    std::string rootFramePush() const;
    void emitRootFramePop();
    Binding findVariable(const std::string& name, const SourceLocation& location) const;
    const FieldDeclaration* findField(const ClassDeclaration& owner,
                                      const std::string& name,
                                      std::vector<std::size_t>& path) const;
    std::size_t flattenedFieldCount(const ClassDeclaration& owner) const;
    std::vector<std::pair<std::vector<std::string>, const ClassDeclaration*>>
    subobjects(const ClassDeclaration& owner) const;
    std::vector<std::string> virtualBaseNames(const ClassDeclaration& owner) const;
    std::size_t virtualBasePointerIndex(const ClassDeclaration& owner,
                                        const std::string& baseName) const;
    std::size_t virtualBaseStorageIndex(const ClassDeclaration& owner,
                                        const std::string& baseName) const;
    std::size_t fieldIndex(const ClassDeclaration& owner, std::size_t field) const;
    std::string emitFieldAddress(const std::string& pointer, const ClassDeclaration& owner,
                                 const std::vector<std::size_t>& path);
    std::string emitSubobjectAddress(const std::string& pointer,
                                     const ClassDeclaration& owner,
                                     const std::vector<std::string>& path);
    std::string subobjectAddressSequence(const std::string& pointer,
                                        const ClassDeclaration& owner,
                                        const std::vector<std::string>& path,
                                        const std::string& temporaryPrefix,
                                        std::string& address) const;
    std::string subobjectFieldOffset(const ClassDeclaration& owner,
                                     const std::vector<std::string>& path,
                                     std::size_t field, bool dynamicPointerSubfield = false) const;
    std::string viewMetadataSymbol(const ClassDeclaration& owner,
                                   const std::vector<std::string>& path) const;
    Value convertObjectValue(Value value, const std::string& expectedType,
                             const SourceLocation& location);
    std::string externMethodDeclaration(const ClassDeclaration& owner,
                                        const MethodDeclaration& method) const;
    std::string externReturnLlvmType(const std::string& type) const;
    bool resolveBaseQualifier(const Expression& receiver, const Expression*& root,
                              const ClassDeclaration*& view,
                              std::vector<std::string>& path) const;
    const MethodDeclaration* findMethod(const ClassDeclaration& owner,
                                        const std::string& name) const;
    std::vector<const MethodDeclaration*> methodSlots(const ClassDeclaration& owner) const;
    std::size_t methodSlot(const ClassDeclaration& owner, const std::string& name) const;
    std::string declaringClass(const MethodDeclaration& method) const;
    std::string emitAddress(const Binding& binding, const SourceLocation& location);
    std::string llvmType(const std::string& type) const;
    std::string methodSymbol(const std::string& className, const std::string& methodName) const;
    std::string newTemporary();
    std::string freshLabel(const std::string& prefix);
    std::string internString(const std::string& bytes);
    void emitStringBytes(const std::string& bytes);
    void emitPrint(const Statement& statement);
    void emitPrintDynamicValue(const Value& value);
    void emitNullCheck(const std::string& pointer, const SourceLocation& location);
    bool isArrayType(const std::string& type) const;
    bool isMapType(const std::string& type) const;
    bool isManagedReferenceType(const std::string& type) const;
    bool isDynamicValueType(const std::string& type) const;
    [[noreturn]] void unsupported(const SourceLocation& location, const std::string& feature) const;

    std::string targetTriple_;
    std::unordered_map<std::string, const ClassDeclaration*> classes_;
    std::unordered_map<std::string, const OutOfLineMethodDefinition*> methodDefinitions_;
    const ClassDeclaration* currentClass_ = nullptr;
    const ClassDeclaration* currentFieldClass_ = nullptr;
    const MethodDeclaration* currentMethod_ = nullptr;
    std::vector<Scope> scopes_;
    std::string instructions_;
    std::string entryAllocas_;
    std::string functionPrologue_;
    std::string stringGlobals_;
    std::string typeDefinitions_;
    std::string metadataGlobals_;
    std::string externDeclarations_;
    std::vector<std::string> rootSlots_;
    std::size_t nextTemporary_ = 0;
    std::size_t nextVariable_ = 0;
    std::size_t nextRoot_ = 0;
    std::size_t nextExceptionFrame_ = 0;
    std::size_t nextLabel_ = 0;
    std::size_t nextString_ = 0;
    bool blockTerminated_ = false;
};

} // namespace simp
