/**
 * @file Parser.hpp
 * @brief Recursive-descent parser for the documented Simple subset.
 * @author Generated by GitHub Copilot
 */
#pragma once

#include "simp/Ast.hpp"
#include "simp/Token.hpp"

#include <cstddef>
#include <iosfwd>
#include <vector>

namespace simp {

class Parser {
public:
    explicit Parser(std::vector<Token> tokens, std::ostream* traceOutput = nullptr);
    Program parseProgram();
    Program parseModule();

private:
    const Token& current() const;
    const Token& previous() const;
    bool check(TokenType type) const;
    bool match(TokenType type);
    void skipNewlines();
    bool startsOutOfLineDefinition() const;
    void consumeStatementTerminator();
    const Token& consume(TokenType type, const char* expectation);
    [[noreturn]] void error(const Token& token, const std::string& message) const;
    void validateFormatString(const Expression& format, std::size_t argumentCount,
                              const Token& location) const;
    void trace(const char* action) const;

    ClassDeclaration parseClass();
    void parseNamespace(Program& program);
    ImportDeclaration parseImport();
    std::string parseQualifiedIdentifier(const char* expectation);
    OutOfLineMethodDefinition parseOutOfLineMethodDefinition();
    MethodDeclaration parseMethod(const Token& typeOrName, const Token& methodName,
                                 bool constructor, const std::string& returnType = {});
    std::vector<Parameter> parseParameters();
    std::string parseType(bool allowVoid = false);
    std::vector<Statement> parseBlock();
    Statement parseStatement();
    Statement parseDeclaration();
    Statement parseIdentifierStatement();
    Statement parseReturn();
    Statement parseSuperConstructorCall();
    Statement parsePrint();
    Statement parseIf();
    Statement parseWhile();
    Statement parseForEach();
    Statement parseRaise();
    Statement parseTry();
    std::unique_ptr<Expression> parseExpression();
    std::unique_ptr<Expression> parseComparison();
    std::unique_ptr<Expression> parseAddition();
    std::unique_ptr<Expression> parseMultiplication();
    std::unique_ptr<Expression> parseUnary();
    std::unique_ptr<Expression> parsePrimary();
    std::unique_ptr<Expression> parsePostfix(std::unique_ptr<Expression> expression);

    std::vector<Token> tokens_;
    std::size_t current_ = 0;
    std::ostream* traceOutput_ = nullptr;
    std::vector<std::string> namespacePath_;
};

} // namespace simp
