/**
 * @file RuntimeThreads.h
 * @brief C ABI for the pthread-style Thread and Semaphore native bindings.
 * @author Generated by GitHub Copilot
 *
 * These functions are meant to be bound from Simple via the existing
 * out-of-line native-method mechanism (`from "<symbol>"`), not called
 * directly by hand-written C outside of tests. See "Threads" in
 * SIMPLE-LANGUAGE-NOTES.md for the full design writeup, and
 * tests/functional/positive/positive_threads.simp for the expected Simple
 * declarations:
 *
 *   class Thread {
 *       handle launch() from "simp_thread_start"
 *       void join(handle worker) from "simp_thread_join"
 *   }
 *
 *   class Semaphore {
 *       handle create(int initialCount) from "simp_semaphore_create"
 *       void wait(handle sem) from "simp_semaphore_wait"
 *       void signal(handle sem) from "simp_semaphore_signal"
 *       void release(handle sem) from "simp_semaphore_release"
 *   }
 *
 * ("start" is a reserved keyword in Simple, hence "launch".)
 *
 * A `Thread` subclass must declare a zero-parameter `void run()` method;
 * `launch()` looks it up by name in the receiver's own class metadata (the
 * same per-object method table the compiler already builds for virtual
 * dispatch) and runs it on a new OS thread. There is deliberately no
 * compile-time check binding "run" to any interface: getting the name or
 * signature wrong is a native-ABI-style programmer error (it aborts, the
 * same way every other native-method misuse in this runtime does).
 */
#pragma once

#include "simp/RuntimeGc.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Looks up a zero-argument `void run()` method on `receiver`'s class (by
 * name, via its metadata's method table) and starts it on a new OS thread.
 * Aborts if `receiver` has no such method. Returns an opaque handle usable
 * with simp_thread_join; the caller owns its lifetime, exactly like any
 * other 'handle' value (see the nullability/handle notes in
 * SIMPLE-LANGUAGE-NOTES.md) -- it must eventually be joined exactly once. */
void *simp_thread_start(void *receiver);

/* Blocks the calling thread until the thread started by `worker` (the
 * handle simp_thread_start returned) finishes, then frees the handle.
 * Aborts if `worker` is NULL or has already been joined. `receiver` is
 * unused (join does not need any Thread-instance state). */
void simp_thread_join(void *receiver, void *worker);

/* A plain counting semaphore. `initial_count` must be >= 0 (aborts
 * otherwise). Returns an opaque handle; `receiver` is unused. */
void *simp_semaphore_create(void *receiver, int64_t initial_count);
void simp_semaphore_wait(void *receiver, void *semaphore);
void simp_semaphore_signal(void *receiver, void *semaphore);
void simp_semaphore_release(void *receiver, void *semaphore);

/* Explicitly owned non-recursive mutexes and condition variables. A Condition
 * wait atomically releases/reacquires the associated Mutex, like pthreads. */
void *simp_mutex_create(void *receiver);
int32_t simp_mutex_lock(void *receiver, void *mutex);
int32_t simp_mutex_unlock(void *receiver, void *mutex);
int32_t simp_mutex_release(void *receiver, void *mutex);
void *simp_condition_create(void *receiver);
int32_t simp_condition_wait(void *receiver, void *condition, void *mutex);
int32_t simp_condition_signal(void *receiver, void *condition);
int32_t simp_condition_broadcast(void *receiver, void *condition);
int32_t simp_condition_release(void *receiver, void *condition);

#ifdef __cplusplus
}
#endif
