/**
 * @file RuntimeGc.h
 * @brief C ABI for the prototype's precise non-moving collector.
 * @author Generated by GitHub Copilot
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct SimpMethodMeta {
    const char *name;
    uint64_t name_length;
    void *code;
} SimpMethodMeta;

typedef struct SimpClassMeta {
    const char *name;
    uint64_t name_length;
    uint64_t field_count;
    const SimpMethodMeta *methods;
    uint64_t method_count;
    uint64_t object_size;
    uint64_t reference_field_count;
    const uint64_t *reference_field_offsets;
    void (*finalize)(void *object);
} SimpClassMeta;

typedef enum SimpArrayValueTag {
    SIMP_ARRAY_INTEGER = 1,
    SIMP_ARRAY_STRING = 2,
    SIMP_ARRAY_OBJECT = 3
} SimpArrayValueTag;

typedef struct SimpArrayValue {
    uint64_t tag;
    int64_t integer;
    void *pointer;
    uint64_t length;
} SimpArrayValue;

typedef struct SimpArray {
    const SimpClassMeta *metadata;
    uint64_t length;
    SimpArrayValue values[];
} SimpArray;

typedef struct SimpRootFrame {
    struct SimpRootFrame *previous;
    uint64_t count;
    /* Each element is the address of one pointer-typed object-reference slot. */
    void *const *slots;
} SimpRootFrame;

/* Push/pop are LIFO; return 1 on success and 0 for an invalid operation. */
int simp_gc_push(SimpRootFrame *frame, void *const *slots, uint64_t count);
int simp_gc_pop(SimpRootFrame *frame);
void simp_gc_push_or_abort(SimpRootFrame *frame, void *const *slots, uint64_t count);
void simp_gc_pop_or_abort(SimpRootFrame *frame);

/* Collect before allocating; the returned object's header and fields are zeroed. */
void *simp_gc_alloc(const SimpClassMeta *metadata);
void *simp_gc_alloc_array(uint64_t length);
void *simp_array_index(void *array, int32_t index, const char *file,
                       uint64_t file_length, uint64_t line, uint64_t column);
void *simp_array_slice(void *array, int32_t start, int32_t end, const char *file,
                       uint64_t file_length, uint64_t line, uint64_t column);
void *simp_gc_root(void *object);
void simp_gc_require_alive(void *object, const char *file, uint64_t file_length,
                           uint64_t line, uint64_t column);

/* Extraction guards for the 'any' dynamic value representation: raise on a tag
 * or exact-class mismatch instead of returning a value. */
void simp_value_require_tag(uint64_t actual, uint64_t expected, const char *file,
                            uint64_t file_length, uint64_t line, uint64_t column);
void simp_value_require_class(uint64_t actual_tag, void *pointer,
                              const SimpClassMeta *expected, const char *file,
                              uint64_t file_length, uint64_t line, uint64_t column);
void simp_gc_begin_construction(void *object);
void simp_gc_end_construction(void *object);
void simp_gc_begin_destroy(void *object, const char *file, uint64_t file_length,
                            uint64_t line, uint64_t column);
void simp_gc_end_destroy(void *object);
void simp_gc_collect(void);
size_t simp_gc_heap_count(void);

/* Exception frames are stack-allocated by generated code and remain live through finally. */
uint64_t simp_exception_frame_size(void);
void simp_exception_frame_init(void *frame);
void *simp_exception_frame_buffer(void *frame);
void simp_exception_push(void *frame);
void simp_exception_pop(void *frame);
void simp_exception_clear(void *frame);
const char *simp_exception_take_message(void *frame);
uint64_t simp_exception_message_length(void *frame);
void simp_exception_raise(const char *message, uint64_t length, const char *file,
                          uint64_t file_length, uint64_t line, uint64_t column);
void simp_exception_rethrow(void *frame);

#ifdef __cplusplus
}
#endif
