/**
 * @file RuntimeGc.h
 * @brief C ABI for the prototype's precise non-moving collector.
 * @author Generated by GitHub Copilot
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct SimpMethodMeta {
    const char *name;
    uint64_t name_length;
    void *code;
} SimpMethodMeta;

typedef struct SimpClassMeta {
    const char *name;
    uint64_t name_length;
    uint64_t field_count;
    const SimpMethodMeta *methods;
    uint64_t method_count;
    uint64_t object_size;
    uint64_t reference_field_count;
    const uint64_t *reference_field_offsets;
} SimpClassMeta;

typedef struct SimpRootFrame {
    struct SimpRootFrame *previous;
    uint64_t count;
    /* Each element is the address of one pointer-typed object-reference slot. */
    void *const *slots;
} SimpRootFrame;

/* Push/pop are LIFO; return 1 on success and 0 for an invalid operation. */
int simp_gc_push(SimpRootFrame *frame, void *const *slots, uint64_t count);
int simp_gc_pop(SimpRootFrame *frame);
void simp_gc_push_or_abort(SimpRootFrame *frame, void *const *slots, uint64_t count);
void simp_gc_pop_or_abort(SimpRootFrame *frame);

/* Collect before allocating; the returned object's header and fields are zeroed. */
void *simp_gc_alloc(const SimpClassMeta *metadata);
void simp_gc_collect(void);
size_t simp_gc_heap_count(void);

#ifdef __cplusplus
}
#endif
