/**
 * @file Token.hpp
 * @brief Token kinds and source-spanned token values.
 * @author Generated by GitHub Copilot
 */
#pragma once

#include "simp/SourceLocation.hpp"

#include <string>

namespace simp {

enum class TokenType {
    End,
    Identifier,
    Integer,
    UnsignedInteger,
    Float,
    String,
    Start,
    Int,
    Bool,
    FloatType,
    Unsigned,
    StrgType,
    ListType,
    DictType,
    BufferType,
    HandleType,
    AnyType,
    TypeType,
    Class,
    Namespace,
    Include,
    Inline,
    InlineBody,
    Import,
    As,
    Public,
    Protected,
    Private,
    Virtual,
    Super,
    Null,
    True,
    False,
    Return,
    Void,
    If,
    Else,
    While,
    Do,
    For,
    In,
    Is,
    Break,
    Continue,
    And,
    Or,
    Print,
    Raise,
    Try,
    Except,
    Finally,
    From,
    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    Colon,
    Newline,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    Bang,
    AndAnd,
    OrOr,
    Equal,
    EqualEqual,
    BangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual
};

struct Token {
    TokenType type = TokenType::End;
    std::string text;
    SourceLocation location;
    bool formattedString = false;
};

const char* tokenTypeName(TokenType type) noexcept;

} // namespace simp
