/**
 * @file Token.hpp
 * @brief Token kinds and source-spanned token values.
 * @author Generated by GitHub Copilot
 */
#pragma once

#include "simp/SourceLocation.hpp"

#include <string>

namespace simp {

enum class TokenType {
    End,
    Identifier,
    Integer,
    String,
    Start,
    Int,
    StringType,
    Class,
    Public,
    Protected,
    Private,
    Super,
    Null,
    Return,
    Void,
    If,
    Else,
    While,
    Print,
    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    Comma,
    Dot,
    Colon,
    Semicolon,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Bang,
    Equal,
    EqualEqual,
    BangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual
};

struct Token {
    TokenType type = TokenType::End;
    std::string text;
    SourceLocation location;
    bool formattedString = false;
};

const char* tokenTypeName(TokenType type) noexcept;

} // namespace simp
