
/* A lexical scanner generated by flex */

/* Target: C/C++ */
/* START of m4 controls */
/* M4_YY_TABLES_VERIFY = 0 */
/* M4_MODE_NO_DO_STDINIT */
/* M4_MODE_NO_YYTEXT_IS_ARRAY */
/* M4_MODE_NO_YYMORE_USED */
/* M4_MODE_NO_REAL_FULLSPD */
/* M4_MODE_NO_REAL_FULLTBL */
/* M4_MODE_NO_CPP_USE_READ */
/* M4_MODE_NO_VARIABLE_TRAILING_CONTEXT_RULES */
/* M4_MODE_FIND_ACTION_REJECT_REALLY_USED */
/* M4_MODE_NO_USES_REJECT */
/* M4_MODE_USEMECS */
/* M4_MODE_FIND_ACTION_COMPRESSED */
/* M4_MODE_NO_FULLSPD */
/* M4_MODE_NO_BOL_NEEDED */
/* M4_MODE_YYLINENO */
/* M4_MODE_USEECS */
/* M4_MODE_GENTABLES */
/* M4_MODE_INTERACTIVE */
/* M4_MODE_NO_FULLSPD_OR_FULLTBL */
/* M4_MODE_FIND_ACTION_REJECT_OR_INTERACTIVE */
/* M4_MODE_NO_YYWRAP */
/* M4_MODE_INTERACTIVE */
/* M4_MODE_C_ONLY */
/* M4_MODE_PREFIX = yy */
/* M4_MODE_NO_YYINPUT */
/* M4_YY_NO_YYUNPUT */
/* M4_MODE_NO_REWRITE */
/* END of m4 controls */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* Feature test macros. Flex uses functions that require a minimum set of
 * macros defined. As defining some macros may hide function declarations that
 * user code might use, be conservative and respect user's definitions as much
 * as possible. In glibc, feature test macros may not be all set up until one
 * of the libc header (that includes <features.h>) is included. This creates
 * a circular dependency when we check the macros. <assert.h> is the safest
 * header we can include and does not declare too many functions we don't need.
 */
#if !defined(__GNU_LIBRARY__) && defined(__STDC__)
#include <assert.h>
#endif
#if !(defined(_POSIX_C_SOURCE) || defined(_XOPEN_SOURCE) || \
    defined(_POSIX_SOURCE))
# define _POSIX_C_SOURCE 1 /* Required for fileno() */
# define _POSIX_SOURCE 1
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* begin standard C++ headers. */

/* flex integer type definitions */

#ifndef YYFLEX_INTTYPES_DEFINED
#define YYFLEX_INTTYPES_DEFINED

/* Prefer C99 integer types if available. */

# if defined(__cplusplus) && __cplusplus >= 201103L
#include <cstdint>
#  define YYFLEX_USE_STDINT
# endif
# if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* Include <inttypes.h> and not <stdint.h> because Solaris 2.6 has the former
 * and not the latter.
 */
#include <inttypes.h>
#  define YYFLEX_USE_STDINT
# else
#  if defined(_MSC_VER) && _MSC_VER >= 1600
/* Visual C++ 2010 does not define __STDC_VERSION__ and has <stdint.h> but not
 * <inttypes.h>.
 */
#include <stdint.h>
#   define YYFLEX_USE_STDINT
#  endif
# endif
# ifdef YYFLEX_USE_STDINT
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
# else
typedef unsigned char flex_uint8_t;
typedef short int flex_int16_t;
typedef unsigned short int flex_uint16_t;
#  ifdef __STDC__
typedef signed char flex_int8_t;
/* ISO C only requires at least 16 bits for int. */
#   ifdef __cplusplus
#include <climits>
#   else
#include <limits.h>
#   endif
#   if UINT_MAX >= 4294967295
#    define YYFLEX_INT32_DEFINED
typedef int flex_int32_t;
typedef unsigned int flex_uint32_t;
#   endif
#  else
typedef char flex_int8_t;
#  endif
#  ifndef YYFLEX_INT32_DEFINED
typedef long int flex_int32_t;
typedef unsigned long int flex_uint32_t;
#  endif
# endif
#endif /* YYFLEX_INTTYPES_DEFINED */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define yybegin(s) (yy_start) = 1 + 2 * (s)
/* Legacy interface */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define yystart() (((yy_start) - 1) / 2)
/* Legacy interfaces */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* The state buf must be large enough to hold one state per character in the main buffer,
 * plus the start state, plus the two end-of-buffer byte states.
 */
#define YY_STATE_BUF_EXTRA_SPACE 3
#define YY_STATE_BUF_SIZE   (YY_BUF_SIZE + YY_STATE_BUF_EXTRA_SPACE)

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *yybuffer;
/* Legacy interface */
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl ) { \
			if ( yytext[yyl] == '\n' ) { \
                        	--yylineno;\
			} \
		} \
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p) { \
			if ( *p == '\n' ) { \
                		--yylineno;\
			} \
		} \
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define yyunput(c) yyunput_r( c, (yytext_ptr)  )
/* Legacy interface */
#define unput(c) yyunput_r( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yyatbol;

	int yy_bs_lineno; /**< The line count. */
	int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static yybuffer * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define yy_current_buffer() ( (yy_buffer_stack)			\
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Legacy interface */
#define YY_CURRENT_BUFFER yy_current_buffer()
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( yybuffer new_buffer  );
yybuffer yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( yybuffer b  );
void yy_flush_buffer ( yybuffer b  );
void yypush_buffer_state ( yybuffer new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( yybuffer b, FILE *file  );
#define yy_flush_current_buffer() yy_flush_buffer( yy_current_buffer() )
#define YY_FLUSH_BUFFER yy_flush_current_buffer()

yybuffer yy_scan_buffer ( char *base, yy_size_t size  );
yybuffer yy_scan_string ( const char *yy_str  );
yybuffer yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) { \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
			yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
}
#define yysetbol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}
#define yyatbol() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
/* Legacy interface */
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
#define yy_set_bol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)

#define YY_SKIP_YYWRAP

typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

/* Watch out: yytext_ptr is a variable when yytext is an array,
 * but it's a macro when yytext is a pointer.
 */

extern char *yytext;

#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */
/* START of m4 controls */
/* M4_MODE_NO_NULTRANS */
/* M4_MODE_NO_NULTRANS_FULLTBL */
/* M4_MODE_NO_NULTRANS_FULLSPD */
/* END of m4 controls */

/* START of Flex-generated definitions */
#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
#define YY_JAMBASE 319
#define YY_JAMSTATE 230
#define YY_NUL_EC 1
#define YY_OFFSET_TYPE flex_int16_t
/* END of Flex-generated definitions */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yypanic ( const char* msg  );

struct yy_trans_info
	{
	/* We require that yy_verify and yy_nxt must be of the same size int. */

	/* We generate a bogus 'struct yy_trans_info' data type
	 * so we can guarantee that it is always declared in the skel.
	 * This is so we can compile "sizeof(struct yy_trans_info)"
	 * in any scanner.
	 */
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;

	};

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	 \
	yyleng = (int) (yy_cp - yy_bp); \
	 \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
 \
	(yy_c_buf_p) = yy_cp;

extern int yyflexdebug;
int yyflexdebug = 0;
/* Legacy interface */
#ifndef yy_flex_debug
#define yy_flex_debug yyflexdebug
#endif

/* %% [2.0] data tables for the DFA are inserted here */

/* footprint: 23850 bytes */

/* m4 controls begin */
/* M4_MODE_HAS_BACKING_UP */
/* M4_MODE_NEED_YY_CP */
/* m4 controls end */

/* Table of booleans, true if rule could match eol. */
static const flex_int16_t yy_rule_can_match_eol[91] = { 0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, };

static const flex_int16_t yy_accept[231] = { 0,
         0,    0,   85,   85,   81,   81,   91,   88,    2,    1,
        44,   65,   49,   88,   83,   51,   52,   47,   45,   60,
        46,   59,   48,   62,   62,   88,   53,   50,   54,   61,
        55,   56,   61,   61,   61,   61,   61,   61,   61,   61,
        61,   61,   61,   61,   61,   61,   61,   61,   61,   57,
        88,   58,   85,   87,   84,   90,   81,   82,   66,   90,
        36,   43,   38,   41,   39,   40,   63,   42,    0,   62,
         0,    0,    0,   89,   33,   35,   34,   61,   61,   61,
        61,   61,   61,   61,    7,   61,   61,   61,   61,    9,
        61,   61,   61,   61,   61,   37,   61,   61,   61,   61,

        61,   61,   61,   61,   61,   61,   37,   85,   86,   81,
        78,   75,   76,   78,   77,   78,   74,   71,   69,   72,
        67,   68,   70,   73,    0,   63,   64,   38,   61,   61,
        61,   61,   61,   61,   61,   61,   61,   61,   61,   32,
        61,   61,   44,   61,   61,   61,   61,   61,   61,   24,
        61,   61,   61,   61,   61,   79,   80,   30,   61,   61,
        61,   61,   21,    8,   61,   15,   61,   61,   61,   61,
        20,   61,   28,   61,   61,   61,   29,   61,   61,   61,
        12,   18,   27,   61,   61,   61,   79,   80,   61,    3,
        23,    5,   61,   61,   13,   31,   61,   61,   61,   61,

        17,   26,   61,   61,   61,   16,   61,   11,   14,   80,
        61,   61,   25,    6,   61,   61,   61,   10,   22,   61,
        30,   61,   32,   61,   28,   61,    4,   61,   19,    0
};

/* Character equivalence-class mapping */
static const YY_CHAR yy_ec[256] = { 0,
         1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
         1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
        10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
        18,   18,   18,   18,   18,   19,   19,    1,   20,   21,
        22,   23,   24,    1,   25,   25,   25,   25,   26,   25,
        27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
        27,   27,   27,   27,   27,   27,   27,   28,   27,   27,
        29,   30,   31,    1,   27,    1,   32,   33,   34,   35,

        36,   37,   38,   39,   40,   27,   41,   42,   43,   44,
        45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
        54,   27,   55,   56,   57,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1
};

/* Character meta-equivalence-class mappings */
static const YY_CHAR yy_meta[58] = { 0,
         1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
         1,    1,    1,    1,    1,    1,    5,    5,    5,    1,
         1,    1,    1,    1,    5,    5,    6,    6,    1,    7,
         1,    5,    5,    5,    5,    5,    5,    6,    6,    6,
         6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
         6,    6,    6,    6,    1,    1,    1
};

static const flex_int16_t yy_base[243] = { 0,
         0,    0,   55,   56,   57,   62,  318,  319,  319,  319,
       295,  319,  294,  308,  319,  319,  319,  292,  291,  319,
       290,   51,  289,   62,   57,  307,  287,  286,  285,    0,
       319,  319,  262,   26,   49,   21,   36,   63,   59,  265,
        52,  257,  256,   68,  253,   52,   67,  262,  260,  319,
       243,  319,    0,  319,  319,    0,    0,  319,  319,  111,
       319,  319,  319,  319,  319,  319,   91,  319,   95,  106,
       119,    0,  295,  319,  319,  319,  319,    0,  262,  251,
       259,  262,  249,  258,    0,  243,   86,  248,  244,    0,
       242,  238,  238,  242,  235,    0,  243,  242,  232,  233,

       102,  233,  234,  229,  236,  239,  319,    0,  319,    0,
       319,  319,  319,  128,  319,    0,  319,  319,  319,  319,
       319,  319,  319,  319,  132,  148,    0,    0,  232,  241,
       224,  105,  222,  234,  233,  219,  219,  234,  220,  228,
       214,  226,  222,  216,  211,  208,  119,  223,  220,    0,
       219,  205,  213,  210,  209,  153,    0,  214,  208,  200,
       198,  206,    0,    0,  199,    0,  208,  194,  195,  203,
         0,  192,  199,  189,  201,  189,    0,  191,  200,  197,
         0,    0,    0,  194,  195,  195,  319,    0,  197,    0,
         0,    0,  184,  178,    0,    0,  177,  189,  178,  179,

         0,    0,  178,  183,  166,    0,  166,    0,    0,  319,
       165,  152,    0,    0,  151,  164,  130,    0,    0,  127,
         0,  125,    0,  109,    0,  105,    0,   94,    0,  319,
       171,  178,  185,  188,  194,  200,  207,  213,  117,  113,
        96,   77
};

static const flex_int16_t yy_def[243] = { 0,
       230,    1,  231,  231,  232,  232,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  233,  230,  230,  230,  234,
       230,  230,  234,  234,  234,  234,  234,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  230,
       230,  230,  235,  230,  230,  236,  237,  230,  230,  238,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  239,  233,  230,  230,  230,  230,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  234,

       234,  234,  234,  234,  234,  234,  230,  235,  230,  237,
       230,  230,  230,  230,  230,  240,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  239,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
       234,  234,  234,  234,  234,  230,  241,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  230,  242,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  234,

       234,  234,  234,  234,  234,  234,  234,  234,  234,  230,
       234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
       234,  234,  234,  234,  234,  234,  234,  234,  234,    0,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230
};

static const flex_int16_t yy_nxt[377] = { 0,
         8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
        18,   19,   20,   21,   22,   23,   24,   25,   25,   26,
        27,   28,   29,    8,   30,   30,   30,   30,   31,    8,
        32,   33,   34,   35,   36,   37,   38,   30,   30,   39,
        30,   40,   30,   41,   42,   43,   44,   45,   46,   47,
        30,   48,   30,   49,   50,   51,   52,   54,   54,   58,
        84,   59,   55,   55,   58,   85,   59,   67,   67,   67,
        80,   69,   81,   70,   70,   70,   69,   86,   70,   70,
        70,  210,   71,   94,   56,   56,   60,   71,   87,   72,
        82,   60,   71,   83,   88,   90,   95,   71,  101,   98,

       188,   91,   92,   99,   89,  102,  103,   67,   67,   67,
       104,   67,   67,   67,   72,  112,   71,  157,  113,  135,
        69,  127,   70,   70,   70,  136,   71,  114,  114,  229,
       125,   71,  125,  148,  115,  126,  126,  126,  116,  183,
       117,   71,  228,  118,  156,  156,  119,  120,  126,  126,
       126,  149,  161,  162,  121,  150,  177,  122,  178,  123,
       227,  124,  226,  116,  126,  126,  126,  225,  179,  187,
       187,   53,   53,   53,   53,   53,   53,   53,   57,   57,
        57,   57,   57,   57,   57,   73,   73,   73,   73,   73,
        73,   73,   78,   78,  108,  224,  108,  223,  108,  108,

       109,  222,  109,  109,  109,  109,  109,  110,  221,  220,
       110,  110,  110,  111,  219,  111,  111,  111,  111,  111,
       177,  218,  217,  216,  215,  214,  213,  212,  211,  209,
       208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
       198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
       186,  185,  184,  183,  182,  181,  180,  176,  175,  174,
       173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
       163,  160,  159,  158,  155,  154,  153,  152,  151,  147,
       146,  145,  144,  143,  142,  141,  140,  139,  138,  137,
       134,  133,  132,  131,  130,  129,  128,   74,  107,  106,

       105,  100,   97,   96,   93,   79,   77,   76,   75,   74,
        68,   66,   65,   64,   63,   62,   61,  230,    7,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230
};

static const flex_int16_t yy_chk[377] = { 0,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
         1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        36,    5,    3,    4,    6,   36,    6,   22,   22,   22,
        34,   25,   34,   25,   25,   25,   24,   37,   24,   24,
        24,  242,   25,   41,    3,    4,    5,   24,   37,   24,
        35,    6,   25,   35,   38,   39,   41,   24,   46,   44,

       241,   39,   39,   44,   38,   46,   47,   67,   67,   67,
        47,   69,   69,   69,   24,   60,   67,  240,   60,   87,
        70,  239,   70,   70,   70,   87,   67,   60,   60,  228,
        71,   70,   71,  101,   60,   71,   71,   71,   60,  226,
        60,   70,  224,   60,  114,  114,   60,   60,  125,  125,
       125,  101,  132,  132,   60,  101,  147,   60,  147,   60,
       222,   60,  220,   60,  126,  126,  126,  217,  147,  156,
       156,  231,  231,  231,  231,  231,  231,  231,  232,  232,
       232,  232,  232,  232,  232,  233,  233,  233,  233,  233,
       233,  233,  234,  234,  235,  216,  235,  215,  235,  235,

       236,  212,  236,  236,  236,  236,  236,  237,  211,  207,
       237,  237,  237,  238,  205,  238,  238,  238,  238,  238,
       204,  203,  200,  199,  198,  197,  194,  193,  189,  186,
       185,  184,  180,  179,  178,  176,  175,  174,  173,  172,
       170,  169,  168,  167,  165,  162,  161,  160,  159,  158,
       155,  154,  153,  152,  151,  149,  148,  146,  145,  144,
       143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
       133,  131,  130,  129,  106,  105,  104,  103,  102,  100,
        99,   98,   97,   95,   94,   93,   92,   91,   89,   88,
        86,   84,   83,   82,   81,   80,   79,   73,   51,   49,

        48,   45,   43,   42,   40,   33,   29,   28,   27,   26,
        23,   21,   19,   18,   14,   13,   11,    7,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
       230,  230,  230,  230,  230,  230
};

/* Definitions for backing up.  We don't need them if yyreject()
 * is being used because then we use an alternative backing-up
 * technique instead.
 */
static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of yyreject() which flex missed.
 */
#define yyreject() reject_used_but_not_detected
#define REJECT reject_used_but_not_detected

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET

char *yytext;

/* %% [3.0] static declarations conditional on mode switches go here */
#line 1 "scanner.l"
#line 2 "scanner.l"
#include "parser.h"

#include <stdio.h>

void yyerror(const char* s);

typedef struct _file_stack_ {
    const char* fname;
    int line;
    int col;
    FILE* fptr;
    YY_BUFFER_STATE buffer;
    struct _file_stack_* next;
} FileStack;

#define MAX_INCL 15
FileStack* fstack = NULL;
int incl_depth = 0;

int bidx = 0;
char buffer[1024 * 64];
const char* file_name;

static void __append_char(char ch) {
    // TODO: bounds checking
    buffer[bidx] = ch;
    bidx++;
}

static void __append_str(const char* str) {
    // TODO: bounds checking
    strcpy(&buffer[bidx], str);
    bidx += strlen(str);
}

int yycolumn = 1;

/* This is executed before every action.
#define YY_USER_ACTION                                                   \
  fstack->line = prev_yylineno; fstack->col = yycolumn;                  \
  if (yylineno == prev_yylineno) yycolumn += yyleng;                     \
  else {                                                                 \
    for (yycolumn = 1; yytext[yyleng - yycolumn] != '\n'; ++yycolumn) {} \
    prev_yylineno = yylineno;                                            \
  }
 */
#define YY_USER_ACTION                                                   \
  fstack->col = yycolumn;                  \
  if (yylineno == prev_yylineno) yycolumn += yyleng;                     \
  else {                                                                 \
    for (yycolumn = 1; yytext[yyleng - yycolumn] != '\n'; ++yycolumn) {} \
    prev_yylineno = yylineno;                                            \
  }


/* state definitions */



#define INITIAL 0
#define SQUOTES 1
#define DQUOTES 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */

#include <unistd.h>

#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_YYUNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#define YY_NO_YYINPUT 1

#ifndef YY_NO_YYINPUT

static int yyinput ( void );
#ifndef __cplusplus
#define input yyinput
#endif

#endif

/*
 * Amount of stuff to slurp up with each read.
 * We assume the stdio library has already
 * chosen a fit size foe whatever platform
 * we're running on.
 */
#define YY_READ_BUF_SIZE BUFSIZ

/* Size of default input buffer. We want to be able to fit two
 * OS-level reads, but efficiency gains as the buffer size
 * increases fall off after that
 */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE	(2 * YY_READ_BUF_SIZE)
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef yyecho

/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define yyecho() do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)

#endif
/* Legacy interface */
#define ECHO yyecho()

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yypanic (const char* msg ) {
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Report a fatal error. Legacy interface. */
#ifndef YY_FATAL_ERROR

#define YY_FATAL_ERROR(msg) yypanic( msg )

#endif

/* Legacy interface */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) do {result = yyread(buf, max_size );} while (0)

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */

static int yyread(char *buf, size_t max_size ) {

	int result;
	
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) {
		int c = '*';
		int n;
		for ( n = 0; n < max_size &&
			      (c = getc( yyin )) != EOF && c != '\n'; ++n ) {
			buf[n] = (char) c;
		}
		if ( c == '\n' ) {
			buf[n++] = (char) c;
		}
		if ( c == EOF && ferror( yyin ) ) {
			YY_FATAL_ERROR( "input in flex scanner failed" );
		}
		result = n;
	} else {
		errno=0;
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) {
			if( errno != EINTR) {
				YY_FATAL_ERROR( "input in flex scanner failed" );
				break;
			}
			errno=0;
			clearerr(yyin);
		}
	}

	 return result;
}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)

#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#define YY_RULE_SETUP \
		YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL {
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) ) {
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) ) {
			(yy_start) = 1;	/* first start state */
		}
		if ( ! yyin ) {

			yyin = stdin;

		}
		if ( ! yyout ) {

			yyout = stdout;

		}
		if ( yy_current_buffer() == NULL ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
	}

	/* open scope of user declarationns */
	{
/* %% [4.0] user's declarations go here */
#line 65 "scanner.l"


#line 68 "scanner.l"
   /* Any indented text before the first rule goes at the top of the lexer.  */
   // int start_line, start_column;
   int prev_yylineno = yylineno;



		while ( /*CONSTCOND*/1 ) {		/* loops until end-of-file is reached */

			yy_cp = (yy_c_buf_p);

			/* Support of yytext. */
			*yy_cp = (yy_hold_char);

			/* yy_bp points to the position in yy_ch_buf of the start of
			 * the current run.
			 */
			yy_bp = yy_cp;

	/* Generate the code to find the start state. */

			yy_current_state = (yy_start);

			/* Set up for storing up states. */
			
	yy_match:
			/* Generate the code to find the next match. */

			do {
				
	int yy_c = *(yy_ec+YY_SC_TO_UI(*yy_cp));
	/* Save the backing-up info \before/ computing the next state
	 * because we always compute one more state than needed - we
	 * always proceed until we reach a jam state
	 */
	
		/* Generate code to keep backing-up information. */

		if ( yy_accept[yy_current_state] ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
		yy_current_state = (int) yy_def[yy_current_state];

		/* We've arranged it so that templates are never chained
		 * to one another.  This means we can afford to make a
		 * very simple test to see if we need to convert to
		 * yy_c's meta-equivalence class without worrying
		 * about erroneously looking up the meta-equivalence
		 * class twice
		 */

		/* lastdfa + 2 == YY_JAMSTATE + 1 is the beginning of the templates */
		if (yy_current_state >= YY_JAMSTATE + 1) {
			yy_c = yy_meta[yy_c];
		}

	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];

				++yy_cp;

			}
			while ( yy_base[yy_current_state] != YY_JAMBASE );
			
	yy_find_action:
			/* code to find the action number goes here */
			
		yy_act = yy_accept[yy_current_state];
			if ( yy_act == 0 ) { /* have to back up */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				yy_act = yy_accept[yy_current_state];
			}

			YY_DO_BEFORE_ACTION;

			if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] ) {
				int yyl;
				for ( yyl = 0; yyl < yyleng; ++yyl ) {
					if ( yytext[yyl] == '\n' ) {
						
    yylineno++;
;

					}
				}
			}

		do_action:	/* This label is used only to access EOF actions. */

			switch ( yy_act ) { /* beginning of action switch */

			case 0: /* must back up */
				/* undo the effects of YY_DO_BEFORE_ACTION */
				*yy_cp = (yy_hold_char);

				/* Backing-up info for compressed tables is taken \after/ */
				/* yy_cp has been incremented for the next state. */
				yy_cp = (yy_last_accepting_cpos);
				
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;

/* %% [5.0] user actions get inserted here */
	case 1:
/* rule 1 can match eol */
YY_RULE_SETUP

#line 72 "scanner.l"
{ fstack->line++; fstack->col = 1; }
	/*LINTED*/break;
	case 2:
YY_RULE_SETUP

#line 73 "scanner.l"
{}
	/*LINTED*/break;
	case 3:
YY_RULE_SETUP

#line 75 "scanner.l"
{ return BREAK; }
	/*LINTED*/break;
	case 4:
YY_RULE_SETUP

#line 76 "scanner.l"
{ return CONTINUE; }
	/*LINTED*/break;
	case 5:
YY_RULE_SETUP

#line 77 "scanner.l"
{ return CONST; }
	/*LINTED*/break;
	case 6:
YY_RULE_SETUP

#line 78 "scanner.l"
{ return IMPORT; }
	/*LINTED*/break;
	case 7:
YY_RULE_SETUP

#line 79 "scanner.l"
{ return DO; }
	/*LINTED*/break;
	case 8:
YY_RULE_SETUP

#line 80 "scanner.l"
{ return ELSE; }
	/*LINTED*/break;
	case 9:
YY_RULE_SETUP

#line 81 "scanner.l"
{ return IF; }
	/*LINTED*/break;
	case 10:
YY_RULE_SETUP

#line 82 "scanner.l"
{ return RETURN; }
	/*LINTED*/break;
	case 11:
YY_RULE_SETUP

#line 83 "scanner.l"
{ return WHILE; }
	/*LINTED*/break;
	case 12:
YY_RULE_SETUP

#line 84 "scanner.l"
{ return TRUE; }
	/*LINTED*/break;
	case 13:
YY_RULE_SETUP

#line 85 "scanner.l"
{ return FALSE; }
	/*LINTED*/break;
	case 14:
YY_RULE_SETUP

#line 86 "scanner.l"
{ return YIELD; }
	/*LINTED*/break;
	case 15:
YY_RULE_SETUP

#line 87 "scanner.l"
{ return EXIT; }
	/*LINTED*/break;
	case 16:
YY_RULE_SETUP

#line 88 "scanner.l"
{ return TRACE; }
	/*LINTED*/break;
	case 17:
YY_RULE_SETUP

#line 89 "scanner.l"
{ return PRINT; }
	/*LINTED*/break;
	case 18:
YY_RULE_SETUP

#line 90 "scanner.l"
{ return TYPE; }
	/*LINTED*/break;
	case 19:
YY_RULE_SETUP

#line 91 "scanner.l"
{ return NAMESPACE; }
	/*LINTED*/break;
	case 20:
YY_RULE_SETUP

#line 92 "scanner.l"
{ return LIST; }
	/*LINTED*/break;
	case 21:
YY_RULE_SETUP

#line 93 "scanner.l"
{ return DICT; }
	/*LINTED*/break;
	case 22:
YY_RULE_SETUP

#line 94 "scanner.l"
{ return STRUCT; }
	/*LINTED*/break;
	case 23:
YY_RULE_SETUP

#line 95 "scanner.l"
{ return CLASS; }
	/*LINTED*/break;
	case 24:
YY_RULE_SETUP

#line 96 "scanner.l"
{ return TRY; }
	/*LINTED*/break;
	case 25:
YY_RULE_SETUP

#line 97 "scanner.l"
{ return EXCEPT; }
	/*LINTED*/break;
	case 26:
YY_RULE_SETUP

#line 98 "scanner.l"
{ return RAISE; }
	/*LINTED*/break;
	case 27:
YY_RULE_SETUP

#line 100 "scanner.l"
{ yylval.type = UNSIGNED; return UNSIGNED; }
	/*LINTED*/break;
	case 28:
YY_RULE_SETUP

#line 101 "scanner.l"
{ yylval.type = NOTHING; return NOTHING; }
	/*LINTED*/break;
	case 29:
YY_RULE_SETUP

#line 102 "scanner.l"
{ yylval.type = STRING; return STRING; }
	/*LINTED*/break;
	case 30:
YY_RULE_SETUP

#line 103 "scanner.l"
{ yylval.type = BOOLEAN; return BOOLEAN; }
	/*LINTED*/break;
	case 31:
YY_RULE_SETUP

#line 104 "scanner.l"
{ yylval.type = FLOAT; return FLOAT; }
	/*LINTED*/break;
	case 32:
YY_RULE_SETUP

#line 105 "scanner.l"
{ yylval.type = INTEGER; return INTEGER; }
	/*LINTED*/break;
	case 33:
YY_RULE_SETUP

#line 107 "scanner.l"
{ return LORE; }
	/*LINTED*/break;
	case 34:
YY_RULE_SETUP

#line 108 "scanner.l"
{ return GORE; }
	/*LINTED*/break;
	case 35:
YY_RULE_SETUP

#line 109 "scanner.l"
{ return EQU; }
	/*LINTED*/break;
	case 36:
YY_RULE_SETUP

#line 110 "scanner.l"
{ return NEQU; }
	/*LINTED*/break;
	case 37:
YY_RULE_SETUP

#line 111 "scanner.l"
{ return OR; }
	/*LINTED*/break;
	case 38:
YY_RULE_SETUP

#line 112 "scanner.l"
{ return AND; }
	/*LINTED*/break;
	case 39:
YY_RULE_SETUP

#line 113 "scanner.l"
{ return ADD_ASSIGN; }
	/*LINTED*/break;
	case 40:
YY_RULE_SETUP

#line 114 "scanner.l"
{ return SUB_ASSIGN; }
	/*LINTED*/break;
	case 41:
YY_RULE_SETUP

#line 115 "scanner.l"
{ return MUL_ASSIGN; }
	/*LINTED*/break;
	case 42:
YY_RULE_SETUP

#line 116 "scanner.l"
{ return DIV_ASSIGN; }
	/*LINTED*/break;
	case 43:
YY_RULE_SETUP

#line 117 "scanner.l"
{ return MOD_ASSIGN; }
	/*LINTED*/break;
	case 44:
YY_RULE_SETUP

#line 118 "scanner.l"
{ return NOT; }
	/*LINTED*/break;
	case 45:
YY_RULE_SETUP

#line 120 "scanner.l"
{ return '+'; }
	/*LINTED*/break;
	case 46:
YY_RULE_SETUP

#line 121 "scanner.l"
{ return '-'; }
	/*LINTED*/break;
	case 47:
YY_RULE_SETUP

#line 122 "scanner.l"
{ return '*'; }
	/*LINTED*/break;
	case 48:
YY_RULE_SETUP

#line 123 "scanner.l"
{ return '/'; }
	/*LINTED*/break;
	case 49:
YY_RULE_SETUP

#line 124 "scanner.l"
{ return '%'; }
	/*LINTED*/break;
	case 50:
YY_RULE_SETUP

#line 125 "scanner.l"
{ return '='; }
	/*LINTED*/break;
	case 51:
YY_RULE_SETUP

#line 126 "scanner.l"
{ return '('; }
	/*LINTED*/break;
	case 52:
YY_RULE_SETUP

#line 127 "scanner.l"
{ return ')'; }
	/*LINTED*/break;
	case 53:
YY_RULE_SETUP

#line 128 "scanner.l"
{ return '<'; }
	/*LINTED*/break;
	case 54:
YY_RULE_SETUP

#line 129 "scanner.l"
{ return '>'; }
	/*LINTED*/break;
	case 55:
YY_RULE_SETUP

#line 130 "scanner.l"
{ return '['; }
	/*LINTED*/break;
	case 56:
YY_RULE_SETUP

#line 131 "scanner.l"
{ return ']'; }
	/*LINTED*/break;
	case 57:
YY_RULE_SETUP

#line 132 "scanner.l"
{ return '{'; }
	/*LINTED*/break;
	case 58:
YY_RULE_SETUP

#line 133 "scanner.l"
{ return '}'; }
	/*LINTED*/break;
	case 59:
YY_RULE_SETUP

#line 134 "scanner.l"
{ return '.'; }
	/*LINTED*/break;
	case 60:
YY_RULE_SETUP

#line 135 "scanner.l"
{ return ','; }
	/*LINTED*/break;
	case 61:
YY_RULE_SETUP

#line 137 "scanner.l"
{
        yylval.symbol = (char*)strdup(yytext);
        return SYMBOL;
    }
	/*LINTED*/break;
	case 62:
YY_RULE_SETUP

#line 142 "scanner.l"
{
        yylval.inum = (double)strtol(yytext, NULL, 10);
        return INUM;
    }
	/*LINTED*/break;
/* recognize a float */
	case 63:
YY_RULE_SETUP

#line 148 "scanner.l"
{
        yylval.fnum = strtod(yytext, NULL);
        return FNUM;
    }
	/*LINTED*/break;
	case 64:
YY_RULE_SETUP

#line 153 "scanner.l"
{
        yylval.unum = (double)strtol(yytext, NULL, 16);
        return UNUM;
    }
	/*LINTED*/break;
/* double quoted strings have escapes managed */
	case 65:
YY_RULE_SETUP

#line 159 "scanner.l"
{
        bidx = 0;
        memset(buffer, 0, sizeof(buffer));
        BEGIN(DQUOTES);
    }
	/*LINTED*/break;
	case 66:
YY_RULE_SETUP

#line 165 "scanner.l"
{
        yylval.str = (char*)strdup(buffer);
        BEGIN(INITIAL);
        return STRG;
    }
	/*LINTED*/break;
/* the short rule matches before the long one does */
	case 67:
YY_RULE_SETUP

#line 172 "scanner.l"
{ __append_char('\n'); }
	/*LINTED*/break;
	case 68:
YY_RULE_SETUP

#line 173 "scanner.l"
{ __append_char('\r'); }
	/*LINTED*/break;
	case 69:
YY_RULE_SETUP

#line 174 "scanner.l"
{ __append_char('\x1b'); }
	/*LINTED*/break;
	case 70:
YY_RULE_SETUP

#line 175 "scanner.l"
{ __append_char('\t'); }
	/*LINTED*/break;
	case 71:
YY_RULE_SETUP

#line 176 "scanner.l"
{ __append_char('\b'); }
	/*LINTED*/break;
	case 72:
YY_RULE_SETUP

#line 177 "scanner.l"
{ __append_char('\f'); }
	/*LINTED*/break;
	case 73:
YY_RULE_SETUP

#line 178 "scanner.l"
{ __append_char('\v'); }
	/*LINTED*/break;
	case 74:
YY_RULE_SETUP

#line 179 "scanner.l"
{ __append_char('\\'); }
	/*LINTED*/break;
	case 75:
YY_RULE_SETUP

#line 180 "scanner.l"
{ __append_char('\"'); }
	/*LINTED*/break;
	case 76:
YY_RULE_SETUP

#line 181 "scanner.l"
{ __append_char('\''); }
	/*LINTED*/break;
	case 77:
YY_RULE_SETUP

#line 182 "scanner.l"
{ __append_char('\?'); }
	/*LINTED*/break;
	case 78:
YY_RULE_SETUP

#line 183 "scanner.l"
{ __append_char(yytext[1]); }
	/*LINTED*/break;
	case 79:
YY_RULE_SETUP

#line 184 "scanner.l"
{ __append_char((char)strtol(yytext + 1, 0, 8)); }
	/*LINTED*/break;
	case 80:
YY_RULE_SETUP

#line 185 "scanner.l"
{ __append_char((char)strtol(yytext + 2, 0, 16)); }
	/*LINTED*/break;
	case 81:
YY_RULE_SETUP

#line 186 "scanner.l"
{ __append_str(yytext); }
	/*LINTED*/break;
	case 82:
/* rule 82 can match eol */
YY_RULE_SETUP

#line 187 "scanner.l"
{ fstack->line++; fstack->col = 1; } // yylineno++; } /* track line numbers, but strip new line */
	/*LINTED*/break;
/* single quoted strings are absolute literals */
	case 83:
YY_RULE_SETUP

#line 190 "scanner.l"
{
        bidx = 0;
        memset(buffer, 0, sizeof(buffer));
        BEGIN(SQUOTES);
    }
	/*LINTED*/break;
	case 84:
YY_RULE_SETUP

#line 196 "scanner.l"
{
        yylval.str = (char*)strdup(buffer);
        BEGIN(INITIAL);
        return STRG;
    }
	/*LINTED*/break;
	case 85:
YY_RULE_SETUP

#line 202 "scanner.l"
{ __append_str(yytext); }
	/*LINTED*/break;
	case 86:
YY_RULE_SETUP

#line 203 "scanner.l"
{ __append_str(yytext); }
	/*LINTED*/break;
	case 87:
/* rule 87 can match eol */
YY_RULE_SETUP

#line 204 "scanner.l"
{
        __append_str(yytext);
        //yylineno++;
        fstack->line++; fstack->col = 1;
    } /* don't strip new lines */
	/*LINTED*/break;
	case 88:
YY_RULE_SETUP

#line 210 "scanner.l"
{
        printf("Warning: unrecognized character: %c (0x%02X)\n", yytext[0], yytext[0]);
        //return yytext[0];
    }
	/*LINTED*/break;
/* comments */
	case 89:
/* rule 89 can match eol */
YY_RULE_SETUP

#line 216 "scanner.l"
{ fstack->line++; fstack->col = 1; }
	/*LINTED*/break;
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SQUOTES):
case YY_STATE_EOF(DQUOTES):
#line 218 "scanner.l"
{

        incl_depth--;

        FileStack* tmp = fstack;

#ifdef ENABLE_PARSER_TRACE
        fprintf(stderr, ">>>>>> closing file: %s\n", tmp->fname);
#endif

        free((void*)tmp->fname);
        fclose(tmp->fptr);
        free(tmp);

        fstack = fstack->next;

        if(fstack == NULL) {
            yyterminate();
        }
        else {
            yy_delete_buffer(YY_CURRENT_BUFFER);
            yy_switch_to_buffer(fstack->buffer);
        }
    }
	/*LINTED*/break;
	case 90:
YY_RULE_SETUP

#line 244 "scanner.l"
yyecho();
	/*LINTED*/break;



			case YY_END_OF_BUFFER:
			{
				/* Amount of text matched not including the EOB char. */
				int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

				/* Undo the effects of YY_DO_BEFORE_ACTION. */
				*yy_cp = (yy_hold_char);
				YY_RESTORE_YY_MORE_OFFSET

				if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW ) {
					/* We're scanning a new file or input source.  It's
					 * possible that this happened because the user
					 * just pointed yyin at a new source and called
					 * yylex().  If so, then we have to assure
					 * consistency between yy_current_buffer() and our
					 * globals.  Here is the right place to do so, because
					 * this is the first action (other than possibly a
					 * back-up) that will match for the new input source.
					 */
					(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;

					YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;

					YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
				}

				/* Note that here we test for yy_c_buf_p "<=" to the position
				 * of the first EOB in the buffer, since yy_c_buf_p will
				 * already have been incremented past the NUL character
				 * (since all states make transitions on EOB to the
				 * end-of-buffer state).  Contrast this with the test
				 * in input().
				 */
				if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) { /* This was really a NUL. */
					yy_state_type yy_next_state;

					(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

					yy_current_state = yy_get_previous_state(  );

					/* Okay, we're now positioned to make the NUL
					 * transition.  We couldn't have
					 * yy_get_previous_state() go ahead and do it
					 * for us because it doesn't know how to deal
					 * with the possibility of jamming (and we don't
					 * want to build jamming into it because then it
					 * will run more slowly).
					 */

					yy_next_state = yy_try_NUL_trans( yy_current_state );

					yy_bp = (yytext_ptr) + YY_MORE_ADJ;

					if ( yy_next_state ) {
						/* Consume the NUL. */
						yy_cp = ++(yy_c_buf_p);
						yy_current_state = yy_next_state;
						goto yy_match;
					} else {
						
						/* Still need to initialize yy_cp, though
						 * yy_current_state was set up by
						 * yy_get_previous_state().
						 */
						yy_cp = (yy_c_buf_p);

						goto yy_find_action;
					}
				} else {	/* not a NUL */
					switch ( yy_get_next_buffer(  ) ) {
					case EOB_ACT_END_OF_FILE:
						(yy_did_buffer_switch_on_eof) = 0;

						if ( yywrap(  ) ) {
							/* Note: because we've taken care in
							 * yy_get_next_buffer() to have set up
							 * yytext, we can now set up
							 * yy_c_buf_p so that if some total
							 * hoser (like flex itself) wants to
							 * call the scanner after we return the
							 * YY_NULL, it'll still work - another
							 * YY_NULL will get returned.
							 */
							(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

							yy_act = YY_STATE_EOF(yystart());
							goto do_action;
						} else {
							if ( ! (yy_did_buffer_switch_on_eof) ) {
								YY_NEW_FILE;
							}
						}
						break;
					case EOB_ACT_CONTINUE_SCAN:
						(yy_c_buf_p) =
							(yytext_ptr) + yy_amount_of_matched_text;

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_match;

					case EOB_ACT_LAST_MATCH:
						(yy_c_buf_p) =
						&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_find_action;
					} /* end EOB inner switch */
				} /* end if */
				break;
			} /* case YY_END_OF_BUFFER */
			default:
				YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
			} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer (void)

{
		char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] ) {
		YY_FATAL_ERROR( "fatal flex scanner internal error--end of buffer missed" );
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 ) {
		/* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 ) {
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
		} else {
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i ) {
		*(dest++) = *(source++);
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING ) {
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;
	} else {
		int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 ) { /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			yybuffer b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer ) {
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 ) {
					b->yy_buf_size += b->yy_buf_size / 8;
				} else {
					b->yy_buf_size *= 2;
				}
				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
			} else {
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;
			}
			if ( ! b->yy_ch_buf ) {
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );
			}
			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

		}

		if ( num_to_read > YY_READ_BUF_SIZE ) {
			num_to_read = YY_READ_BUF_SIZE;
		}
		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	if ( (yy_n_chars) == 0 ) {
		if ( number_to_move == YY_MORE_ADJ ) {
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
		} else {
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
		}
	} else {
		ret_val = EOB_ACT_CONTINUE_SCAN;
	}
	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf ) {
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		}
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state (void)

{
	yy_state_type yy_current_state;
	char *yy_cp;
	
	/* Generate the code to find the start state. */

			yy_current_state = (yy_start);

			/* Set up for storing up states. */
			
	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp ) {
		/* Generate the code to find the next state. */
		
	int yy_c = (*yy_cp ? *(yy_ec+YY_SC_TO_UI(*yy_cp)) : YY_NUL_EC);
	/* Save the backing-up info \before/ computing the next state
	 * because we always compute one more state than needed - we
	 * always proceed until we reach a jam state
	 */
	
		/* Generate code to keep backing-up information. */

		if ( yy_accept[yy_current_state] ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
		yy_current_state = (int) yy_def[yy_current_state];

		/* We've arranged it so that templates are never chained
		 * to one another.  This means we can afford to make a
		 * very simple test to see if we need to convert to
		 * yy_c's meta-equivalence class without worrying
		 * about erroneously looking up the meta-equivalence
		 * class twice
		 */

		/* lastdfa + 2 == YY_JAMSTATE + 1 is the beginning of the templates */
		if (yy_current_state >= YY_JAMSTATE + 1) {
			yy_c = yy_meta[yy_c];
		}

	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];

	}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )

{
	int yy_is_jam;
		/* Generate code for handling NUL's, if needed. */

	/* First, deal with backing up and setting up yy_cp if the scanner
	 * finds that it should JAM on the NUL.
	 *
	 * Only generate a definition for "yy_cp" if we'll generate code
	 * that uses it.  Otherwise lint and the like complain.
	 */
	char *yy_cp = (yy_c_buf_p);

	int yy_c = YY_NUL_EC;
	/* Save the backing-up info \before/ computing the next state
	 * because we always compute one more state than needed - we
	 * always proceed until we reach a jam state
	 */
	
		/* Generate code to keep backing-up information. */

		if ( yy_accept[yy_current_state] ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
		yy_current_state = (int) yy_def[yy_current_state];

		/* We've arranged it so that templates are never chained
		 * to one another.  This means we can afford to make a
		 * very simple test to see if we need to convert to
		 * yy_c's meta-equivalence class without worrying
		 * about erroneously looking up the meta-equivalence
		 * class twice
		 */

		/* lastdfa + 2 == YY_JAMSTATE + 1 is the beginning of the templates */
		if (yy_current_state >= YY_JAMSTATE + 1) {
			yy_c = yy_meta[yy_c];
		}

	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];

yy_is_jam = (yy_current_state == YY_JAMSTATE);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_YYINPUT
int yyinput (void)

{
	int c;
	
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR ) {
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) {
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';
		} else {
			/* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) ) {
			case EOB_ACT_LAST_MATCH:
				/* This happens because yy_g_n_b()
				 * sees that we've accumulated a
				 * token and flags that we need to
				 * try matching the token before
				 * proceeding.  But for input(),
				 * there's no matching to consider.
				 * So convert the EOB_ACT_LAST_MATCH
				 * to EOB_ACT_END_OF_FILE.
				 */

				/* Reset buffer status. */
				yyrestart( yyin );

				/*FALLTHROUGH*/

			case EOB_ACT_END_OF_FILE:
				if ( yywrap(  ) ) {
					return 0;
				}
				if ( ! (yy_did_buffer_switch_on_eof) ) {
					YY_NEW_FILE;
				}
				return yyinput();

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) = (yytext_ptr) + offset;
				break;
			}
		}
	}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' ) {
		
    yylineno++;
;
	}
	
	return c;
}

#endif	/* ifndef YY_NO_YYINPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */

void yyrestart  (FILE * input_file )

{
		size_t new_size = 0;
	yy_state_type *new_state_buf = 0;

	if ( yy_current_buffer() == NULL ) {
		yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
	        	yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER_LVALUE, input_file );
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */

void yy_switch_to_buffer  (yybuffer  new_buffer )

{
		size_t new_size = 0;
	yy_state_type *new_state_buf = 0;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
	 */
	yyensure_buffer_stack ();
	if ( yy_current_buffer() == new_buffer ) {
		return;
	}
	if ( yy_current_buffer() ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)

{
		(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;

	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;

	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */

yybuffer yy_create_buffer  (FILE * file, int  size )

{
	yybuffer b;
	
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if (  b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( b->yy_ch_buf == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */

void yy_delete_buffer (yybuffer  b )

{
	
	if ( b == NULL ) {
		return;
	}
	if ( b == yy_current_buffer() ) {	/* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (yybuffer) 0;
	}
	if ( b->yy_is_our_buffer ) {
		yyfree( (void *) b->yy_ch_buf  );
	}
	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */

static void yy_init_buffer  (yybuffer  b, FILE * file )

{
	int oerrno = errno;
	
	yy_flush_buffer( b );

	b->yy_input_file = file;

    /* b->yy_input_file should never by NULL but we'll handle it cleanly
	 * on the off chance.
	 */
	if (b->yy_input_file == NULL){
	  b->yy_fill_buffer = 0;
	} else {
	  b->yy_fill_buffer = 1;
	}

	/* If b is the current buffer, then yy_init_buffer was _probably_
	 * called from yyrestart() or through yy_get_next_buffer.
	 * In that case, we don't want to reset the lineno or column.
	 */
	if (b != yy_current_buffer()) {
		b->yy_bs_lineno = 1;
		b->yy_bs_column = 0;
	}

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c yy_current_buffer().
 * 
 */

void yy_flush_buffer (yybuffer  b )

{
		if ( b == NULL ) {
		return;
	}
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yyatbol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer() ) {
		yy_load_buffer_state(  );
	}
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */

void yypush_buffer_state (yybuffer new_buffer )

{
		if (new_buffer == NULL) {
		return;
	}
	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( yy_current_buffer() != NULL ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	/* Only push if top exists. Otherwise, replace top. */
	if (yy_current_buffer()) {
		(yy_buffer_stack_top)++;
	}
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */

void yypop_buffer_state (void)

{
		if (yy_current_buffer() == NULL) {
		return;
	}
	yy_delete_buffer(yy_current_buffer() );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0) {
		--(yy_buffer_stack_top);
	}
	if (yy_current_buffer() != NULL) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */

static void yyensure_buffer_stack (void)

{
	yy_size_t num_to_alloc;
	
	if ((yy_buffer_stack) == NULL) {
		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
		 */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( (yy_buffer_stack == NULL) ) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {
		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ((yy_buffer_stack) == NULL) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}
		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_buffer  (char * base, yy_size_t  size )
{
	yybuffer b;
	
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR ) {
		/* They forgot to leave room for the EOB's. */
		return NULL;
	}
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );
	}
	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yyatbol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
yybuffer yy_scan_string (const char * yystr )
{
	
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_bytes  (const char * yybytes, int  _yybytes_len ) {
	yybuffer b;
	char *buf;
	yy_size_t n;
	int i;
	
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( buf == 0 ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );
	}
	for ( i = 0; i < _yybytes_len; ++i ) {
		buf[i] = yybytes[i];
	}
	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );
	}
	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do { \
		/* Undo effects of setting up yytext. */ \
		int yyless_macro_arg = (n); \
		YY_LESS_LINENO(yyless_macro_arg);\
			yytext[yyleng] = (yy_hold_char); \
			(yy_c_buf_p) = yytext + yyless_macro_arg; \
			(yy_hold_char) = *(yy_c_buf_p); \
			*(yy_c_buf_p) = '\0'; \
			yyleng = yyless_macro_arg; \
	} while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void) {
	
	return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void) {
		return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void) {
		return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void) {
		return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void) {
		return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number ) {
	
	yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str ) {
		yyin = _in_str ;
}

void yyset_out (FILE *  _out_str ) {
		yyout = _out_str ;
}

int yyget_debug  (void) {
		return yyflexdebug;
}

void yyset_debug (int  _bdebug ) {
		yyflexdebug = _bdebug ;
}

static int yy_init_globals (void) {
		/* Initialization is the same as for the non-reentrant scanner.
	 * This function is called from yylex_destroy(), so don't allocate here.
	 */

	/* We do not touch yylineno unless the option is enabled. */
	yylineno =  1;
    
	(yy_buffer_stack) = NULL;
	(yy_buffer_stack_top) = 0;
	(yy_buffer_stack_max) = 0;
	(yy_c_buf_p) = NULL;
	(yy_init) = 0;
	(yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
	yyin = stdin;
	yyout = stdout;
#else
	yyin = NULL;
	yyout = NULL;
#endif

	/* For future reference: Set errno on error, since we are called by
	 * yylex_init()
	 */
	return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void) {
	
	/* Pop the buffer stack, destroying each element. */
	while(yy_current_buffer()) {
		yy_delete_buffer( yy_current_buffer()  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

	/* Reset the globals. This is important in a non-reentrant scanner so the next time
	 * yylex() is called, initialization will occur. */
	yy_init_globals( );

	return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n ) {
		
	int i;
	for ( i = 0; i < n; ++i ) {
		s1[i] = s2[i];
	}
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size ) {
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size ) {
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr ) {
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#line 244 "scanner.l"


void open_file(const char *fname) {

#ifdef ENABLE_PARSER_TRACE
    fprintf(stderr, "<<<<<<< opening file: %s\n", fname);
#endif

    if(incl_depth > MAX_INCL) {
        fprintf(stderr, "FATAL ERROR: Maximum include depth exceeded\n");
        exit(1);
    }
    incl_depth++;

    FileStack* fs = malloc(sizeof(FileStack));
    fs->fname = strdup(fname);
    fs->line = 1;
    fs->col = 1;
    fs->next = NULL;

    yyin = fopen(fname, "r");
    if(yyin == NULL) {
        fprintf(stderr, "fatal error: cannot open input file: %s: %s\n", fname,
                strerror(errno));
        exit(1);
    }

    fs->fptr = yyin;
    yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
    fs->buffer = YY_CURRENT_BUFFER;

    if(fstack != NULL)
        fs->next = fstack;

    fstack = fs;
}

int get_line_no() {

    if(fstack != NULL)
        return fstack->line;
    else
        return -1;
}

int get_col_no() {

    if(fstack != NULL)
        return fstack->col;
    else
        return -1;
}

const char* get_file_name() {

    if(fstack != NULL)
        return fstack->fname;
    else
        return "no file open";
}

int main(int argc, char** argv) {

    if(argc < 2) {
        fprintf(stderr, "Need input file");
        exit(1);
    }

    open_file(argv[1]);
    return yyparse();
}
