/**
 * @file Ast.cpp
 * @brief AST pretty-printer.
 * @author Generated by GitHub Copilot
 */
#include "simp/Ast.hpp"

#include <ostream>

namespace simp {

std::unique_ptr<Expression> cloneExpression(const Expression& expression) {
    auto copy = std::make_unique<Expression>();
    copy->kind = expression.kind;
    copy->location = expression.location;
    copy->typeLocation = expression.typeLocation;
    copy->value = expression.value;
    copy->sliceHasStart = expression.sliceHasStart;
    copy->sliceHasEnd = expression.sliceHasEnd;
    copy->sliceHasStep = expression.sliceHasStep;
    copy->resolvedSignature = expression.resolvedSignature;
    copy->resolvedType = expression.resolvedType;
    if (expression.left) copy->left = cloneExpression(*expression.left);
    if (expression.right) copy->right = cloneExpression(*expression.right);
    for (const auto& argument : expression.arguments)
        copy->arguments.push_back(cloneExpression(*argument));
    copy->argumentNames = expression.argumentNames;
    copy->argumentNameLocations = expression.argumentNameLocations;
    copy->formatSegments = expression.formatSegments;
    copy->formatArgumentIndices = expression.formatArgumentIndices;
    copy->formatSpecs = expression.formatSpecs;
    return copy;
}

ClassDeclaration makeBuiltinExceptionClass() {
    ClassDeclaration declaration;
    declaration.name = "Exception";
    declaration.builtin = true;
    declaration.location = {"<builtin>", 1, 1};
    declaration.fields.push_back(
        {"String", "message", declaration.location, AccessLevel::Public});
    declaration.fields.push_back(
        {"bool", "runtime_owns_message", declaration.location, AccessLevel::Private});

    MethodDeclaration constructor;
    constructor.name = "Exception";
    constructor.returnType = "void";
    constructor.location = declaration.location;
    constructor.constructor = true;
    constructor.parameters.push_back({"String", "text", declaration.location});

    Statement assignment;
    assignment.kind = StatementKind::Assignment;
    assignment.location = declaration.location;
    assignment.target = std::make_unique<Expression>();
    assignment.target->kind = ExpressionKind::Identifier;
    assignment.target->location = declaration.location;
    assignment.target->value = "message";
    auto value = std::make_unique<Expression>();
    value->kind = ExpressionKind::Identifier;
    value->location = declaration.location;
    value->value = "text";
    assignment.expressions.push_back(std::move(value));
    constructor.body.push_back(std::move(assignment));
    declaration.methods.push_back(std::move(constructor));
    return declaration;
}

namespace {

void indent(std::ostream& output, int depth) {
    for (int index = 0; index < depth; ++index) {
        output << "  ";
    }
}

const char* expressionName(ExpressionKind kind) {
    switch (kind) {
    case ExpressionKind::BoundMethod: return "BoundMethod";
    case ExpressionKind::CallbackCall: return "CallbackCall";
    case ExpressionKind::Integer: return "Integer";
    case ExpressionKind::Unsigned: return "Unsigned";
    case ExpressionKind::Float: return "Float";
    case ExpressionKind::Boolean: return "Boolean";
    case ExpressionKind::String: return "String";
    case ExpressionKind::FormatString: return "FormatString";
    case ExpressionKind::Identifier: return "Identifier";
    case ExpressionKind::ImplicitThis: return "ImplicitThis";
    case ExpressionKind::Unary: return "Unary";
    case ExpressionKind::Binary: return "Binary";
    case ExpressionKind::Member: return "Member";
    case ExpressionKind::EnumConstant: return "EnumConstant";
    case ExpressionKind::Call: return "Call";
    case ExpressionKind::ConstructorCall: return "ConstructorCall";
    case ExpressionKind::BufferConstructor: return "BufferConstructor";
    case ExpressionKind::BufferLiteral: return "BufferLiteral";
    case ExpressionKind::Null: return "Null";
    case ExpressionKind::ArrayLiteral: return "ArrayLiteral";
    case ExpressionKind::MapLiteral: return "MapLiteral";
    case ExpressionKind::Index: return "Index";
    case ExpressionKind::Slice: return "Slice";
    case ExpressionKind::Cast: return "Cast";
    case ExpressionKind::ObjectCast: return "ObjectCast";
    case ExpressionKind::TypeTest: return "TypeTest";
    case ExpressionKind::TypeOf: return "TypeOf";
    case ExpressionKind::TypeName: return "TypeName";
    }
    return "Expression";
}

void dumpExpression(const Expression& expression, std::ostream& output, int depth) {
    indent(output, depth);
    output << expressionName(expression.kind);
    if (!expression.value.empty()) {
        output << " [" << expression.value << "]";
    }
    output << '\n';
    if (expression.left) {
        dumpExpression(*expression.left, output, depth + 1);
    }
    if (expression.right) {
        dumpExpression(*expression.right, output, depth + 1);
    }
    for (const auto& argument : expression.arguments) {
        dumpExpression(*argument, output, depth + 1);
    }
}

void dumpStatements(const std::vector<Statement>& statements, std::ostream& output, int depth);

void dumpStatement(const Statement& statement, std::ostream& output, int depth) {
    indent(output, depth);
    switch (statement.kind) {
    case StatementKind::Declaration:
        output << "Declaration [" << statement.declaredType << " " << statement.name << "]\n";
        break;
    case StatementKind::Assignment:
        output << "Assignment";
        if (statement.assignmentOperator != "=") {
            output << " [" << statement.assignmentOperator << "]";
        }
        output << '\n';
        break;
    case StatementKind::Print: output << "Print\n"; break;
    case StatementKind::If: output << "If\n"; break;
    case StatementKind::While: output << "While\n"; break;
    case StatementKind::DoWhile: output << "Do while\n"; break;
    case StatementKind::Break: output << "Break\n"; break;
    case StatementKind::Continue: output << "Continue\n"; break;
    case StatementKind::ForEach:
        output << (statement.keyName.empty()
                       ? "For each [" + statement.name + "]\n"
                       : "For each [" + statement.keyName + ", " + statement.name + "]\n");
        break;
    case StatementKind::Block: output << "Block\n"; break;
    case StatementKind::Return: output << "Return\n"; break;
    case StatementKind::Expression: output << "Expression statement\n"; break;
    case StatementKind::SuperConstructorCall:
        output << (statement.virtualBaseInitializer ? "Super virtual constructor [" :
                                                       "Super constructor [")
               << statement.name << "]\n";
        break;
    case StatementKind::Raise: output << "Raise\n"; break;
    case StatementKind::Try: output << "Try\n"; break;
    case StatementKind::InlineC: output << "Inline C\n"; break;
    }
    if (statement.target) {
        dumpExpression(*statement.target, output, depth + 1);
    }
    for (const auto& expression : statement.expressions) {
        dumpExpression(*expression, output, depth + 1);
    }
    if (!statement.body.empty()) {
        dumpStatements(statement.body, output, depth + 1);
    }
    if (statement.kind == StatementKind::Try) {
        for (const auto& handler : statement.exceptionHandlers) {
            indent(output, depth + 1);
            output << "Except";
            if (!handler.exceptionType.empty()) {
                output << " [" << handler.exceptionType << "]";
            }
            if (handler.hasBinding) output << " as [" << handler.name << "]";
            output << '\n';
            dumpStatements(handler.body, output, depth + 2);
        }
    } else if (statement.hasAlternate) {
        indent(output, depth + 1);
        output << "Else\n";
        dumpStatements(statement.alternate, output, depth + 2);
    }
    if (statement.hasCleanup) {
        indent(output, depth + 1);
        output << "Finally\n";
        dumpStatements(statement.cleanup, output, depth + 2);
    }
}

void dumpStatements(const std::vector<Statement>& statements, std::ostream& output, int depth) {
    for (const auto& statement : statements) {
        dumpStatement(statement, output, depth);
    }
}

} // namespace

void dumpAst(const Program& program, std::ostream& output) {
    output << "Program\n";
    for (const auto& import : program.imports) {
        indent(output, 1);
        output << "Import [" << import.moduleName;
        if (!import.alias.empty()) output << " as " << import.alias;
        output << "]\n";
    }
    for (const auto& declaration : program.namespaces) {
        indent(output, 1);
        output << "Namespace [";
        for (std::size_t index = 0; index < declaration.path.size(); ++index) {
            if (index != 0) output << ".";
            output << declaration.path[index];
        }
        output << "]\n";
    }
    for (const auto& definition : program.outOfLineMethods) {
        indent(output, 1);
        output << "Out-of-line method [" << definition.className << "."
               << definition.method.returnType << " " << definition.method.name << "(";
        for (std::size_t index = 0; index < definition.method.parameters.size(); ++index) {
            if (index != 0) output << ", ";
            output << definition.method.parameters[index].type << " "
                   << definition.method.parameters[index].name;
        }
        output << ")";
        if (definition.method.externalBinding) {
            output << " from \"" << definition.method.externalSymbol << "\"";
        }
        output << "]\n";
    }
    for (const auto& declaration : program.classes) {
        if (declaration.builtin) continue;
        indent(output, 1);
        output << "Class [" << declaration.name;
        if (!declaration.baseClassNames.empty()) {
            output << " : ";
            for (std::size_t index = 0; index < declaration.baseClassNames.size(); ++index) {
                if (index != 0) output << ", ";
                const char* access = declaration.baseAccess[index] == AccessLevel::Public
                                         ? "public "
                                         : declaration.baseAccess[index] == AccessLevel::Protected
                                               ? "protected "
                                               : "private ";
                output << access;
                if (declaration.baseVirtual[index]) output << "virtual ";
                output << declaration.baseClassNames[index];
            }
        }
        output << "]\n";
        for (const auto& field : declaration.fields) {
            indent(output, 2);
            output << "Field [" << field.type << " " << field.name << "]\n";
        }
        for (const auto& member : declaration.enumMembers) {
            indent(output, 2);
            output << "Enum member [" << member.name;
            if (member.value) output << " = " << *member.value;
            output << "]\n";
        }
        for (const auto& method : declaration.methods) {
            indent(output, 2);
            output << (method.constructor ? "Constructor [" :
                       method.declarationOnly ? "Method declaration [" : "Method [")
                   << method.returnType << " " << method.name << "]\n";
            dumpStatements(method.body, output, 3);
        }
    }
    dumpStatements(program.statements, output, 1);
}

} // namespace simp
