/**
 * @file CodeGeneratorLayout.cpp
 * @brief Object subobject layout and qualified base-path resolution.
 * @author Generated by GitHub Copilot
 */
#include "simp/CodeGenerator.hpp"

#include "simp/Diagnostic.hpp"

#include <algorithm>
#include <stdexcept>

namespace simp {

const FieldDeclaration* CodeGenerator::findField(const ClassDeclaration& owner,
                                                  const std::string& name,
                                                  std::vector<std::size_t>& path) const {
    const auto visit = [this, &name](const auto& self, const ClassDeclaration& declaration,
                                     std::vector<std::size_t>& fieldPath)
        -> const FieldDeclaration* {
        for (std::size_t index = 0; index < declaration.baseClassNames.size(); ++index) {
            const auto base = classes_.find(declaration.baseClassNames[index]);
            if (base == classes_.end()) continue;
            fieldPath.push_back(index + 2);
            if (const auto* field = self(self, *base->second, fieldPath)) return field;
            fieldPath.pop_back();
        }
        for (std::size_t index = 0; index < declaration.fields.size(); ++index) {
            if (declaration.fields[index].name == name) {
                fieldPath.push_back(declaration.baseClassNames.size() + index + 2);
                return &declaration.fields[index];
            }
        }
        return nullptr;
    };
    path.clear();
    return visit(visit, owner, path);
}

std::size_t CodeGenerator::flattenedFieldCount(const ClassDeclaration& owner) const {
    std::size_t count = owner.fields.size();
    for (const auto& baseName : owner.baseClassNames) {
        const auto base = classes_.find(baseName);
        if (base != classes_.end()) count += flattenedFieldCount(*base->second);
    }
    return count;
}

std::vector<std::size_t> CodeGenerator::directBasePath(
    const ClassDeclaration& owner, const std::vector<std::string>& path) const {
    std::vector<std::size_t> indices;
    const ClassDeclaration* current = &owner;
    for (const auto& baseName : path) {
        const auto position = std::find(current->baseClassNames.begin(),
                                        current->baseClassNames.end(), baseName);
        if (position == current->baseClassNames.end()) {
            throw std::logic_error("invalid qualified base path");
        }
        indices.push_back(static_cast<std::size_t>(
                              std::distance(current->baseClassNames.begin(), position)) +
                          2);
        current = classes_.at(baseName);
    }
    return indices;
}

std::vector<std::pair<std::vector<std::string>, const ClassDeclaration*>>
CodeGenerator::subobjects(const ClassDeclaration& owner) const {
    std::vector<std::pair<std::vector<std::string>, const ClassDeclaration*>> result;
    const auto visit = [this, &result](const auto& self, const ClassDeclaration& current,
                                       std::vector<std::string> path) -> void {
        result.emplace_back(path, &current);
        for (const auto& baseName : current.baseClassNames) {
            const auto base = classes_.find(baseName);
            if (base == classes_.end()) continue;
            auto basePath = path;
            basePath.push_back(baseName);
            self(self, *base->second, std::move(basePath));
        }
    };
    visit(visit, owner, {});
    return result;
}

std::string CodeGenerator::emitSubobjectAddress(
    const std::string& pointer, const ClassDeclaration& owner,
    const std::vector<std::string>& path) {
    if (path.empty()) return pointer;
    const auto indices = directBasePath(owner, path);
    const auto result = newTemporary();
    instructions_ += "  " + result + " = getelementptr inbounds %Class." + owner.name +
                     ", ptr " + pointer + ", i32 0";
    for (const auto index : indices) {
        instructions_ += ", i32 " + std::to_string(index);
    }
    instructions_ += "\n";
    return result;
}

std::string CodeGenerator::viewMetadataSymbol(
    const ClassDeclaration& owner, const std::vector<std::string>& path) const {
    std::string symbol = "@.simp.view.meta." + owner.name + ".p";
    for (std::size_t index = 0; index < path.size(); ++index) {
        if (index != 0) symbol += "_";
        symbol += path[index];
    }
    return symbol;
}

bool CodeGenerator::resolveBaseQualifier(const Expression& receiver,
                                         const Expression*& root,
                                         const ClassDeclaration*& view,
                                         std::vector<std::string>& path) const {
    std::vector<std::string> reversed;
    const Expression* cursor = &receiver;
    while (cursor->kind == ExpressionKind::Member) {
        reversed.push_back(cursor->value);
        cursor = cursor->left.get();
    }
    if (reversed.empty() || cursor->kind != ExpressionKind::Identifier) return false;
    const auto binding = findVariable(cursor->value, cursor->location);
    const auto owner = classes_.find(binding.type);
    if (owner == classes_.end()) return false;
    root = cursor;
    view = owner->second;
    for (auto name = reversed.rbegin(); name != reversed.rend(); ++name) {
        if (std::find(view->baseClassNames.begin(), view->baseClassNames.end(), *name) ==
            view->baseClassNames.end()) {
            return false;
        }
        const auto base = classes_.find(*name);
        if (base == classes_.end()) return false;
        path.push_back(*name);
        view = base->second;
    }
    return true;
}

CodeGenerator::Binding CodeGenerator::findVariable(const std::string& name,
                                                   const SourceLocation& location) const {
    for (auto scope = scopes_.rbegin(); scope != scopes_.rend(); ++scope) {
        const auto found = scope->find(name);
        if (found != scope->end()) return found->second;
    }
    if (currentFieldClass_ != nullptr) {
        std::vector<std::size_t> path;
        if (const auto* field = findField(*currentFieldClass_, name, path)) {
            return {field->type, "%this", std::move(path), true};
        }
    }
    throw DiagnosticError(location, "backend could not resolve variable or field '" + name + "'");
}

std::string CodeGenerator::emitAddress(const Binding& binding, const SourceLocation& location) {
    if (!binding.field) return binding.pointer;
    const auto pointer = newTemporary();
    instructions_ += "  " + pointer + " = getelementptr inbounds %Class." +
                     currentFieldClass_->name + ", ptr %this, i32 0";
    for (const auto index : binding.fieldPath) {
        instructions_ += ", i32 " + std::to_string(index);
    }
    instructions_ += "\n";
    (void)location;
    return pointer;
}

CodeGenerator::Value CodeGenerator::convertObjectValue(
    Value value, const std::string& expectedType, const SourceLocation& location) {
    if (value.operand == "null" || value.type == expectedType ||
        classes_.find(value.type) == classes_.end() ||
        classes_.find(expectedType) == classes_.end()) {
        if (value.operand == "null") value.type = expectedType;
        return value;
    }
    const auto& owner = *classes_.at(value.type);
    std::vector<std::string> path;
    const auto findPath = [this, &expectedType](const auto& self,
                                                const ClassDeclaration& current,
                                                std::vector<std::string>& candidate)
        -> bool {
        for (const auto& baseName : current.baseClassNames) {
            candidate.push_back(baseName);
            if (baseName == expectedType) return true;
            if (self(self, *classes_.at(baseName), candidate)) return true;
            candidate.pop_back();
        }
        return false;
    };
    if (!findPath(findPath, owner, path)) {
        throw DiagnosticError(location, "backend could not find the required base subobject");
    }
    const auto address = emitSubobjectAddress(value.operand, owner, path);
    return {expectedType, address};
}

} // namespace simp
