/**
 * @file CodeGeneratorDispatch.cpp
 * @brief Stable virtual method slots and inherited method lookup.
 * @author Generated by GitHub Copilot
 */
#include "simp/CodeGenerator.hpp"

#include <algorithm>
#include <stdexcept>

namespace simp {

const MethodDeclaration* CodeGenerator::findMethod(const ClassDeclaration& owner,
                                                    const std::string& name) const {
    for (const auto& method : owner.methods) {
        if (method.name == name && !method.constructor && !method.destructor) return &method;
    }
    const MethodDeclaration* result = nullptr;
    for (const auto& baseName : owner.baseClassNames) {
        const auto base = classes_.find(baseName);
        if (base == classes_.end()) continue;
        if (const auto* candidate = findMethod(*base->second, name)) {
            if (result != nullptr) return nullptr;
            result = candidate;
        }
    }
    return result;
}

std::vector<const MethodDeclaration*> CodeGenerator::methodSlots(
    const ClassDeclaration& owner) const {
    std::vector<const MethodDeclaration*> slots;
    const auto append = [this, &slots](const auto& self,
                                       const ClassDeclaration& declaration) -> void {
        for (const auto& baseName : declaration.baseClassNames) {
            const auto base = classes_.find(baseName);
            if (base != classes_.end()) self(self, *base->second);
        }
        for (const auto& method : declaration.methods) {
            if (method.constructor || method.destructor) continue;
            const auto inherited = std::find_if(
                slots.begin(), slots.end(), [&method](const MethodDeclaration* candidate) {
                    return candidate->name == method.name;
                });
            if (inherited == slots.end()) {
                slots.push_back(&method);
            } else {
                *inherited = &method;
            }
        }
    };
    append(append, owner);
    return slots;
}

std::size_t CodeGenerator::methodSlot(const ClassDeclaration& owner,
                                      const std::string& name) const {
    const auto slots = methodSlots(owner);
    for (std::size_t index = 0; index < slots.size(); ++index) {
        if (slots[index]->name == name) return index;
    }
    throw std::logic_error("resolved method has no dispatch slot");
}

std::string CodeGenerator::declaringClass(const MethodDeclaration& method) const {
    for (const auto& entry : classes_) {
        for (const auto& candidate : entry.second->methods) {
            if (&candidate == &method) return entry.first;
        }
    }
    return {};
}

} // namespace simp
