/**
 * @file CodeGeneratorPrint.cpp
 * @brief LLVM string constants and formatted print lowering.
 * @author Generated by GitHub Copilot
 */
#include "simp/CodeGenerator.hpp"

#include "simp/Diagnostic.hpp"

#include <iomanip>
#include <sstream>

namespace simp {
namespace {

std::string llvmBytes(const std::string& bytes) {
    std::ostringstream escaped;
    for (const unsigned char byte : bytes) {
        if (byte >= 0x20 && byte <= 0x7e && byte != '"' && byte != '\\') {
            escaped << static_cast<char>(byte);
        } else {
            escaped << '\\' << std::uppercase << std::hex << std::setw(2) << std::setfill('0')
                    << static_cast<unsigned>(byte) << std::nouppercase << std::dec;
        }
    }
    return escaped.str();
}

} // namespace

std::string CodeGenerator::internString(const std::string& bytes) {
    const auto name = "@.simp.string." + std::to_string(nextString_++);
    stringGlobals_ += name + " = private unnamed_addr constant [" +
                      std::to_string(bytes.size()) + " x i8] c\"" + llvmBytes(bytes) + "\"\n";
    return name;
}

void CodeGenerator::emitStringBytes(const std::string& bytes) {
    if (bytes.empty()) return;
    const auto global = internString(bytes);
    const auto pointer = newTemporary();
    instructions_ += "  " + pointer + " = getelementptr inbounds [" +
                     std::to_string(bytes.size()) + " x i8], ptr " + global + ", i64 0, i64 0\n";
    const auto stream = newTemporary();
    instructions_ += "  " + stream + " = load ptr, ptr @stdout\n";
    instructions_ += "  call i64 @fwrite(ptr " + pointer + ", i64 1, i64 " +
                     std::to_string(bytes.size()) + ", ptr " + stream + ")\n";
}

void CodeGenerator::emitPrint(const Statement& statement) {
    if (statement.expressions.empty()) return;
    const auto& expression = *statement.expressions.front();
    if (expression.kind == ExpressionKind::String) {
        emitStringBytes(expression.value);
    } else {
        const auto value = emitExpression(expression);
        emitPrintValue(value, statement.location);
    }
}

void CodeGenerator::emitPrintValue(const Value& value, const SourceLocation& location) {
    if (!value.nullFlag.empty()) {
        // Scalar locals track nullness via a companion i1 flag (see the
        // "Nullability model (confirmed)" note in SIMPLE-LANGUAGE-NOTES.md);
        // a null value always prints as the literal text "(null)".
        const auto nullLabel = freshLabel("print.scalar.null");
        const auto valueLabel = freshLabel("print.scalar.value");
        const auto endLabel = freshLabel("print.scalar.end");
        instructions_ += "  br i1 " + value.nullFlag + ", label %" + nullLabel + ", label %" +
                         valueLabel + "\n" + nullLabel + ":\n";
        emitStringBytes("(null)");
        instructions_ += "  br label %" + endLabel + "\n" + valueLabel + ":\n";
        Value nonNull = value;
        nonNull.nullFlag.clear();
        emitPrintValue(nonNull, location);
        instructions_ += "  br label %" + endLabel + "\n" + endLabel + ":\n";
        return;
    }
    if (value.type == "int") {
        instructions_ += "  call i32 (ptr, ...) @printf(ptr @.simp.int.format, i64 " +
                         value.operand + ")\n";
    } else if (value.type == "unsigned") {
        instructions_ += "  call i32 (ptr, ...) @printf(ptr @.simp.unsigned.format, i64 " +
                         value.operand + ")\n";
    } else if (value.type == "float") {
        instructions_ += "  call i32 (ptr, ...) @printf(ptr @.simp.float.format, double " +
                         value.operand + ")\n";
    } else if (value.type == "bool") {
        const auto trueLabel = freshLabel("print.bool.true");
        const auto falseLabel = freshLabel("print.bool.false");
        const auto endLabel = freshLabel("print.bool.end");
        instructions_ += "  br i1 " + value.operand + ", label %" + trueLabel +
                         ", label %" + falseLabel + "\n"
                         + trueLabel + ":\n";
        emitStringBytes("true");
        instructions_ += "  br label %" + endLabel + "\n" + falseLabel + ":\n";
        emitStringBytes("false");
        instructions_ += "  br label %" + endLabel + "\n" + endLabel + ":\n";
    } else if (isStringType(value.type)) {
        const auto isNull = newTemporary();
        const auto nullLabel = freshLabel("print.string.null");
        const auto dataLabel = freshLabel("print.string.data");
        const auto endLabel = freshLabel("print.string.end");
        instructions_ += "  " + isNull + " = icmp eq ptr " + value.operand + ", null\n"
                         "  br i1 " + isNull + ", label %" + nullLabel + ", label %" +
                         dataLabel + "\n" + nullLabel + ":\n";
        emitStringBytes("(null)");
        instructions_ += "  br label %" + endLabel + "\n" + dataLabel + ":\n";
        std::string data;
        std::string length;
        emitStringBytesAccess(value, location, data, length);
        const auto stream = newTemporary();
        instructions_ += "  " + stream + " = load ptr, ptr @stdout\n";
        instructions_ += "  call i64 @fwrite(ptr " + data + ", i64 1, i64 " + length +
                         ", ptr " + stream + ")\n";
        instructions_ += "  br label %" + endLabel + "\n" + endLabel + ":\n";
    } else if (value.type == "type") {
        const auto data = newTemporary();
        const auto length = newTemporary();
        instructions_ += "  " + data + " = extractvalue %SimpleString " + value.operand +
                         ", 0\n";
        instructions_ += "  " + length + " = extractvalue %SimpleString " + value.operand +
                         ", 1\n";
        const auto isNull = newTemporary();
        const auto nullLabel = freshLabel("print.string.null");
        const auto dataLabel = freshLabel("print.string.data");
        const auto endLabel = freshLabel("print.string.end");
        instructions_ += "  " + isNull + " = icmp eq ptr " + data + ", null\n"
                         "  br i1 " + isNull + ", label %" + nullLabel + ", label %" +
                         dataLabel + "\n" + nullLabel + ":\n";
        emitStringBytes("(null)");
        instructions_ += "  br label %" + endLabel + "\n" + dataLabel + ":\n";
        const auto stream = newTemporary();
        instructions_ += "  " + stream + " = load ptr, ptr @stdout\n";
        instructions_ += "  call i64 @fwrite(ptr " + data + ", i64 1, i64 " + length +
                         ", ptr " + stream + ")\n";
        instructions_ += "  br label %" + endLabel + "\n" + endLabel + ":\n";
    } else if (value.type == "any") {
        emitPrintDynamicValue(value, location);
    } else {
        unsupported(location, "printing object references");
    }
}

void CodeGenerator::emitPrintDynamicValue(const Value& value,
                                         const SourceLocation& location) {
    const auto tag = newTemporary();
    instructions_ += "  " + tag + " = extractvalue %SimpleArrayValue " + value.operand + ", 0\n";
    const auto intLabel = freshLabel("print.any.int");
    const auto stringLabel = freshLabel("print.any.string");
    const auto boolLabel = freshLabel("print.any.bool");
    const auto floatLabel = freshLabel("print.any.float");
    const auto unsignedLabel = freshLabel("print.any.unsigned");
    const auto objectLabel = freshLabel("print.any.object");
    const auto nullLabel = freshLabel("print.any.null");
    const auto instanceLabel = freshLabel("print.any.instance");
    const auto invalidLabel = freshLabel("print.any.invalid");
    const auto endLabel = freshLabel("print.any.end");
    instructions_ += "  switch i64 " + tag + ", label %" + objectLabel + " [ i64 1, label %" +
                     intLabel + " i64 2, label %" + stringLabel + " i64 11, label %" +
                     stringLabel + " i64 6, label %" + boolLabel +
                     " i64 7, label %" + floatLabel + " i64 8, label %" + unsignedLabel +
                     " i64 9, label %" + invalidLabel + " i64 10, label %" + invalidLabel +
                     " ]\n";
    instructions_ += intLabel + ":\n";
    const auto stored = newTemporary();
    instructions_ += "  " + stored + " = extractvalue %SimpleArrayValue " + value.operand +
                     ", 1\n"
                     "  call i32 (ptr, ...) @printf(ptr @.simp.int.format, i64 " + stored +
                     ")\n"
                     "  br label %" + endLabel + "\n";
    instructions_ += boolLabel + ":\n";
    const auto boolStored = newTemporary();
    const auto boolValue = newTemporary();
    instructions_ += "  " + boolStored + " = extractvalue %SimpleArrayValue " + value.operand +
                     ", 1\n"
                     "  " + boolValue + " = trunc i64 " + boolStored + " to i1\n";
    emitPrintValue({"bool", boolValue}, {});
    instructions_ += "  br label %" + endLabel + "\n";
    instructions_ += floatLabel + ":\n";
    const auto floatStored = newTemporary();
    const auto floatValue = newTemporary();
    instructions_ += "  " + floatStored + " = extractvalue %SimpleArrayValue " + value.operand +
                     ", 1\n"
                     "  " + floatValue + " = bitcast i64 " + floatStored + " to double\n";
    emitPrintValue({"float", floatValue}, {});
    instructions_ += "  br label %" + endLabel + "\n";
    instructions_ += unsignedLabel + ":\n";
    const auto unsignedValue = newTemporary();
    instructions_ += "  " + unsignedValue + " = extractvalue %SimpleArrayValue " +
                     value.operand + ", 1\n";
    emitPrintValue({"unsigned", unsignedValue}, {});
    instructions_ += "  br label %" + endLabel + "\n";
    instructions_ += stringLabel + ":\n";
    const auto stringData = newTemporary();
    const auto stringLength = newTemporary();
    const auto stringStream = newTemporary();
    instructions_ += "  " + stringData + " = extractvalue %SimpleArrayValue " + value.operand +
                     ", 2\n"
                     "  " + stringLength + " = extractvalue %SimpleArrayValue " + value.operand +
                     ", 3\n"
                     "  " + stringStream + " = load ptr, ptr @stdout\n"
                     "  call i64 @fwrite(ptr " + stringData + ", i64 1, i64 " + stringLength +
                     ", ptr " + stringStream + ")\n"
                     "  br label %" + endLabel + "\n";
    instructions_ += invalidLabel + ":\n";
    const auto file = internString(location.file);
    const auto message = internString("buffer and handle values are not printable");
    instructions_ += "  call void @simp_exception_raise(ptr " + message + ", i64 " +
                     std::to_string(std::string("buffer and handle values are not printable").size()) +
                     ", ptr " + file + ", i64 " + std::to_string(location.file.size()) +
                     ", i64 " + std::to_string(location.line) + ", i64 " +
                     std::to_string(location.column) + ")\n"
                     "  unreachable\n";
    instructions_ += objectLabel + ":\n";
    const auto objectPointer = newTemporary();
    const auto isNull = newTemporary();
    instructions_ += "  " + objectPointer + " = extractvalue %SimpleArrayValue " +
                     value.operand + ", 2\n"
                     "  " + isNull + " = icmp eq ptr " + objectPointer + ", null\n"
                     "  br i1 " + isNull + ", label %" + nullLabel + ", label %" +
                     instanceLabel + "\n";
    instructions_ += nullLabel + ":\n";
    emitStringBytes("(null)");
    instructions_ += "  br label %" + endLabel + "\n";
    // Printing an 'any' object reference does not (yet) dispatch to a
    // user-defined toString(); it prints a fixed placeholder so output stays
    // deterministic regardless of the referenced class's runtime identity.
    instructions_ += instanceLabel + ":\n";
    // A String instance prints its bytes; every other class prints a fixed
    // placeholder because dynamic printing does not dispatch to user code.
    const auto instanceMetadata = newTemporary();
    const auto isString = newTemporary();
    const auto stringObjectLabel = freshLabel("print.any.string.object");
    const auto otherObjectLabel = freshLabel("print.any.other.object");
    instructions_ += "  " + instanceMetadata + " = load ptr, ptr " + objectPointer + "\n"
                     "  " + isString + " = icmp eq ptr " + instanceMetadata + ", " +
                     classMetadataSymbol("String") + "\n"
                     "  br i1 " + isString + ", label %" + stringObjectLabel + ", label %" +
                     otherObjectLabel + "\n" + stringObjectLabel + ":\n";
    emitPrintValue({"String", objectPointer}, location);
    instructions_ += "  br label %" + endLabel + "\n" + otherObjectLabel + ":\n";
    emitStringBytes("<object>");
    instructions_ += "  br label %" + endLabel + "\n";
    instructions_ += endLabel + ":\n";
}

} // namespace simp
