/**
 * @file CodeGeneratorExceptions.cpp
 * @brief LLVM control-flow generation for the supported exception subset.
 * @author Generated by GitHub Copilot
 */
#include "simp/CodeGenerator.hpp"

namespace simp {

void CodeGenerator::emitTry(const Statement& statement) {
    const auto frameNumber = nextExceptionFrame_++;
    const auto frame = "%simp.exception.frame." + std::to_string(frameNumber);
    const auto frameSize = "%simp.exception.size." + std::to_string(frameNumber);
    entryAllocas_ += "  " + frameSize + " = call i64 @simp_exception_frame_size()\n"
                     "  " + frame + " = alloca i8, i64 " + frameSize + ", align 16\n";
    instructions_ += "  call void @simp_exception_frame_init(ptr " + frame + ")\n";
    const auto buffer = newTemporary();
    const auto jumpResult = newTemporary();
    const auto normal = newTemporary();
    const auto bodyLabel = freshLabel("try.body");
    const auto exceptionLabel = freshLabel("try.exception");
    const auto endLabel = freshLabel("try.end");
    const auto bodyDoneLabel = freshLabel("try.body.done");
    instructions_ += "  " + buffer + " = call ptr @simp_exception_frame_buffer(ptr " +
                     frame + ")\n"
                     "  " + jumpResult + " = call i32 @setjmp(ptr " + buffer + ") #0\n"
                     "  " + normal + " = icmp eq i32 " + jumpResult + ", 0\n"
                     "  br i1 " + normal + ", label %" + bodyLabel + ", label %" +
                     exceptionLabel + "\n"
                     + bodyLabel + ":\n"
                     "  call void @simp_exception_push(ptr " + frame + ")\n";
    scopes_.emplace_back();
    blockTerminated_ = false;
    emitStatements(statement.body);
    const bool bodyTerminated = blockTerminated_;
    scopes_.pop_back();
    if (!bodyTerminated) {
        instructions_ += "  call void @simp_exception_pop(ptr " + frame + ")\n"
                         "  br label %" + bodyDoneLabel + "\n";
    }

    instructions_ += exceptionLabel + ":\n";
    blockTerminated_ = false;
    if (statement.hasAlternate) {
        std::string caughtStringSlot;
        if (statement.hasExceptionBinding) {
            const auto length = newTemporary();
            const auto message = newTemporary();
            const auto stringFirst = newTemporary();
            const auto stringValue = newTemporary();
            const auto messageSlot = "%v" + std::to_string(nextVariable_++);
            entryAllocas_ += "  " + messageSlot + " = alloca %SimpleString\n";
            instructions_ += "  " + length +
                             " = call i64 @simp_exception_message_length(ptr " + frame + ")\n"
                             "  " + message +
                             " = call ptr @simp_exception_take_message(ptr " + frame + ")\n"
                             "  " + stringFirst + " = insertvalue %SimpleString poison, ptr " +
                             message + ", 0\n"
                             "  " + stringValue + " = insertvalue %SimpleString " + stringFirst +
                             ", i64 " + length + ", 1\n"
                             "  store %SimpleString " + stringValue + ", ptr " +
                             messageSlot + "\n";
            caughtStringSlot = messageSlot;
        } else {
            instructions_ += "  call void @simp_exception_clear(ptr " + frame + ")\n";
        }
        if (statement.hasCleanup || statement.hasExceptionBinding) {
            const auto catchNumber = nextExceptionFrame_++;
            const auto catchFrame = "%simp.exception.frame." + std::to_string(catchNumber);
            const auto catchSize = "%simp.exception.size." + std::to_string(catchNumber);
            entryAllocas_ += "  " + catchSize + " = call i64 @simp_exception_frame_size()\n"
                             "  " + catchFrame + " = alloca i8, i64 " + catchSize +
                             ", align 16\n";
            instructions_ += "  call void @simp_exception_frame_init(ptr " + catchFrame +
                             ")\n";
            const auto catchBuffer = newTemporary();
            const auto catchResult = newTemporary();
            const auto catchNormal = newTemporary();
            const auto catchBodyLabel = freshLabel("except.body");
            const auto catchErrorLabel = freshLabel("except.exception");
            const auto catchDoneLabel = freshLabel("except.done");
            instructions_ += "  " + catchBuffer +
                             " = call ptr @simp_exception_frame_buffer(ptr " + catchFrame +
                             ")\n"
                             "  " + catchResult + " = call i32 @setjmp(ptr " + catchBuffer +
                             ") #0\n"
                             "  " + catchNormal + " = icmp eq i32 " + catchResult + ", 0\n"
                             "  br i1 " + catchNormal + ", label %" + catchBodyLabel +
                             ", label %" + catchErrorLabel + "\n"
                             + catchBodyLabel + ":\n"
                             "  call void @simp_exception_push(ptr " + catchFrame + ")\n";
            scopes_.emplace_back();
            if (statement.hasExceptionBinding) {
                scopes_.back().emplace(
                    statement.name,
                    Binding{"string", caughtStringSlot, 0, false, true});
            }
            blockTerminated_ = false;
            emitStatements(statement.alternate);
            const bool catchTerminated = blockTerminated_;
            scopes_.pop_back();
            if (!catchTerminated) {
                instructions_ += "  call void @simp_exception_pop(ptr " + catchFrame + ")\n"
                                 "  br label %" + catchDoneLabel + "\n";
            }
            instructions_ += catchErrorLabel + ":\n";
            blockTerminated_ = false;
            if (statement.hasExceptionBinding) {
                instructions_ += "  call void @simp_exception_clear(ptr " + frame + ")\n";
            }
            scopes_.emplace_back();
            emitStatements(statement.cleanup);
            scopes_.pop_back();
            if (!blockTerminated_) {
                instructions_ += "  call void @simp_exception_rethrow(ptr " + catchFrame +
                                 ")\n"
                                 "  unreachable\n";
            }
            instructions_ += catchDoneLabel + ":\n";
            blockTerminated_ = false;
            scopes_.emplace_back();
            if (statement.hasExceptionBinding) {
                instructions_ += "  call void @simp_exception_clear(ptr " + frame + ")\n";
            }
            if (statement.hasCleanup) emitStatements(statement.cleanup);
            scopes_.pop_back();
            if (!blockTerminated_) instructions_ += "  br label %" + endLabel + "\n";
        } else {
            scopes_.emplace_back();
            if (statement.hasExceptionBinding) {
                scopes_.back().emplace(
                    statement.name,
                    Binding{"string", caughtStringSlot, 0, false, true});
            }
            blockTerminated_ = false;
            emitStatements(statement.alternate);
            scopes_.pop_back();
            if (!blockTerminated_) instructions_ += "  br label %" + endLabel + "\n";
        }
    } else {
        blockTerminated_ = false;
        scopes_.emplace_back();
        emitStatements(statement.cleanup);
        scopes_.pop_back();
        if (!blockTerminated_) {
            instructions_ += "  call void @simp_exception_rethrow(ptr " + frame + ")\n"
                             "  unreachable\n";
        }
    }

    instructions_ += bodyDoneLabel + ":\n";
    blockTerminated_ = false;
    scopes_.emplace_back();
    emitStatements(statement.cleanup);
    scopes_.pop_back();
    if (!blockTerminated_) instructions_ += "  br label %" + endLabel + "\n";
    instructions_ += endLabel + ":\n";
    blockTerminated_ = false;
}

} // namespace simp
