/**
 * @file CodeGeneratorModule.cpp
 * @brief LLVM object layouts, class metadata, and function/module assembly.
 * @author Generated by GitHub Copilot
 */
#include "simp/CodeGenerator.hpp"

#include <algorithm>
#include <sstream>
#include <utility>
#include <unordered_set>
#include <vector>

namespace simp {

namespace {

std::string subobjectTag(const std::vector<std::string>& path,
                         const ClassDeclaration&) {
    if (path.empty()) return "root";
    std::string tag = "p";
    for (std::size_t index = 0; index < path.size(); ++index) {
        if (tag.size() > 1) tag += "_";
        tag += path[index];
    }
    return tag;
}

std::string methodTableName(const ClassDeclaration& owner,
                            const std::vector<std::string>& path) {
    const auto tag = subobjectTag(path, owner);
    return path.empty() ? "@.simp.method.table." + owner.name
                        : "@.simp.method.table." + owner.name + "." + tag;
}

std::string viewMetadataName(const ClassDeclaration& owner,
                             const std::vector<std::string>& path) {
    return path.empty() ? "@.simp.class.meta." + owner.name
                        : "@.simp.view.meta." + owner.name + "." +
                              subobjectTag(path, owner);
}

} // namespace

void CodeGenerator::emitClassTypesAndMetadata(const Program& program) {
    classes_.clear();
    for (const auto& declaration : program.classes) {
        classes_.emplace(declaration.name, &declaration);
    }
    typeDefinitions_ += "%SimpleString = type { ptr, i64 }\n";
    typeDefinitions_ += "%SimpleArrayValue = type { i64, i64, ptr, i64 }\n";
    typeDefinitions_ += "%SimpleArray = type { ptr, i64, [0 x %SimpleArrayValue] }\n";
    typeDefinitions_ += "%SimpRootFrame = type { ptr, i64, ptr }\n";
    typeDefinitions_ += "%SimpleClassMeta = type { ptr, i64, i64, ptr, i64, i64, i64, ptr, ptr }\n";
    typeDefinitions_ += "%SimpleMethodMeta = type { ptr, i64, ptr }\n";
    for (const auto& owner : program.classes) {
        typeDefinitions_ += "%Class." + owner.name + " = type { ptr";
        typeDefinitions_ += ", ptr";
        for (const auto& baseName : owner.baseClassNames) {
            typeDefinitions_ += ", %Class." + baseName;
        }
        const auto virtualBases = virtualBaseNames(owner);
        for (std::size_t index = 0; index < virtualBases.size(); ++index) {
            typeDefinitions_ += ", ptr";
        }
        for (const auto& field : owner.fields) {
            typeDefinitions_ += ", " + llvmType(field.type);
        }
        for (const auto& baseName : virtualBases) {
            typeDefinitions_ += ", %Class." + baseName;
        }
        typeDefinitions_ += " }\n";
    }
    for (const auto& owner : program.classes) {
        const auto className = internString(owner.name);
        std::vector<std::string> referenceOffsets;
        for (const auto& subobject : subobjects(owner)) {
            for (std::size_t localFieldIndex = 0;
                 localFieldIndex < subobject.second->fields.size(); ++localFieldIndex) {
                const auto& field = subobject.second->fields[localFieldIndex];
                const bool dynamic = isDynamicValueType(field.type);
                if (!isManagedReferenceType(field.type) && !dynamic) continue;
                const auto offset = "i64 " + subobjectFieldOffset(
                    owner, subobject.first,
                    fieldIndex(*subobject.second, localFieldIndex), dynamic);
                referenceOffsets.push_back(std::move(offset));
            }
        }
        const auto offsets = "@.simp.reference.offsets." + owner.name;
        if (!referenceOffsets.empty()) {
            metadataGlobals_ += offsets + " = private constant [" +
                                std::to_string(referenceOffsets.size()) + " x i64] [";
            for (std::size_t index = 0; index < referenceOffsets.size(); ++index) {
                if (index != 0) metadataGlobals_ += ", ";
                metadataGlobals_ += referenceOffsets[index];
            }
            metadataGlobals_ += "]\n";
        }
        const auto objectSize = "ptrtoint (ptr getelementptr (%Class." + owner.name +
                               ", ptr null, i32 1) to i64)";
        const auto offsetPointer = referenceOffsets.empty() ? "null" : offsets;
        const auto containsDestructor = [this](const auto& self,
                                               const ClassDeclaration& declaration) -> bool {
            if (std::any_of(declaration.methods.begin(), declaration.methods.end(),
                            [](const MethodDeclaration& method) { return method.destructor; }))
                return true;
            for (const auto& baseName : declaration.baseClassNames) {
                const auto base = classes_.find(baseName);
                if (base != classes_.end() && self(self, *base->second)) return true;
            }
            return false;
        };
        const auto hasDestructor = containsDestructor(containsDestructor, owner);
        for (const auto& view : subobjects(owner)) {
            const auto methods = methodSlots(*view.second);
            const auto table = methodTableName(owner, view.first);
            if (!methods.empty()) {
                metadataGlobals_ += table + " = private constant [" +
                                    std::to_string(methods.size()) +
                                    " x %SimpleMethodMeta] [";
                for (std::size_t index = 0; index < methods.size(); ++index) {
                    if (index != 0) metadataGlobals_ += ", ";
                    const auto methodName = internString(methods[index]->name);
                    const auto thunk = "@simp.thunk." + owner.name + "." +
                                       subobjectTag(view.first, owner) + "." +
                                       std::to_string(index);
                    metadataGlobals_ += "%SimpleMethodMeta { ptr " + methodName +
                                        ", i64 " +
                                        std::to_string(methods[index]->name.size()) +
                                        ", ptr " + thunk + " }";
                }
                metadataGlobals_ += "]\n";
            }
            const auto metadata = viewMetadataName(owner, view.first);
            metadataGlobals_ += metadata + " = private constant %SimpleClassMeta ";
            metadataGlobals_ += "{ ptr " + className + ", i64 " +
                                std::to_string(owner.name.size()) + ", i64 " +
                                std::to_string(flattenedFieldCount(owner)) + ", ptr " +
                                (methods.empty() ? "null" : table) + ", i64 " +
                                std::to_string(methods.size()) + ", i64 " + objectSize +
                                ", i64 " + std::to_string(referenceOffsets.size()) +
                                ", ptr " + offsetPointer + ", ptr " +
                                (hasDestructor ? "@simp.finalize." + owner.name : "null") +
                                " }\n";
        }
    }
}

void CodeGenerator::emitMethod(const ClassDeclaration& owner, const MethodDeclaration& method,
                               const std::string& symbolOverride) {
    currentClass_ = &owner;
    currentFieldClass_ = &owner;
    currentMethod_ = &method;
    scopes_.clear();
    scopes_.emplace_back();
    entryAllocas_.clear();
    functionPrologue_.clear();
    rootSlots_.clear();
    instructions_.clear();
    nextTemporary_ = 0;
    nextVariable_ = 0;
    nextRoot_ = 0;
    nextExceptionFrame_ = 0;
    nextLabel_ = 0;
    blockTerminated_ = false;
    for (const auto& field : owner.fields) {
        std::vector<std::size_t> path;
        (void)findField(owner, field.name, path);
        scopes_.front().emplace(field.name,
                                Binding{field.type, "%this", std::move(path), true, false});
    }
    scopes_.emplace_back();

    std::string signature = "ptr %this";
    if (method.constructor) {
        signature += ", i1 %simp.initialize.virtual.bases";
    }
    const auto thisPointer = "%v" + std::to_string(nextVariable_++);
    entryAllocas_ += "  " + thisPointer + " = alloca ptr\n";
    rootSlots_.push_back(thisPointer);
    functionPrologue_ += "  store ptr %this, ptr " + thisPointer + "\n";
    for (const auto& parameter : method.parameters) {
        const auto argument = "%arg." + parameter.name;
        signature += ", " + llvmType(parameter.type) + " " + argument;
        const auto pointer = "%v" + std::to_string(nextVariable_++);
        scopes_.back().emplace(parameter.name,
                               Binding{parameter.type, pointer, {}, false});
        entryAllocas_ += "  " + pointer + " = alloca " + llvmType(parameter.type) + "\n";
        registerRootSlot(pointer, parameter.type);
        functionPrologue_ += "  store " + llvmType(parameter.type) + " " + argument +
                             ", ptr " + pointer + "\n";
    }
    const auto symbol = symbolOverride.empty() ? methodSymbol(owner.name, method.name)
                                               : symbolOverride;
    const auto returnType = llvmType(method.returnType);
    if (method.constructor) {
        const auto virtualBases = virtualBaseNames(owner);
        if (!virtualBases.empty()) {
            const auto initializeLabel = freshLabel("virtual.initialize");
            const auto endLabel = freshLabel("virtual.initialize.end");
            instructions_ += "  br i1 %simp.initialize.virtual.bases, label %" +
                             initializeLabel + ", label %" + endLabel + "\n" +
                             initializeLabel + ":\n";
            for (const auto& baseName : virtualBases) {
                const auto* base = classes_.at(baseName);
                const MethodDeclaration* constructor = nullptr;
                for (const auto& candidate : base->methods) {
                    if (candidate.constructor) {
                        constructor = &candidate;
                        break;
                    }
                }
                if (constructor == nullptr) continue;
                const Statement* initializer = nullptr;
                for (const auto& candidate : method.body) {
                    if (candidate.kind == StatementKind::SuperConstructorCall &&
                        candidate.virtualBaseInitializer && candidate.name == baseName) {
                        initializer = &candidate;
                        break;
                    }
                }
                const auto basePointer = newTemporary();
                instructions_ += "  " + basePointer +
                                 " = getelementptr inbounds %Class." + owner.name +
                                 ", ptr %this, i32 0, i32 " +
                                 std::to_string(virtualBaseStorageIndex(owner, baseName)) +
                                 "\n";
                std::string arguments = "ptr " + basePointer + ", i1 false";
                if (initializer != nullptr) {
                    for (std::size_t index = 0;
                         index < initializer->expressions.size(); ++index) {
                        const auto value = emitExpression(
                            *initializer->expressions[index],
                            constructor->parameters[index].type);
                        const auto converted = convertObjectValue(
                            value, constructor->parameters[index].type,
                            initializer->expressions[index]->location);
                        arguments += ", " + llvmType(constructor->parameters[index].type) +
                                     " " + converted.operand;
                    }
                }
                instructions_ += "  call void " + methodSymbol(baseName, constructor->name) +
                                 "(" + arguments + ")\n";
            }
            instructions_ += "  br label %" + endLabel + "\n" + endLabel + ":\n";
        }
    }
    emitStatements(method.body);
    if (!blockTerminated_) {
        emitRootFramePop();
        instructions_ += "  ret void\n";
    }
    const auto body = instructions_;
    instructions_ = "define " + returnType + " " + symbol + "(" + signature +
                    ") {\nentry:\n" + entryAllocas_ + rootFrameInitialization() +
                    functionPrologue_ + rootFramePush() + body + "}\n\n";
    currentClass_ = nullptr;
    currentFieldClass_ = nullptr;
    currentMethod_ = nullptr;
}

void CodeGenerator::emitClassMethods(const Program& program) {
    std::string functions;
    std::string finalizers;
    for (const auto& owner : program.classes) {
        for (const auto& method : owner.methods) {
            emitMethod(owner, method);
            functions += instructions_;
        }
    }
    for (const auto& dynamicOwner : program.classes) {
        for (const auto& view : subobjects(dynamicOwner)) {
            const auto slots = methodSlots(*view.second);
            for (std::size_t slotIndex = 0; slotIndex < slots.size(); ++slotIndex) {
                std::vector<std::pair<const ClassDeclaration*, std::vector<std::string>>>
                    candidates{{&dynamicOwner, {}}};
                auto candidatePath = std::vector<std::string>{};
                for (const auto& baseName : view.first) {
                    candidatePath.push_back(baseName);
                    candidates.emplace_back(classes_.at(baseName), candidatePath);
                }
                for (const auto& nested : subobjects(*view.second)) {
                    auto nestedPath = view.first;
                    nestedPath.insert(nestedPath.end(), nested.first.begin(),
                                      nested.first.end());
                    if (nestedPath.empty()) continue;
                    candidates.emplace_back(nested.second, std::move(nestedPath));
                }
                const MethodDeclaration* implementation = nullptr;
                const ClassDeclaration* implementationOwner = nullptr;
                std::vector<std::string> implementationPath;
                for (const auto& candidate : candidates) {
                    for (const auto& method : candidate.first->methods) {
                        if (method.name == slots[slotIndex]->name &&
                            !method.constructor && !method.destructor) {
                            implementation = &method;
                            implementationOwner = candidate.first;
                            implementationPath = candidate.second;
                            break;
                        }
                    }
                    if (implementation != nullptr) break;
                }
                if (implementation == nullptr || implementationOwner == nullptr) continue;
                const auto thunkName = "@simp.thunk." + dynamicOwner.name + "." +
                                       subobjectTag(view.first, dynamicOwner) + "." +
                                       std::to_string(slotIndex);
                const auto returnType = llvmType(implementation->returnType);
                std::string signature = "ptr %this";
                std::string callArguments = "ptr %impl.this";
                for (const auto& parameter : implementation->parameters) {
                    signature += ", " + llvmType(parameter.type) + " %arg." + parameter.name;
                    callArguments += ", " + llvmType(parameter.type) + " %arg." + parameter.name;
                }
                const auto rootAddress = "%root.addr";
                const std::string root = "%root";
                std::string thunk = "define " + returnType + " " + thunkName + "(" +
                                    signature + ") {\nentry:\n"
                                    "  " + rootAddress +
                                    " = getelementptr inbounds %Class." + view.second->name +
                                    ", ptr %this, i32 0, i32 1\n"
                                    "  " + root + " = load ptr, ptr " + rootAddress + "\n";
                if (implementationPath.empty()) {
                    thunk += "  %impl.this = getelementptr i8, ptr " + root + ", i64 0\n";
                } else {
                    std::string implementationAddress;
                    thunk += subobjectAddressSequence(root, dynamicOwner,
                                                      implementationPath, "impl",
                                                      implementationAddress);
                    thunk += "  %impl.this = getelementptr i8, ptr " +
                             implementationAddress + ", i64 0\n";
                }
                if (implementation->returnType == "void") {
                    thunk += "  call void " + methodSymbol(implementationOwner->name,
                                                           implementation->name) +
                             "(" + callArguments + ")\n  ret void\n}\n\n";
                } else {
                    thunk += "  %result = call " + returnType + " " +
                             methodSymbol(implementationOwner->name, implementation->name) +
                             "(" + callArguments + ")\n  ret " + returnType +
                             " %result\n}\n\n";
                }
                functions += thunk;
            }
        }
    }
    for (const auto& dynamicOwner : program.classes) {
        struct DestructorCall {
            const ClassDeclaration* owner;
            const MethodDeclaration* method;
            std::vector<std::string> path;
        };
        std::vector<DestructorCall> chain;
        const auto collectNonVirtual = [this, &chain](
                                           const auto& self,
                                           const ClassDeclaration& declaration,
                                           std::vector<std::string> path) -> void {
            for (const auto& method : declaration.methods) {
                if (method.destructor) chain.push_back({&declaration, &method, path});
            }
            for (std::size_t reverse = declaration.baseClassNames.size(); reverse > 0;
                 --reverse) {
                const auto index = reverse - 1;
                const auto& baseName = declaration.baseClassNames[index];
                const auto found = classes_.find(baseName);
                if (found == classes_.end()) continue;
                if (declaration.baseVirtual[index]) continue;
                auto basePath = path;
                basePath.push_back(baseName);
                self(self, *found->second, std::move(basePath));
            }
        };
        collectNonVirtual(collectNonVirtual, dynamicOwner, {});
        const auto virtualBases = virtualBaseNames(dynamicOwner);
        const auto virtualPath = [this](const ClassDeclaration& owner,
                                        const std::string& target) {
            std::unordered_set<std::string> seen;
            std::vector<std::string> result;
            const auto find = [this, &seen, &target, &result](
                                  const auto& self, const ClassDeclaration& current,
                                  const std::vector<std::string>& path) -> bool {
                for (std::size_t index = 0; index < current.baseClassNames.size(); ++index) {
                    const auto& baseName = current.baseClassNames[index];
                    const auto base = classes_.find(baseName);
                    if (base == classes_.end()) continue;
                    auto nextPath = path;
                    nextPath.push_back(baseName);
                    if (current.baseVirtual[index]) {
                        if (!seen.emplace(baseName).second) continue;
                        if (baseName == target) {
                            result = std::move(nextPath);
                            return true;
                        }
                    }
                    if (self(self, *base->second, nextPath)) return true;
                }
                return false;
            };
            (void)find(find, owner, {});
            return result;
        };
        for (auto baseName = virtualBases.rbegin(); baseName != virtualBases.rend(); ++baseName) {
            const auto found = classes_.find(*baseName);
            if (found == classes_.end()) continue;
            collectNonVirtual(collectNonVirtual, *found->second,
                              virtualPath(dynamicOwner, *baseName));
        }
        if (chain.empty()) continue;
        for (std::size_t index = 0; index < chain.size(); ++index) {
            const auto& call = chain[index];
            const auto symbol = "@simp.destroy." + dynamicOwner.name + "." +
                                std::to_string(index) + "." + call.owner->name;
            emitMethod(*call.owner, *call.method, symbol);
            functions += instructions_;
        }
        std::string finalizerBlocks;
        std::string finalizerAllocas;
        for (std::size_t index = 0; index < chain.size(); ++index) {
            const auto suffix = dynamicOwner.name + "." + std::to_string(index);
            const auto size = "%simp.destroy.size." + suffix;
            const auto frame = "%simp.destroy.frame." + suffix;
            const auto buffer = "%simp.destroy.buffer." + suffix;
            const auto result = "%simp.destroy.result." + suffix;
            const auto normal = "%simp.destroy.normal." + suffix;
            const auto invoke = "destroy.invoke." + suffix;
            const auto caught = "destroy.caught." + suffix;
            const auto keep = "destroy.keep." + suffix;
            const auto discard = "destroy.discard." + suffix;
            const auto next = "destroy.next." + suffix;
            finalizerAllocas += "  " + size + " = call i64 @simp_exception_frame_size()\n"
                                "  " + frame + " = alloca i8, i64 " + size + ", align 16\n";
            std::string objectAddress = "%object";
            if (!chain[index].path.empty()) {
                finalizerAllocas += subobjectAddressSequence(
                    "%object", dynamicOwner, chain[index].path,
                    "destroy." + suffix, objectAddress);
            }
            finalizerBlocks += invoke + ":\n"
                               "  call void @simp_exception_frame_init(ptr " + frame + ")\n"
                               "  " + buffer + " = call ptr @simp_exception_frame_buffer(ptr " +
                               frame + ")\n"
                               "  " + result + " = call i32 @setjmp(ptr " + buffer + ") #0\n"
                               "  " + normal + " = icmp eq i32 " + result + ", 0\n"
                               "  br i1 " + normal + ", label %" + invoke + ".body, label %" +
                               caught + "\n"
                               + invoke + ".body:\n"
                               "  call void @simp_exception_push(ptr " + frame + ")\n"
                               "  call void @simp.destroy." + dynamicOwner.name + "." +
                               std::to_string(index) + "." + chain[index].owner->name +
                               "(ptr " + objectAddress + ")\n"
                               "  call void @simp_exception_pop(ptr " + frame + ")\n"
                               "  br label %" + next + "\n"
                               + caught + ":\n"
                               "  %simp.already.failed." + suffix +
                               " = load i1, ptr %simp.has.exception\n"
                               "  br i1 %simp.already.failed." + suffix + ", label %" + discard +
                               ", label %" + keep + "\n"
                               + keep + ":\n"
                               "  store ptr " + frame + ", ptr %simp.first.exception\n"
                               "  store i1 true, ptr %simp.has.exception\n"
                               "  br label %" + next + "\n"
                               + discard + ":\n"
                               "  call void @simp_exception_clear(ptr " + frame + ")\n"
                               "  br label %" + next + "\n"
                               + next + ":\n";
            if (index + 1 < chain.size()) {
                finalizerBlocks += "  br label %destroy.invoke." + dynamicOwner.name + "." +
                                   std::to_string(index + 1) + "\n";
            }
        }
        finalizers += "define void @simp.finalize." + dynamicOwner.name +
                      "(ptr %object) {\nentry:\n"
                      "  %simp.has.exception = alloca i1\n"
                      "  %simp.first.exception = alloca ptr\n"
                      "  store i1 false, ptr %simp.has.exception\n"
                      "  store ptr null, ptr %simp.first.exception\n" +
                      finalizerAllocas + "  br label %destroy.invoke." +
                      dynamicOwner.name + ".0\n" + finalizerBlocks +
                      "  %simp.any.exception = load i1, ptr %simp.has.exception\n"
                      "  br i1 %simp.any.exception, label %destroy.rethrow, label %destroy.done\n"
                      "destroy.rethrow:\n"
                      "  %simp.saved.frame = load ptr, ptr %simp.first.exception\n"
                      "  call void @simp_exception_rethrow(ptr %simp.saved.frame)\n"
                      "  unreachable\n"
                      "destroy.done:\n"
                      "  ret void\n}\n\n";
    }
    instructions_ = std::move(functions) + std::move(finalizers);
}

void CodeGenerator::emitMain(const Program& program) {
    currentClass_ = nullptr;
    currentFieldClass_ = nullptr;
    currentMethod_ = nullptr;
    scopes_.clear();
    scopes_.emplace_back();
    entryAllocas_.clear();
    functionPrologue_.clear();
    rootSlots_.clear();
    instructions_.clear();
    nextTemporary_ = 0;
    nextVariable_ = 0;
    nextRoot_ = 0;
    nextExceptionFrame_ = 0;
    nextLabel_ = 0;
    blockTerminated_ = false;
    emitStatements(program.statements);
    const auto body = instructions_;
    instructions_ = "define i32 @main() {\nentry:\n" + entryAllocas_ +
                    rootFrameInitialization() + functionPrologue_ + rootFramePush() + body +
                    "  call void @simp_gc_pop_or_abort(ptr %simp.root.frame)\n"
                    "  ret i32 0\n}\n";
}

std::string CodeGenerator::generate(const Program& program) {
    classes_.clear();
    stringGlobals_.clear();
    typeDefinitions_.clear();
    metadataGlobals_.clear();
    instructions_.clear();
    nextString_ = 0;
    emitClassTypesAndMetadata(program);
    emitClassMethods(program);
    const auto methods = instructions_;
    emitMain(program);
    const auto main = instructions_;

    std::ostringstream module;
    module << "source_filename = \"simple\"\n"
           << "target triple = \"" << targetTriple_ << "\"\n\n"
           << typeDefinitions_
           << "@.simp.int.format = private unnamed_addr constant [3 x i8] c\"%d\\00\"\n"
           << "@.simp.null.message = private unnamed_addr constant [14 x i8] c\"null reference\"\n"
           << "@.simp.division.message = private unnamed_addr constant [16 x i8] c\"division by zero\"\n"
           << "@stdout = external global ptr\n"
           << stringGlobals_ << metadataGlobals_ << "\n"
           << "declare i32 @printf(ptr, ...)\n"
           << "declare i64 @fwrite(ptr, i64, i64, ptr)\n"
           << "declare void @simp_gc_push_or_abort(ptr, ptr, i64)\n"
           << "declare void @simp_gc_pop_or_abort(ptr)\n"
           << "declare ptr @simp_gc_alloc(ptr)\n"
           << "declare ptr @simp_gc_alloc_array(i64)\n"
           << "declare ptr @simp_array_index(ptr, i32, ptr, i64, i64, i64)\n"
           << "declare ptr @simp_array_slice(ptr, i32, i32, ptr, i64, i64, i64)\n"
           << "declare void @simp_gc_require_alive(ptr, ptr, i64, i64, i64)\n"
           << "declare void @simp_value_require_tag(i64, i64, ptr, i64, i64, i64)\n"
           << "declare void @simp_value_require_class(i64, ptr, ptr, ptr, i64, i64, i64)\n"
           << "declare void @simp_gc_begin_construction(ptr)\n"
           << "declare void @simp_gc_end_construction(ptr)\n"
           << "declare void @simp_gc_begin_destroy(ptr, ptr, i64, i64, i64)\n"
           << "declare void @simp_gc_end_destroy(ptr)\n"
           << "declare ptr @simp_gc_root(ptr)\n"
           << "declare i64 @simp_exception_frame_size()\n"
           << "declare void @simp_exception_frame_init(ptr)\n"
           << "declare ptr @simp_exception_frame_buffer(ptr)\n"
           << "declare void @simp_exception_push(ptr)\n"
           << "declare void @simp_exception_pop(ptr)\n"
           << "declare void @simp_exception_clear(ptr)\n"
           << "declare ptr @simp_exception_take_message(ptr)\n"
           << "declare i64 @simp_exception_message_length(ptr)\n"
           << "declare void @simp_exception_raise(ptr, i64, ptr, i64, i64, i64) noreturn\n"
           << "declare void @simp_exception_rethrow(ptr) noreturn\n"
           << "declare i32 @setjmp(ptr) returns_twice\n"
           << "declare void @abort()\n\n"
           << "define void @simp.require_nonnull(ptr %object, ptr %file, i64 %file_length, i64 %line, i64 %column) {\n"
           << "entry:\n"
           << "  %isnull = icmp eq ptr %object, null\n"
           << "  br i1 %isnull, label %fail, label %ok\n"
           << "fail:\n"
           << "  call void @simp_exception_raise(ptr @.simp.null.message, i64 14, ptr %file, i64 %file_length, i64 %line, i64 %column)\n"
           << "  unreachable\n"
           << "ok:\n"
           << "  ret void\n"
           << "}\n\n"
           << "attributes #0 = { returns_twice }\n\n"
           << methods << main;
    return module.str();
}

} // namespace simp
