/**
 * @file CodeGenerator.cpp
 * @brief Stable heap-object layout and LLVM IR for the prototype class subset.
 * @author Generated by GitHub Copilot
 */
#include "simp/CodeGenerator.hpp"

#include "simp/Diagnostic.hpp"

#include <algorithm>
#include <sstream>
#include <stdexcept>
#include <utility>

namespace simp {

CodeGenerator::CodeGenerator(std::string targetTriple)
    : targetTriple_(std::move(targetTriple)) {}

[[noreturn]] void CodeGenerator::unsupported(const SourceLocation& location,
                                             const std::string& feature) const {
    throw DiagnosticError(location, feature + " is not supported by the current LLVM backend");
}

std::string CodeGenerator::newTemporary() {
    return "%t" + std::to_string(nextTemporary_++);
}

CodeGenerator::Value CodeGenerator::rootObjectValue(Value value) {
    if (classes_.find(value.type) == classes_.end() || value.operand == "null") {
        return value;
    }
    instructions_ += "  call void @simp_gc_require_alive(ptr " + value.operand + ")\n";
    const auto slot = "%root." + std::to_string(nextRoot_++);
    entryAllocas_ += "  " + slot + " = alloca ptr\n";
    instructions_ += "  store ptr " + value.operand + ", ptr " + slot + "\n";
    rootSlots_.push_back(slot);
    return value;
}

std::string CodeGenerator::freshLabel(const std::string& prefix) {
    return prefix + "." + std::to_string(nextLabel_++);
}

std::string CodeGenerator::llvmType(const std::string& type) const {
    if (type == "int") return "i32";
    if (type == "string") return "%SimpleString";
    if (type == "void") return "void";
    return "ptr";
}

std::string CodeGenerator::methodSymbol(const std::string& className,
                                       const std::string& methodName) const {
    return "@simp." + className + "." + methodName;
}

void CodeGenerator::emitNullCheck(const std::string& pointer) {
    instructions_ += "  call void @simp.require_nonnull(ptr " + pointer + ")\n";
}

CodeGenerator::Value CodeGenerator::emitIntegerExpression(const Expression& expression) {
    if (expression.kind == ExpressionKind::Integer) return {"int", expression.value};
    const auto value = emitExpression(expression);
    if (value.type != "int") {
        throw DiagnosticError(expression.location, "integer expression required");
    }
    return value;
}

std::string CodeGenerator::rootFrameInitialization() const {
    std::ostringstream setup;
    setup << "  %simp.root.frame = alloca %SimpRootFrame\n";
    if (!rootSlots_.empty()) {
        setup << "  %simp.root.slots = alloca [" << rootSlots_.size() << " x ptr]\n";
    }
    for (std::size_t index = 0; index < rootSlots_.size(); ++index) {
        const auto slotAddress = "%simp.root.slot.addr." + std::to_string(index);
        setup << "  store ptr null, ptr " << rootSlots_[index] << "\n"
              << "  " << slotAddress << " = getelementptr inbounds [" << rootSlots_.size()
              << " x ptr], ptr %simp.root.slots, i64 0, i64 " << index << "\n"
              << "  store ptr " << rootSlots_[index] << ", ptr " << slotAddress << "\n";
    }
    return setup.str();
}

std::string CodeGenerator::rootFramePush() const {
    std::ostringstream setup;
    setup << "  call void @simp_gc_push_or_abort(ptr %simp.root.frame, ptr "
          << (rootSlots_.empty() ? "null" : "%simp.root.slots") << ", i64 "
          << rootSlots_.size() << ")\n";
    return setup.str();
}

void CodeGenerator::emitRootFramePop() {
    instructions_ += "  call void @simp_gc_pop_or_abort(ptr %simp.root.frame)\n";
}

CodeGenerator::Value CodeGenerator::emitExpression(const Expression& expression,
                                                   const std::string& expectedType) {
    switch (expression.kind) {
    case ExpressionKind::Integer:
        return {"int", expression.value};
    case ExpressionKind::String: {
        const auto global = internString(expression.value);
        const auto pointer = newTemporary();
        instructions_ += "  " + pointer + ".data = getelementptr inbounds [" +
                         std::to_string(expression.value.size()) + " x i8], ptr " + global +
                         ", i64 0, i64 0\n";
        const auto first = newTemporary();
        const auto result = newTemporary();
        instructions_ += "  " + first + " = insertvalue %SimpleString poison, ptr " + pointer +
                         ".data, 0\n";
        instructions_ += "  " + result + " = insertvalue %SimpleString " + first + ", i64 " +
                         std::to_string(expression.value.size()) + ", 1\n";
        return {"string", result};
    }
    case ExpressionKind::Null:
        return {expectedType, "null"};
    case ExpressionKind::Identifier: {
        const auto binding = findVariable(expression.value, expression.location);
        const auto pointer = emitAddress(binding, expression.location);
        const auto result = newTemporary();
        instructions_ += "  " + result + " = load " + llvmType(binding.type) + ", ptr " +
                         pointer + "\n";
        return rootObjectValue({binding.type, result});
    }
    case ExpressionKind::Member: {
        const Expression* root = nullptr;
        const ClassDeclaration* owner = nullptr;
        std::vector<std::string> basePath;
        const bool qualified =
            resolveBaseQualifier(*expression.left, root, owner, basePath);
        const auto receiver = emitExpression(qualified ? *root : *expression.left);
        if (classes_.find(receiver.type) == classes_.end()) {
            throw DiagnosticError(expression.location, "member receiver is not an object");
        }
        emitNullCheck(receiver.operand);
        if (!qualified) owner = classes_.at(receiver.type);
        std::size_t fieldIndex = 0;
        const auto* field = findField(*owner, expression.value, fieldIndex);
        if (field == nullptr) {
            throw DiagnosticError(expression.location,
                                  "class '" + owner->name + "' has no field '" + expression.value + "'");
        }
        if (qualified) {
            fieldIndex += basePathFieldOffset(*classes_.at(receiver.type), basePath);
        }
        const auto address = newTemporary();
        instructions_ += "  " + address + " = getelementptr inbounds %Class." + receiver.type +
                         ", ptr " + receiver.operand + ", i32 0, i32 " +
                         std::to_string(fieldIndex + 1) + "\n";
        const auto result = newTemporary();
        instructions_ += "  " + result + " = load " + llvmType(field->type) + ", ptr " +
                         address + "\n";
        return rootObjectValue({field->type, result});
    }
    case ExpressionKind::ConstructorCall: {
        const auto found = classes_.find(expression.value);
        if (found == classes_.end()) {
            throw DiagnosticError(expression.location, "unknown class '" + expression.value + "'");
        }
        const auto* owner = found->second;
        const auto object = newTemporary();
        instructions_ += "  " + object + " = call ptr @simp_gc_alloc(ptr @.simp.class.meta." +
                         owner->name + ")\n";
        rootObjectValue({owner->name, object});
        emitNullCheck(object);
        const MethodDeclaration* constructor = nullptr;
        for (const auto& method : owner->methods) {
            if (method.constructor) {
                constructor = &method;
                break;
            }
        }
        if (constructor != nullptr) {
            instructions_ += "  call void @simp_gc_begin_construction(ptr " + object + ")\n";
        }
        for (const auto& method : owner->methods) {
            if (!method.constructor) continue;
            std::string arguments = "ptr " + object;
            for (std::size_t index = 0; index < expression.arguments.size(); ++index) {
                const auto value = emitExpression(*expression.arguments[index],
                                                  method.parameters[index].type);
                arguments += ", " + llvmType(method.parameters[index].type) + " " + value.operand;
            }
            instructions_ += "  call void " + methodSymbol(owner->name, method.name) +
                             "(" + arguments + ")\n";
            instructions_ += "  call void @simp_gc_end_construction(ptr " + object + ")\n";
            break;
        }
        return {owner->name, object};
    }
    case ExpressionKind::Call: {
        if (expression.left->kind != ExpressionKind::Member) {
            throw DiagnosticError(expression.location, "only object method calls are supported");
        }
        const auto& target = *expression.left;
        const Expression* root = nullptr;
        const ClassDeclaration* owner = nullptr;
        std::vector<std::string> basePath;
        const bool qualified = resolveBaseQualifier(*target.left, root, owner, basePath);
        const auto receiver = emitExpression(qualified ? *root : *target.left);
        const auto found = classes_.find(receiver.type);
        if (found == classes_.end()) {
            throw DiagnosticError(target.location, "method receiver is not an object");
        }
        emitNullCheck(receiver.operand);
        if (!qualified) owner = found->second;
        if (target.value == "destroy") {
            if (qualified) {
                throw DiagnosticError(target.location,
                                      "qualified destructor calls are not supported");
            }
            const MethodDeclaration* destructor = nullptr;
            for (const auto& candidate : owner->methods) {
                if (candidate.destructor) {
                    destructor = &candidate;
                    break;
                }
            }
            if (destructor == nullptr) {
                throw DiagnosticError(target.location,
                                      "class '" + owner->name + "' has no destructor");
            }
            instructions_ += "  call void @simp_gc_begin_destroy(ptr " +
                             receiver.operand + ")\n";
            instructions_ += "  call void " + methodSymbol(owner->name, destructor->name) +
                             "(ptr " + receiver.operand + ")\n";
            instructions_ += "  call void @simp_gc_end_destroy(ptr " +
                             receiver.operand + ")\n";
            return {"void", ""};
        }
        const auto* method = findMethod(*owner, target.value);
        if (method == nullptr) {
            throw DiagnosticError(target.location,
                                  "class '" + owner->name + "' has no method '" + target.value + "'");
        }
        std::string arguments = "ptr " + receiver.operand;
        for (std::size_t index = 0; index < expression.arguments.size(); ++index) {
            const auto value = emitExpression(*expression.arguments[index], method->parameters[index].type);
            arguments += ", " + llvmType(method->parameters[index].type) + " " + value.operand;
        }
        const auto metadata = newTemporary();
        instructions_ += "  " + metadata + " = load ptr, ptr " + receiver.operand + "\n";
        const auto tableAddress = newTemporary();
        instructions_ += "  " + tableAddress +
                         " = getelementptr inbounds %SimpleClassMeta, ptr " + metadata +
                         ", i32 0, i32 3\n";
        const auto table = newTemporary();
        instructions_ += "  " + table + " = load ptr, ptr " + tableAddress + "\n";
        const auto entry = newTemporary();
        instructions_ += "  " + entry + " = getelementptr inbounds %SimpleMethodMeta, ptr " +
        table + ", i64 " + std::to_string(methodSlot(*owner, target.value)) +
                         "\n";
        const auto functionAddress = newTemporary();
        instructions_ += "  " + functionAddress +
                         " = getelementptr inbounds %SimpleMethodMeta, ptr " + entry +
                         ", i32 0, i32 2\n";
        const auto function = newTemporary();
        instructions_ += "  " + function + " = load ptr, ptr " + functionAddress + "\n";
        if (method->returnType == "void") {
            instructions_ += "  call void " + function + "(" + arguments + ")\n";
            return {"void", ""};
        }
        const auto result = newTemporary();
        instructions_ += "  " + result + " = call " + llvmType(method->returnType) + " " +
                         function + "(" + arguments + ")\n";
        return rootObjectValue({method->returnType, result});
    }
    case ExpressionKind::Unary: {
        const auto operand = emitIntegerExpression(*expression.left);
        if (expression.value == "+") return operand;
        const auto result = newTemporary();
        if (expression.value == "-") {
            instructions_ += "  " + result + " = sub i32 0, " + operand.operand + "\n";
        } else {
            const auto flag = newTemporary();
            instructions_ += "  " + flag + " = icmp eq i32 " + operand.operand + ", 0\n";
            instructions_ += "  " + result + " = zext i1 " + flag + " to i32\n";
        }
        return {"int", result};
    }
    case ExpressionKind::Binary: {
        const auto left = emitIntegerExpression(*expression.left);
        const auto right = emitIntegerExpression(*expression.right);
        const auto result = newTemporary();
        const auto& operation = expression.value;
        if (operation == "+" || operation == "-" || operation == "*") {
            const char* instruction = operation == "+" ? "add" : operation == "-" ? "sub" : "mul";
            instructions_ += "  " + result + " = " + instruction + " i32 " + left.operand +
                             ", " + right.operand + "\n";
            return {"int", result};
        }
        if (operation == "/" || operation == "%") {
            const auto zero = newTemporary();
            const auto failureLabel = freshLabel("division.zero");
            const auto successLabel = freshLabel("division.ok");
            instructions_ += "  " + zero + " = icmp eq i32 " + right.operand + ", 0\n"
                             "  br i1 " + zero + ", label %" + failureLabel +
                             ", label %" + successLabel + "\n"
                             + failureLabel + ":\n"
                             "  call void @simp_exception_raise(ptr @.simp.division.message, i64 16)\n"
                             "  unreachable\n"
                             + successLabel + ":\n";
            const char* instruction = operation == "/" ? "sdiv" : "srem";
            instructions_ += "  " + result + " = " + instruction + " i32 " + left.operand +
                             ", " + right.operand + "\n";
            return {"int", result};
        }
        std::string predicate;
        if (operation == "==") predicate = "eq";
        else if (operation == "!=") predicate = "ne";
        else if (operation == "<") predicate = "slt";
        else if (operation == "<=") predicate = "sle";
        else if (operation == ">") predicate = "sgt";
        else if (operation == ">=") predicate = "sge";
        else unsupported(expression.location, "operator '" + operation + "'");
        const auto flag = newTemporary();
        instructions_ += "  " + flag + " = icmp " + predicate + " i32 " + left.operand +
                         ", " + right.operand + "\n";
        instructions_ += "  " + result + " = zext i1 " + flag + " to i32\n";
        return {"int", result};
    }
    }
    unsupported(expression.location, "expression");
}

} // namespace simp
