/**
 * @file CodeGeneratorLayout.cpp
 * @brief Object subobject layout and qualified base-path resolution.
 * @author Generated by GitHub Copilot
 */
#include "simp/CodeGenerator.hpp"

#include "simp/Diagnostic.hpp"

#include <algorithm>
#include <limits>
#include <stdexcept>
#include <unordered_set>

namespace simp {

const FieldDeclaration* CodeGenerator::findField(const ClassDeclaration& owner,
                                                  const std::string& name,
                                                  std::vector<std::size_t>& path) const {
    const auto visit = [this, &name](const auto& self, const ClassDeclaration& declaration,
                                     std::vector<std::size_t>& fieldPath)
        -> const FieldDeclaration* {
        for (std::size_t index = 0; index < declaration.baseClassNames.size(); ++index) {
            const auto base = classes_.find(declaration.baseClassNames[index]);
            if (base == classes_.end()) continue;
            if (declaration.baseVirtual[index]) {
                const auto names = virtualBaseNames(declaration);
                const auto slot = static_cast<std::size_t>(std::distance(
                    names.begin(),
                    std::find(names.begin(), names.end(),
                              declaration.baseClassNames[index])));
                fieldPath.push_back(std::numeric_limits<std::size_t>::max() - slot);
            } else {
                fieldPath.push_back(index + 2);
            }
            if (const auto* field = self(self, *base->second, fieldPath)) return field;
            fieldPath.pop_back();
        }
        for (std::size_t index = 0; index < declaration.fields.size(); ++index) {
            if (declaration.fields[index].name == name) {
                fieldPath.push_back(fieldIndex(declaration, index));
                return &declaration.fields[index];
            }
        }
        return nullptr;
    };
    path.clear();
    return visit(visit, owner, path);
}

std::size_t CodeGenerator::flattenedFieldCount(const ClassDeclaration& owner) const {
    std::size_t count = 0;
    std::unordered_set<std::string> virtualSeen;
    const auto visit = [this, &count, &virtualSeen](const auto& self,
                                                   const ClassDeclaration& current) -> void {
        count += current.fields.size();
        for (std::size_t index = 0; index < current.baseClassNames.size(); ++index) {
            const auto& baseName = current.baseClassNames[index];
            const auto base = classes_.find(baseName);
            if (base == classes_.end()) continue;
            if (current.baseVirtual[index] && !virtualSeen.emplace(baseName).second) continue;
            self(self, *base->second);
        }
    };
    visit(visit, owner);
    return count;
}

std::vector<std::string> CodeGenerator::virtualBaseNames(
    const ClassDeclaration& owner) const {
    std::vector<std::string> result;
    std::unordered_set<std::string> seen;
    const auto visit = [this, &result, &seen](const auto& self,
                                              const ClassDeclaration& current) -> void {
        for (std::size_t index = 0; index < current.baseClassNames.size(); ++index) {
            const auto& baseName = current.baseClassNames[index];
            if (current.baseVirtual[index]) {
                if (!seen.emplace(baseName).second) continue;
            }
            const auto base = classes_.find(baseName);
            if (base == classes_.end()) continue;
            self(self, *base->second);
            if (current.baseVirtual[index]) result.push_back(baseName);
        }
    };
    visit(visit, owner);
    return result;
}

std::size_t CodeGenerator::virtualBasePointerIndex(
    const ClassDeclaration& owner, const std::string& baseName) const {
    const auto names = virtualBaseNames(owner);
    const auto found = std::find(names.begin(), names.end(), baseName);
    if (found == names.end()) throw std::logic_error("unknown virtual base slot");
    return owner.baseClassNames.size() + 2 +
           static_cast<std::size_t>(std::distance(names.begin(), found));
}

std::size_t CodeGenerator::virtualBaseStorageIndex(
    const ClassDeclaration& owner, const std::string& baseName) const {
    const auto names = virtualBaseNames(owner);
    const auto found = std::find(names.begin(), names.end(), baseName);
    if (found == names.end()) throw std::logic_error("unknown virtual base storage");
    return owner.baseClassNames.size() + 2 + names.size() + owner.fields.size() +
           static_cast<std::size_t>(std::distance(names.begin(), found));
}

std::size_t CodeGenerator::fieldIndex(const ClassDeclaration& owner,
                                      std::size_t field) const {
    return owner.baseClassNames.size() + 2 + virtualBaseNames(owner).size() + field;
}

std::vector<std::pair<std::vector<std::string>, const ClassDeclaration*>>
CodeGenerator::subobjects(const ClassDeclaration& owner) const {
    std::vector<std::pair<std::vector<std::string>, const ClassDeclaration*>> result;
    std::unordered_set<std::string> virtualSeen;
    const auto visit = [this, &result, &virtualSeen](const auto& self,
                                                     const ClassDeclaration& current,
                                                     std::vector<std::string> path) -> void {
        result.emplace_back(path, &current);
        for (std::size_t index = 0; index < current.baseClassNames.size(); ++index) {
            const auto& baseName = current.baseClassNames[index];
            const auto base = classes_.find(baseName);
            if (base == classes_.end()) continue;
            auto basePath = path;
            basePath.push_back(baseName);
            if (current.baseVirtual[index]) {
                if (virtualSeen.emplace(baseName).second) {
                    self(self, *base->second, std::move(basePath));
                }
            } else {
                self(self, *base->second, std::move(basePath));
            }
        }
    };
    visit(visit, owner, {});
    return result;
}

std::string CodeGenerator::emitFieldAddress(
    const std::string& pointer, const ClassDeclaration& owner,
    const std::vector<std::size_t>& path) {
    std::string address = pointer;
    const ClassDeclaration* current = &owner;
    for (const auto index : path) {
        const auto virtualNames = virtualBaseNames(*current);
        if (index >= std::numeric_limits<std::size_t>::max() - virtualNames.size()) {
            const auto slot = std::numeric_limits<std::size_t>::max() - index;
            if (slot >= virtualNames.size()) throw std::logic_error("invalid virtual field path");
            const auto slotAddress = newTemporary();
            instructions_ += "  " + slotAddress + " = getelementptr inbounds %Class." +
                             current->name + ", ptr " + address + ", i32 0, i32 " +
                             std::to_string(virtualBasePointerIndex(*current, virtualNames[slot])) +
                             "\n";
            const auto loaded = newTemporary();
            instructions_ += "  " + loaded + " = load ptr, ptr " + slotAddress + "\n";
            address = loaded;
            current = classes_.at(virtualNames[slot]);
            continue;
        }
        if (index >= 2 && index < current->baseClassNames.size() + 2) {
            const auto baseIndex = index - 2;
            const auto next = newTemporary();
            instructions_ += "  " + next + " = getelementptr inbounds %Class." +
                             current->name + ", ptr " + address + ", i32 0, i32 " +
                             std::to_string(index) + "\n";
            address = next;
            current = classes_.at(current->baseClassNames[baseIndex]);
            continue;
        }
        const auto field = newTemporary();
        instructions_ += "  " + field + " = getelementptr inbounds %Class." +
                         current->name + ", ptr " + address + ", i32 0, i32 " +
                         std::to_string(index) + "\n";
        return field;
    }
    throw std::logic_error("field path has no field index");
}

std::string CodeGenerator::emitSubobjectAddress(
    const std::string& pointer, const ClassDeclaration& owner,
    const std::vector<std::string>& path) {
    if (path.empty()) return pointer;
    std::string address;
    const auto prefix = newTemporary();
    instructions_ += subobjectAddressSequence(pointer, owner, path, prefix.substr(1), address);
    return address;
}

std::string CodeGenerator::subobjectAddressSequence(
    const std::string& pointer, const ClassDeclaration& owner,
    const std::vector<std::string>& path, const std::string& temporaryPrefix,
    std::string& address) const {
    address = pointer;
    std::string code;
    const ClassDeclaration* current = &owner;
    for (std::size_t step = 0; step < path.size(); ++step) {
        const auto found = std::find(current->baseClassNames.begin(),
                                     current->baseClassNames.end(), path[step]);
        if (found == current->baseClassNames.end()) {
            throw std::logic_error("invalid qualified base path");
        }
        const auto baseIndex = static_cast<std::size_t>(
            std::distance(current->baseClassNames.begin(), found));
        const auto result = "%" + temporaryPrefix + ".addr." + std::to_string(step);
        if (current->baseVirtual[baseIndex]) {
            const auto slot = "%" + temporaryPrefix + ".slot." + std::to_string(step);
            code += "  " + slot + " = getelementptr inbounds %Class." + current->name +
                    ", ptr " + address + ", i32 0, i32 " +
                    std::to_string(virtualBasePointerIndex(*current, path[step])) + "\n"
                    "  " + result + " = load ptr, ptr " + slot + "\n";
            address = result;
        } else {
            code += "  " + result + " = getelementptr inbounds %Class." + current->name +
                    ", ptr " + address + ", i32 0, i32 " +
                    std::to_string(baseIndex + 2) + "\n";
            address = result;
        }
        current = classes_.at(path[step]);
    }
    return code;
}

std::string CodeGenerator::subobjectFieldOffset(
    const ClassDeclaration& owner, const std::vector<std::string>& path,
    std::size_t field, bool dynamicPointerSubfield) const {
    const ClassDeclaration* current = &owner;
    const ClassDeclaration* segment = &owner;
    std::vector<std::size_t> indices;
    std::string rootOffset;
    const auto offsetExpression = [&indices](const ClassDeclaration& type) {
        std::string expression = "ptrtoint (ptr getelementptr (%Class." + type.name +
                                 ", ptr null, i32 0";
        for (const auto index : indices) {
            expression += ", i32 " + std::to_string(index);
        }
        expression += ") to i64)";
        return expression;
    };
    for (const auto& baseName : path) {
        const auto found = std::find(current->baseClassNames.begin(),
                                     current->baseClassNames.end(), baseName);
        if (found == current->baseClassNames.end()) {
            throw std::logic_error("invalid qualified base path");
        }
        const auto baseIndex = static_cast<std::size_t>(
            std::distance(current->baseClassNames.begin(), found));
        if (current->baseVirtual[baseIndex]) {
            rootOffset = "ptrtoint (ptr getelementptr (%Class." + owner.name +
                         ", ptr null, i32 0, i32 " +
                         std::to_string(virtualBaseStorageIndex(owner, baseName)) +
                         ") to i64)";
            segment = classes_.at(baseName);
            indices.clear();
        } else {
            indices.push_back(baseIndex + 2);
        }
        current = classes_.at(baseName);
    }
    indices.push_back(field);
    // A field of type 'any' is stored as %SimpleArrayValue { tag, integer, pointer,
    // length }; only its third machine word (the pointer sub-field) can hold a
    // traceable GC reference, so the metadata records that sub-field's offset
    // instead of the aggregate's start.
    if (dynamicPointerSubfield) {
        indices.push_back(2);
    }
    const auto localOffset = offsetExpression(*segment);
    if (rootOffset.empty()) return localOffset;
    return "add (i64 " + rootOffset + ", i64 " + localOffset + ")";
}

std::string CodeGenerator::viewMetadataSymbol(
    const ClassDeclaration& owner, const std::vector<std::string>& path) const {
    std::string symbol = "@.simp.view.meta." + owner.name + ".p";
    for (std::size_t index = 0; index < path.size(); ++index) {
        if (index != 0) symbol += "_";
        symbol += path[index];
    }
    return symbol;
}

bool CodeGenerator::resolveBaseQualifier(const Expression& receiver,
                                         const Expression*& root,
                                         const ClassDeclaration*& view,
                                         std::vector<std::string>& path) const {
    std::vector<std::string> reversed;
    const Expression* cursor = &receiver;
    while (cursor->kind == ExpressionKind::Member) {
        reversed.push_back(cursor->value);
        cursor = cursor->left.get();
    }
    if (reversed.empty() ||
        (cursor->kind != ExpressionKind::Identifier &&
         cursor->kind != ExpressionKind::ObjectCast &&
         cursor->kind != ExpressionKind::ImplicitThis)) return false;
    const auto rootType = cursor->kind == ExpressionKind::ImplicitThis
        ? currentClass_->name : cursor->kind == ExpressionKind::ObjectCast
        ? cursor->value : findVariable(cursor->value, cursor->location).type;
    const auto owner = classes_.find(rootType);
    if (owner == classes_.end()) return false;
    root = cursor;
    view = owner->second;
    for (auto name = reversed.rbegin(); name != reversed.rend(); ++name) {
        if (std::find(view->baseClassNames.begin(), view->baseClassNames.end(), *name) ==
            view->baseClassNames.end()) {
            return false;
        }
        const auto base = classes_.find(*name);
        if (base == classes_.end()) return false;
        path.push_back(*name);
        view = base->second;
    }
    return true;
}

CodeGenerator::Binding CodeGenerator::findVariable(const std::string& name,
                                                   const SourceLocation& location) const {
    for (auto scope = scopes_.rbegin(); scope != scopes_.rend(); ++scope) {
        const auto found = scope->find(name);
        if (found != scope->end()) return found->second;
    }
    if (currentFieldClass_ != nullptr) {
        std::vector<std::size_t> path;
        if (const auto* field = findField(*currentFieldClass_, name, path)) {
            return {field->type, "%this", std::move(path), true};
        }
    }
    throw DiagnosticError(location, "backend could not resolve variable or field '" + name + "'");
}

std::string CodeGenerator::emitAddress(const Binding& binding, const SourceLocation& location) {
    if (!binding.field) return binding.pointer;
    (void)location;
    return emitFieldAddress("%this", *currentFieldClass_, binding.fieldPath);
}

CodeGenerator::Binding CodeGenerator::emitFieldBinding(const Expression& target) {
    const Expression* root = nullptr;
    const ClassDeclaration* owner = nullptr;
    std::vector<std::string> basePath;
    const bool qualified = resolveBaseQualifier(*target.left, root, owner, basePath);
    auto receiver = emitExpression(qualified ? *root : *target.left);
    emitNullCheck(receiver.operand, target.location);
    if (!qualified) {
        owner = classes_.at(receiver.type);
    } else {
        receiver = {owner->name,
                    emitSubobjectAddress(receiver.operand, *classes_.at(receiver.type), basePath)};
    }
    std::vector<std::size_t> fieldPath;
    const auto* field = findField(*owner, target.value, fieldPath);
    if (field == nullptr) {
        throw DiagnosticError(target.location, "backend could not resolve field");
    }
    return {field->type, emitFieldAddress(receiver.operand, *owner, fieldPath), {}};
}

CodeGenerator::Value CodeGenerator::convertObjectValue(
    Value value, const std::string& expectedType, const SourceLocation& location) {
    if (value.operand == "null") {
        if (expectedType == "any") {
            return buildDynamicValue({"null", "null"}, location);
        }
        if (isNullableScalarType(expectedType)) {
            const auto zero = expectedType == "float" ? "0.0" : "0";
            return {expectedType, zero, "1"};
        }
        value.type = expectedType;
        return value;
    }
    if (value.type == expectedType) {
        return value;
    }
    if (expectedType == "any") {
        return buildDynamicValue(value, location);
    }
    if (value.type == "any") {
        return extractTypedValue(value, expectedType, location);
    }
    if (classes_.find(value.type) == classes_.end() ||
        classes_.find(expectedType) == classes_.end()) {
        return value;
    }
    const auto& owner = *classes_.at(value.type);
    std::vector<std::string> path;
    const auto findPath = [this, &expectedType](const auto& self,
                                                const ClassDeclaration& current,
                                                std::vector<std::string>& candidate)
        -> bool {
        for (const auto& baseName : current.baseClassNames) {
            candidate.push_back(baseName);
            if (baseName == expectedType) return true;
            if (self(self, *classes_.at(baseName), candidate)) return true;
            candidate.pop_back();
        }
        return false;
    };
    if (!findPath(findPath, owner, path)) {
        throw DiagnosticError(location, "backend could not find the required base subobject");
    }
    const auto address = emitSubobjectAddress(value.operand, owner, path);
    const auto isNull = newTemporary();
    const auto convertedAddress = newTemporary();
    instructions_ += "  " + isNull + " = icmp eq ptr " + value.operand + ", null\n"
                     "  " + convertedAddress + " = select i1 " + isNull + ", ptr null, ptr " +
                     address + "\n";
    return {expectedType, convertedAddress};
}

} // namespace simp
