/**
 * @file Lexer.cpp
 * @brief Tokenization of the documented Simple prototype subset.
 * @author Generated by GitHub Copilot
 */
#include "simp/Lexer.hpp"

#include "simp/Diagnostic.hpp"

#include <cctype>
#include <unordered_map>
#include <utility>

namespace simp {
namespace {

char lowerAscii(char value) {
    if (value >= 'A' && value <= 'Z') {
        return static_cast<char>(value - 'A' + 'a');
    }
    return value;
}

bool isIdentifierStart(char value) {
    return (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || value == '_';
}

bool isIdentifierPart(char value) {
    return isIdentifierStart(value) || (value >= '0' && value <= '9');
}

} // namespace

const char* tokenTypeName(TokenType type) noexcept {
    switch (type) {
    case TokenType::End: return "end of file";
    case TokenType::Identifier: return "identifier";
    case TokenType::Integer: return "integer";
    case TokenType::String: return "string";
    case TokenType::Start: return "'start'";
    case TokenType::Int: return "'int'";
    case TokenType::StringType: return "'string'";
    case TokenType::If: return "'if'";
    case TokenType::Else: return "'else'";
    case TokenType::While: return "'while'";
    case TokenType::Print: return "'print'";
    case TokenType::LeftBrace: return "'{'";
    case TokenType::RightBrace: return "'}'";
    case TokenType::LeftParen: return "'('";
    case TokenType::RightParen: return "')'";
    case TokenType::Comma: return "','";
    case TokenType::Semicolon: return "';'";
    case TokenType::Plus: return "'+'";
    case TokenType::Minus: return "'-'";
    case TokenType::Star: return "'*'";
    case TokenType::Slash: return "'/'";
    case TokenType::Percent: return "'%'";
    case TokenType::Bang: return "'!'";
    case TokenType::Equal: return "'='";
    case TokenType::EqualEqual: return "'=='";
    case TokenType::BangEqual: return "'!='";
    case TokenType::Less: return "'<'";
    case TokenType::LessEqual: return "'<='";
    case TokenType::Greater: return "'>'";
    case TokenType::GreaterEqual: return "'>='";
    }
    return "token";
}

Lexer::Lexer(std::string source, std::string fileName)
    : source_(std::move(source)), fileName_(std::move(fileName)) {}

bool Lexer::atEnd() const noexcept {
    return position_ >= source_.size();
}

char Lexer::peek(std::size_t offset) const noexcept {
    const auto index = position_ + offset;
    return index < source_.size() ? source_[index] : '\0';
}

char Lexer::advance() noexcept {
    const char value = source_[position_++];
    if (value == '\n') {
        ++line_;
        column_ = 1;
    } else {
        ++column_;
    }
    return value;
}

SourceLocation Lexer::currentLocation() const {
    return {fileName_, line_, column_};
}

Token Lexer::makeToken(TokenType type, std::string text, SourceLocation location,
                       bool formattedString) const {
    return {type, std::move(text), std::move(location), formattedString};
}

void Lexer::skipTrivia() {
    for (;;) {
        while (!atEnd() && std::isspace(static_cast<unsigned char>(peek())) != 0) {
            advance();
        }
        if (peek() != '/' || peek(1) != '/') {
            return;
        }
        while (!atEnd() && peek() != '\n') {
            advance();
        }
    }
}

Token Lexer::scanIdentifierOrInteger() {
    const auto location = currentLocation();
    const bool integer = peek() >= '0' && peek() <= '9';
    std::string text;
    while (integer ? (peek() >= '0' && peek() <= '9') : isIdentifierPart(peek())) {
        text.push_back(advance());
    }
    if (integer) {
        return makeToken(TokenType::Integer, std::move(text), location);
    }

    std::string normalized;
    normalized.reserve(text.size());
    for (char value : text) {
        normalized.push_back(lowerAscii(value));
    }
    static const std::unordered_map<std::string, TokenType> keywords{
        {"start", TokenType::Start}, {"int", TokenType::Int},
        {"string", TokenType::StringType}, {"if", TokenType::If},
        {"else", TokenType::Else}, {"while", TokenType::While},
        {"print", TokenType::Print}
    };
    const auto found = keywords.find(normalized);
    return makeToken(found == keywords.end() ? TokenType::Identifier : found->second,
                     std::move(text), location);
}

Token Lexer::scanString(char quote, SourceLocation location) {
    advance();
    std::string value;
    while (!atEnd() && peek() != quote) {
        if (peek() == '\n' || peek() == '\r') {
            throw DiagnosticError(currentLocation(), "newline in string literal");
        }
        if (quote == '"' && peek() == '\\') {
            advance();
            if (atEnd()) {
                throw DiagnosticError(location, "unterminated escape sequence");
            }
            const char escaped = advance();
            switch (escaped) {
            case 'n': value.push_back('\n'); break;
            case 'r': value.push_back('\r'); break;
            case 't': value.push_back('\t'); break;
            case '\\': value.push_back('\\'); break;
            case '"': value.push_back('"'); break;
            default:
                throw DiagnosticError(currentLocation(), "unsupported string escape");
            }
        } else {
            value.push_back(advance());
        }
    }
    if (atEnd()) {
        throw DiagnosticError(location, "unterminated string literal");
    }
    advance();
    return makeToken(TokenType::String, std::move(value), std::move(location), quote == '"');
}

std::vector<Token> Lexer::tokenize() {
    std::vector<Token> tokens;
    while (!atEnd()) {
        skipTrivia();
        if (atEnd()) {
            break;
        }
        const auto location = currentLocation();
        const char value = peek();
        if (isIdentifierStart(value) || (value >= '0' && value <= '9')) {
            tokens.push_back(scanIdentifierOrInteger());
            continue;
        }
        if (value == '"' || value == '\'') {
            tokens.push_back(scanString(value, location));
            continue;
        }

        advance();
        TokenType type;
        switch (value) {
        case '{': type = TokenType::LeftBrace; break;
        case '}': type = TokenType::RightBrace; break;
        case '(': type = TokenType::LeftParen; break;
        case ')': type = TokenType::RightParen; break;
        case ',': type = TokenType::Comma; break;
        case ';': type = TokenType::Semicolon; break;
        case '+': type = TokenType::Plus; break;
        case '-': type = TokenType::Minus; break;
        case '*': type = TokenType::Star; break;
        case '/': type = TokenType::Slash; break;
        case '%': type = TokenType::Percent; break;
        case '!':
            type = peek() == '=' ? (advance(), TokenType::BangEqual) : TokenType::Bang;
            break;
        case '=':
            type = peek() == '=' ? (advance(), TokenType::EqualEqual) : TokenType::Equal;
            break;
        case '<':
            type = peek() == '=' ? (advance(), TokenType::LessEqual) : TokenType::Less;
            break;
        case '>':
            type = peek() == '=' ? (advance(), TokenType::GreaterEqual) : TokenType::Greater;
            break;
        default:
            throw DiagnosticError(location, "unexpected character");
        }
        std::string text(1, value);
        if (type == TokenType::BangEqual || type == TokenType::EqualEqual ||
            type == TokenType::LessEqual || type == TokenType::GreaterEqual) {
            text.push_back('=');
        }
        tokens.push_back(makeToken(type, std::move(text), location));
    }
    tokens.push_back(makeToken(TokenType::End, "", currentLocation()));
    return tokens;
}

} // namespace simp
