/**
 * @file main.cpp
 * @brief Command-line driver for the Simple front-end prototype.
 * @author Generated by GitHub Copilot
 */
#include "simp/Ast.hpp"
#include "simp/CodeGenerator.hpp"
#include "simp/Diagnostic.hpp"
#include "simp/ModuleRegistry.hpp"
#include "simp/Parser.hpp"
#include "simp/SemanticAnalyzer.hpp"
#include "simp/SourceLoader.hpp"

#include <cstdlib>
#include <charconv>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <string>
#include <system_error>
#include <unordered_set>
#include <vector>

#include <sys/wait.h>

namespace {

void printUsage(std::ostream& output) {
    output << "Usage: simp [--verbose] [--trace-parser] [--dump-ast] [--dump-symbols] "
              "[--check-only] [--max-include-depth N] [--emit-llvm FILE] [-o FILE] "
              "<source.simp>\n";
}

std::string shellQuote(const std::string& value) {
    std::string quoted = "'";
    for (const char character : value) {
        if (character == '\'') {
            quoted += "'\\''";
        } else {
            quoted.push_back(character);
        }
    }
    quoted.push_back('\'');
    return quoted;
}

void writeFile(const std::string& path, const std::string& contents) {
    const std::filesystem::path destination(path);
    if (!destination.parent_path().empty()) {
        std::filesystem::create_directories(destination.parent_path());
    }
    std::ofstream output(path);
    if (!output) {
        throw std::runtime_error("cannot write generated file: " + path);
    }
    output << contents;
    if (!output) {
        throw std::runtime_error("failed while writing generated file: " + path);
    }
}

std::string defaultExecutablePath(const std::string& inputPath) {
    auto name = std::filesystem::path(inputPath).stem().string();
    if (name.empty()) name = "a.out";
    return (std::filesystem::path(".") / name).string();
}

int buildExecutable(const std::vector<std::string>& irPaths,
                    const std::string& inlineShimPath, const std::string& outputPath) {
    const auto parent = std::filesystem::path(outputPath).parent_path();
    if (!parent.empty()) {
        std::filesystem::create_directories(parent);
    }
    std::string command = shellQuote(SIMP_CLANG_EXECUTABLE) + " -Wno-override-module";
    for (const auto& irPath : irPaths) {
        command += " -x ir " + shellQuote(irPath);
    }
    command += " -x none " + shellQuote(SIMP_GC_RUNTIME_LIBRARY) +
               (inlineShimPath.empty()
                    ? ""
                    : " -I " + shellQuote(SIMP_RUNTIME_INCLUDE_DIRECTORY) +
                          " -x c " + shellQuote(inlineShimPath)) +
               " -pthread -o " + shellQuote(outputPath);
    const int status = std::system(command.c_str());
    if (status == -1) {
        std::cerr << "simp: could not start clang\n";
        return 1;
    }
    if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
        const int exitCode = WIFEXITED(status) ? WEXITSTATUS(status) : 128;
        std::cerr << "simp: clang failed to compile generated LLVM IR (exit status "
                  << exitCode << ")\n";
        return 1;
    }
    return 0;
}

} // namespace

int main(int argc, char** argv) {
    bool verbose = false;
    bool traceParser = false;
    bool dump = false;
    bool dumpSymbols = false;
    bool checkOnly = false;
    std::string requestedOutput;
    std::string irOutput;
    std::string inputPath;
    std::size_t maximumIncludeDepth = 16;

    for (int index = 1; index < argc; ++index) {
        const std::string argument = argv[index];
        if (argument == "--help" || argument == "-h") {
            printUsage(std::cout);
            return 0;
        }
        if (argument == "--verbose" || argument == "-v") {
            verbose = true;
        } else if (argument == "--trace-parser") {
            traceParser = true;
        } else if (argument == "--dump-ast") {
            dump = true;
        } else if (argument == "--dump-symbols") {
            dumpSymbols = true;
        } else if (argument == "--check-only") {
            checkOnly = true;
        } else if (argument == "--max-include-depth") {
            if (index + 1 >= argc) {
                std::cerr << "simp: --max-include-depth requires a non-negative integer\n";
                return 2;
            }
            const std::string value = argv[++index];
            std::size_t parsed = 0;
            const auto result = std::from_chars(value.data(), value.data() + value.size(), parsed);
            if (result.ec != std::errc{} || result.ptr != value.data() + value.size()) {
                std::cerr << "simp: --max-include-depth requires a non-negative integer\n";
                return 2;
            }
            maximumIncludeDepth = parsed;
        } else if (argument == "-o" || argument == "--emit-llvm") {
            if (index + 1 >= argc) {
                std::cerr << "simp: " << argument << " requires a file path\n";
                return 2;
            }
            if (argument == "-o") {
                requestedOutput = argv[++index];
            } else {
                irOutput = argv[++index];
            }
        } else if (!argument.empty() && argument.front() == '-') {
            std::cerr << "simp: unknown option: " << argument << '\n';
            printUsage(std::cerr);
            return 2;
        } else if (inputPath.empty()) {
            inputPath = argument;
        } else {
            std::cerr << "simp: only one input file is supported in this prototype\n";
            return 2;
        }
    }

    if (inputPath.empty()) {
        printUsage(std::cerr);
        return 2;
    }
    std::ifstream input(inputPath);
    if (!input) {
        std::cerr << "simp: cannot open input file: " << inputPath << '\n';
        return 2;
    }
    const std::string source((std::istreambuf_iterator<char>(input)),
                             std::istreambuf_iterator<char>());

    std::vector<std::string> temporaryIrPaths;
    try {
        std::unordered_set<std::string> includedFiles;
        std::error_code pathError;
        const auto canonicalInput = std::filesystem::canonical(inputPath, pathError);
        if (pathError) {
            std::cerr << "simp: cannot resolve input file: " << inputPath << '\n';
            return 2;
        }
        includedFiles.insert(canonicalInput.string());
        auto tokens = simp::tokenizeWithIncludes(
            source, inputPath, includedFiles, 0, true, maximumIncludeDepth);
        tokens.push_back({simp::TokenType::End, "", {inputPath, 1, 1}});
        if (verbose) {
            std::cerr << "[verbose] lexed " << (tokens.size() - 1) << " tokens\n";
        }
        simp::Parser parser(std::move(tokens), traceParser ? &std::cerr : nullptr);
        auto program = parser.parseProgram();
        const auto* configuredRegistry = std::getenv("SIMP_MODULE_REGISTRY");
        const auto registryPath = configuredRegistry == nullptr
                                      ? std::filesystem::current_path() / "simp-modules.tsv"
                                      : std::filesystem::path(configuredRegistry);
        const auto modules = simp::loadImportedModules(program, registryPath);
        simp::SemanticAnalyzer semanticAnalyzer;
        semanticAnalyzer.analyze(program);
        if (dump) {
            simp::dumpAst(program, std::cout);
        }
        if (dumpSymbols) {
            semanticAnalyzer.dumpSymbolTable(std::cout);
        }
        if (checkOnly) {
            if (verbose) {
                std::cerr << "[verbose] semantic analysis succeeded; code generation skipped\n";
            }
            return 0;
        }

        const auto outputPath = requestedOutput.empty()
                                    ? defaultExecutablePath(inputPath)
                                    : requestedOutput;
        simp::CodeGenerator codeGenerator(SIMP_TARGET_TRIPLE);
        const auto ir = codeGenerator.generate(program);
        std::unordered_map<std::string, std::string> inlineShims;
        for (const auto& shim : codeGenerator.inlineShims()) {
            inlineShims.emplace(shim.first, shim.second);
        }
        std::vector<std::string> moduleIrPaths;
        for (const auto& module : modules) {
            simp::CodeGenerator moduleGenerator(SIMP_TARGET_TRIPLE);
            const auto moduleIr = moduleGenerator.generate(program, module.name);
            for (const auto& shim : moduleGenerator.inlineShims()) {
                inlineShims.emplace(shim.first, shim.second);
            }
            const auto moduleIrPath = outputPath + ".simp.module." +
                                      std::to_string(moduleIrPaths.size()) + ".tmp.ll";
            writeFile(moduleIrPath, moduleIr);
            temporaryIrPaths.push_back(moduleIrPath);
            moduleIrPaths.push_back(moduleIrPath);
        }
        std::vector<std::string> linkInputs;
        if (irOutput.empty()) {
            const auto importerIrPath = outputPath + ".simp.tmp.ll";
            writeFile(importerIrPath, ir);
            temporaryIrPaths.push_back(importerIrPath);
            linkInputs.push_back(importerIrPath);
        } else {
            writeFile(irOutput, ir);
            linkInputs.push_back(irOutput);
        }
        linkInputs.insert(linkInputs.end(), moduleIrPaths.begin(), moduleIrPaths.end());
        std::string inlineShimPath;
        if (!inlineShims.empty()) {
            inlineShimPath = outputPath + ".simp.inline.tmp.c";
            std::string source = "#include \"simp/RuntimeGc.h\"\n#include <stdio.h>\n\n";
            for (const auto& shim : inlineShims) {
                source += shim.second;
                source += '\n';
            }
            writeFile(inlineShimPath, source);
            temporaryIrPaths.push_back(inlineShimPath);
        }
        const int buildResult = buildExecutable(linkInputs, inlineShimPath, outputPath);
        for (const auto& temporary : temporaryIrPaths) {
            std::error_code ignored;
            std::filesystem::remove(temporary, ignored);
        }
        if (buildResult != 0) return 1;
        if (verbose) {
            std::cerr << "[verbose] semantic analysis succeeded; LLVM IR compiled by clang\n";
        } else if (!dump && !dumpSymbols) {
            std::cout << "simp: built " << outputPath << '\n';
        }
    } catch (const simp::DiagnosticError& diagnostic) {
        std::cerr << diagnostic.what() << '\n';
        return 1;
    } catch (const std::exception& error) {
        std::cerr << "simp: " << error.what() << '\n';
        for (const auto& temporary : temporaryIrPaths) {
            std::error_code ignored;
            std::filesystem::remove(temporary, ignored);
        }
        return 1;
    }
    return 0;
}
