/**
 * @file RuntimeThreads.c
 * @brief pthread-backed Thread/Semaphore native bindings.
 * @author Generated by GitHub Copilot
 *
 * See RuntimeThreads.h for the Simple-side declarations these symbols are
 * meant to be bound to, and "Threads" in SIMPLE-LANGUAGE-NOTES.md for the
 * cooperative global-lock design these functions participate in via
 * simp_runtime_thread_enter/exit and simp_runtime_gil_release/acquire.
 */
#include "simp/RuntimeThreads.h"

#include <pthread.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>

extern void simp_runtime_set_error(int error_number);
extern void simp_runtime_clear_error(void);

typedef struct SimpThreadHandle {
    pthread_t thread;
} SimpThreadHandle;

typedef struct SimpThreadStartArgs {
    void *receiver;
    void (*run_thunk)(void *);
    pthread_mutex_t ready_mutex;
    pthread_cond_t ready_cond;
    int ready;
} SimpThreadStartArgs;

typedef struct SimpSemaphoreObject {
    pthread_mutex_t mutex;
    pthread_cond_t cond;
    int64_t count;
} SimpSemaphoreObject;

typedef struct SimpMutexObject {
    pthread_mutex_t guard;
    pthread_cond_t available;
    pthread_t owner;
    int locked;
    int64_t waiters;
} SimpMutexObject;

typedef struct SimpConditionObject {
    pthread_mutex_t guard;
    pthread_cond_t condition;
    uint64_t sequence;
    int64_t waiters;
} SimpConditionObject;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
static void (*find_run_method(const SimpClassMeta *metadata))(void *) {
    if (metadata == NULL) return NULL;
    for (uint64_t index = 0; index < metadata->method_count; ++index) {
        const SimpMethodMeta *candidate = &metadata->methods[index];
        if (candidate->name_length == 3 &&
            memcmp(candidate->name, "run", 3) == 0) {
            return (void (*)(void *))candidate->code;
        }
    }
    return NULL;
}
#pragma GCC diagnostic pop

static void *simp_thread_trampoline(void *raw_args) {
    SimpThreadStartArgs *args = (SimpThreadStartArgs *)raw_args;
    void *receiver = args->receiver;
    void (*run_thunk)(void *) = args->run_thunk;

    /* Registers this OS thread with the collector and acquires the global
     * lock (see simp_runtime_thread_enter's doc comment): from this point
     * on this thread is a full participant in the single-lock threading
     * model and may safely run Simple code / touch the managed heap. */
    simp_runtime_thread_enter();
    SimpRootFrame frame = {0};
    void *const slots[1] = {&receiver};
    simp_gc_push_or_abort(&frame, slots, 1);

    /* Hand off root-protection of the receiver to this thread's own frame
     * before signaling the spawner, so there is never a window where
     * neither thread's root frame protects it (see simp_thread_start). */
    pthread_mutex_lock(&args->ready_mutex);
    args->ready = 1;
    pthread_cond_signal(&args->ready_cond);
    pthread_mutex_unlock(&args->ready_mutex);

    run_thunk(receiver);

    simp_gc_pop_or_abort(&frame);
    simp_runtime_thread_exit();
    return NULL;
}

void *simp_thread_start(void *receiver) {
    if (receiver == NULL) abort();
    /* `receiver` is whatever subobject view the compiler passed for this
     * (statically Thread-typed) call; its own metadata field only lists
     * Thread's own declared methods. simp_gc_root resolves to the true,
     * most-derived allocated object, whose metadata table is the merged
     * vtable that actually includes the subclass's "run" method. */
    void *root = simp_gc_root(receiver);
    const SimpClassMeta *metadata = *(const SimpClassMeta *const *)root;
    void (*run_thunk)(void *) = find_run_method(metadata);
    if (run_thunk == NULL) abort();

    SimpThreadStartArgs *args = (SimpThreadStartArgs *)malloc(sizeof(*args));
    if (args == NULL) abort();
    args->receiver = root;
    args->run_thunk = run_thunk;
    args->ready = 0;
    if (pthread_mutex_init(&args->ready_mutex, NULL) != 0) abort();
    if (pthread_cond_init(&args->ready_cond, NULL) != 0) abort();

    /* Root the object from this (spawning) thread until the new thread
     * has rooted it on its own stack (see simp_thread_trampoline). */
    SimpRootFrame frame = {0};
    void *const slots[1] = {&root};
    simp_gc_push_or_abort(&frame, slots, 1);

    SimpThreadHandle *handle = (SimpThreadHandle *)malloc(sizeof(*handle));
    if (handle == NULL) abort();

    if (pthread_create(&handle->thread, NULL, simp_thread_trampoline, args) != 0) {
        simp_gc_pop_or_abort(&frame);
        pthread_mutex_destroy(&args->ready_mutex);
        pthread_cond_destroy(&args->ready_cond);
        free(args);
        free(handle);
        abort();
    }

    /* Wait for the child to take over root-protection of the receiver.
     * Release the global lock first: the child cannot make progress (it
     * needs the same lock to register itself) while this thread holds it. */
    simp_runtime_gil_release();
    pthread_mutex_lock(&args->ready_mutex);
    while (!args->ready) {
        pthread_cond_wait(&args->ready_cond, &args->ready_mutex);
    }
    pthread_mutex_unlock(&args->ready_mutex);
    simp_runtime_gil_acquire();

    simp_gc_pop_or_abort(&frame);
    pthread_mutex_destroy(&args->ready_mutex);
    pthread_cond_destroy(&args->ready_cond);
    free(args);
    return handle;
}

void simp_thread_join(void *receiver, void *worker) {
    (void)receiver;
    if (worker == NULL) abort();
    SimpThreadHandle *handle = (SimpThreadHandle *)worker;
    /* Release the global lock so the joined thread (and any other thread)
     * can keep making progress while this thread blocks. */
    simp_runtime_gil_release();
    const int joined = pthread_join(handle->thread, NULL);
    simp_runtime_gil_acquire();
    if (joined != 0) abort();
    free(handle);
}

void *simp_semaphore_create(void *receiver, int32_t initial_count) {
    (void)receiver;
    if (initial_count < 0) abort();
    SimpSemaphoreObject *semaphore =
        (SimpSemaphoreObject *)malloc(sizeof(*semaphore));
    if (semaphore == NULL) abort();
    if (pthread_mutex_init(&semaphore->mutex, NULL) != 0) abort();
    if (pthread_cond_init(&semaphore->cond, NULL) != 0) abort();
    semaphore->count = initial_count;
    return semaphore;
}

void simp_semaphore_wait(void *receiver, void *semaphore) {
    (void)receiver;
    if (semaphore == NULL) abort();
    SimpSemaphoreObject *sem = (SimpSemaphoreObject *)semaphore;
    /* The semaphore's own mutex/condvar synchronize its count independent
     * of the global lock; releasing the global lock here only prevents a
     * blocked wait from starving every other Simple thread, exactly like
     * simp_thread_join above. */
    simp_runtime_gil_release();
    pthread_mutex_lock(&sem->mutex);
    while (sem->count <= 0) {
        pthread_cond_wait(&sem->cond, &sem->mutex);
    }
    --sem->count;
    pthread_mutex_unlock(&sem->mutex);
    simp_runtime_gil_acquire();
}

void simp_semaphore_signal(void *receiver, void *semaphore) {
    (void)receiver;
    if (semaphore == NULL) abort();
    SimpSemaphoreObject *sem = (SimpSemaphoreObject *)semaphore;
    pthread_mutex_lock(&sem->mutex);
    ++sem->count;
    pthread_cond_signal(&sem->cond);
    pthread_mutex_unlock(&sem->mutex);
}

void simp_semaphore_release(void *receiver, void *semaphore) {
    (void)receiver;
    if (semaphore == NULL) abort();
    SimpSemaphoreObject *sem = (SimpSemaphoreObject *)semaphore;
    pthread_mutex_destroy(&sem->mutex);
    pthread_cond_destroy(&sem->cond);
    free(sem);
}

/*
 * Mutex and Condition are *logical* locks: the native guard mutexes below
 * only protect a few fields for a short, non-blocking critical section and
 * are never held while acquiring the global lock (GIL) or while running
 * Simple code. Blocking waits happen with the GIL released, so a thread that
 * owns a logical mutex can always reacquire the GIL and unlock it.
 */
static int mutex_owned_by_caller(const SimpMutexObject *mutex) {
    return mutex->locked && pthread_equal(mutex->owner, pthread_self());
}

void *simp_mutex_create(void *receiver) {
    (void)receiver;
    SimpMutexObject *mutex = (SimpMutexObject *)malloc(sizeof(*mutex));
    if (mutex == NULL) {
        simp_runtime_set_error(ENOMEM);
        return NULL;
    }
    int result = pthread_mutex_init(&mutex->guard, NULL);
    if (result != 0) {
        free(mutex);
        simp_runtime_set_error(result);
        return NULL;
    }
    result = pthread_cond_init(&mutex->available, NULL);
    if (result != 0) {
        pthread_mutex_destroy(&mutex->guard);
        free(mutex);
        simp_runtime_set_error(result);
        return NULL;
    }
    mutex->locked = 0;
    mutex->waiters = 0;
    simp_runtime_clear_error();
    return mutex;
}

/* Caller holds mutex->guard and not the GIL. */
static void mutex_acquire_locked_guard(SimpMutexObject *mutex) {
    ++mutex->waiters;
    while (mutex->locked) {
        pthread_cond_wait(&mutex->available, &mutex->guard);
    }
    --mutex->waiters;
    mutex->locked = 1;
    mutex->owner = pthread_self();
}

int32_t simp_mutex_lock(void *receiver, void *object) {
    (void)receiver;
    if (object == NULL) {
        simp_runtime_set_error(EINVAL);
        return 0;
    }
    SimpMutexObject *mutex = (SimpMutexObject *)object;
    pthread_mutex_lock(&mutex->guard);
    if (mutex_owned_by_caller(mutex)) {
        pthread_mutex_unlock(&mutex->guard);
        simp_runtime_set_error(EDEADLK);
        return 0;
    }
    if (!mutex->locked) {
        /* Uncontended fast path: no need to give up the GIL. */
        mutex->locked = 1;
        mutex->owner = pthread_self();
        pthread_mutex_unlock(&mutex->guard);
        simp_runtime_clear_error();
        return 1;
    }
    pthread_mutex_unlock(&mutex->guard);

    simp_runtime_gil_release();
    pthread_mutex_lock(&mutex->guard);
    mutex_acquire_locked_guard(mutex);
    pthread_mutex_unlock(&mutex->guard);
    simp_runtime_gil_acquire();
    simp_runtime_clear_error();
    return 1;
}

/* Caller holds mutex->guard. */
static void mutex_release_locked_guard(SimpMutexObject *mutex) {
    mutex->locked = 0;
    if (mutex->waiters > 0) pthread_cond_signal(&mutex->available);
}

int32_t simp_mutex_unlock(void *receiver, void *object) {
    (void)receiver;
    if (object == NULL) {
        simp_runtime_set_error(EINVAL);
        return 0;
    }
    SimpMutexObject *mutex = (SimpMutexObject *)object;
    pthread_mutex_lock(&mutex->guard);
    if (!mutex_owned_by_caller(mutex)) {
        pthread_mutex_unlock(&mutex->guard);
        simp_runtime_set_error(EPERM);
        return 0;
    }
    mutex_release_locked_guard(mutex);
    pthread_mutex_unlock(&mutex->guard);
    simp_runtime_clear_error();
    return 1;
}

int32_t simp_mutex_release(void *receiver, void *object) {
    (void)receiver;
    if (object == NULL) {
        simp_runtime_set_error(EINVAL);
        return 0;
    }
    SimpMutexObject *mutex = (SimpMutexObject *)object;
    pthread_mutex_lock(&mutex->guard);
    const int busy = mutex->locked || mutex->waiters > 0;
    pthread_mutex_unlock(&mutex->guard);
    if (busy) {
        simp_runtime_set_error(EBUSY);
        return 0;
    }
    pthread_cond_destroy(&mutex->available);
    pthread_mutex_destroy(&mutex->guard);
    free(mutex);
    simp_runtime_clear_error();
    return 1;
}

void *simp_condition_create(void *receiver) {
    (void)receiver;
    SimpConditionObject *condition =
        (SimpConditionObject *)malloc(sizeof(*condition));
    if (condition == NULL) {
        simp_runtime_set_error(ENOMEM);
        return NULL;
    }
    int result = pthread_mutex_init(&condition->guard, NULL);
    if (result != 0) {
        free(condition);
        simp_runtime_set_error(result);
        return NULL;
    }
    result = pthread_cond_init(&condition->condition, NULL);
    if (result != 0) {
        pthread_mutex_destroy(&condition->guard);
        free(condition);
        simp_runtime_set_error(result);
        return NULL;
    }
    condition->sequence = 0;
    condition->waiters = 0;
    simp_runtime_clear_error();
    return condition;
}

int32_t simp_condition_wait(void *receiver, void *condition_object,
                            void *mutex_object) {
    (void)receiver;
    if (condition_object == NULL || mutex_object == NULL) {
        simp_runtime_set_error(EINVAL);
        return 0;
    }
    SimpConditionObject *condition = (SimpConditionObject *)condition_object;
    SimpMutexObject *mutex = (SimpMutexObject *)mutex_object;

    pthread_mutex_lock(&mutex->guard);
    const int owned = mutex_owned_by_caller(mutex);
    pthread_mutex_unlock(&mutex->guard);
    if (!owned) {
        simp_runtime_set_error(EPERM);
        return 0;
    }

    /* Register as a waiter and snapshot the signal sequence while the
     * logical mutex is still held: any signal issued after the caller
     * releases the mutex bumps the sequence, so it cannot be lost. */
    pthread_mutex_lock(&condition->guard);
    const uint64_t observed = condition->sequence;
    ++condition->waiters;
    pthread_mutex_unlock(&condition->guard);

    simp_runtime_gil_release();

    pthread_mutex_lock(&mutex->guard);
    mutex_release_locked_guard(mutex);
    pthread_mutex_unlock(&mutex->guard);

    pthread_mutex_lock(&condition->guard);
    while (condition->sequence == observed) {
        pthread_cond_wait(&condition->condition, &condition->guard);
    }
    --condition->waiters;
    pthread_mutex_unlock(&condition->guard);

    pthread_mutex_lock(&mutex->guard);
    mutex_acquire_locked_guard(mutex);
    pthread_mutex_unlock(&mutex->guard);

    simp_runtime_gil_acquire();
    simp_runtime_clear_error();
    return 1;
}

static int32_t condition_notify(void *object, int broadcast) {
    if (object == NULL) {
        simp_runtime_set_error(EINVAL);
        return 0;
    }
    SimpConditionObject *condition = (SimpConditionObject *)object;
    pthread_mutex_lock(&condition->guard);
    if (condition->waiters > 0) {
        ++condition->sequence;
        if (broadcast) pthread_cond_broadcast(&condition->condition);
        else pthread_cond_signal(&condition->condition);
    }
    pthread_mutex_unlock(&condition->guard);
    simp_runtime_clear_error();
    return 1;
}

int32_t simp_condition_signal(void *receiver, void *object) {
    (void)receiver;
    return condition_notify(object, 0);
}

int32_t simp_condition_broadcast(void *receiver, void *object) {
    (void)receiver;
    return condition_notify(object, 1);
}

int32_t simp_condition_release(void *receiver, void *object) {
    (void)receiver;
    if (object == NULL) {
        simp_runtime_set_error(EINVAL);
        return 0;
    }
    SimpConditionObject *condition = (SimpConditionObject *)object;
    pthread_mutex_lock(&condition->guard);
    const int busy = condition->waiters > 0;
    pthread_mutex_unlock(&condition->guard);
    if (busy) {
        simp_runtime_set_error(EBUSY);
        return 0;
    }
    pthread_cond_destroy(&condition->condition);
    pthread_mutex_destroy(&condition->guard);
    free(condition);
    simp_runtime_clear_error();
    return 1;
}
