/**
 * @file RuntimeGc.c
 * @brief Single-threaded precise mark/sweep collector for generated Simple objects.
 * @author Generated by GitHub Copilot
 */
#include "simp/RuntimeGc.h"

#include <stdalign.h>
#include <stdlib.h>
#include <string.h>

typedef struct HeapNode {
    struct HeapNode *next;
    void *object;
    int marked;
    int destroyed;
} HeapNode;

static HeapNode *heap = NULL;
static SimpRootFrame *root_frame = NULL;
static size_t object_count = 0;

static int valid_reference_offset(const SimpClassMeta *metadata, uint64_t offset) {
    return offset >= sizeof(void *) &&
           offset <= metadata->object_size - sizeof(void *) &&
           offset % alignof(void *) == 0;
}

static HeapNode *find_object(const void *object) {
    for (HeapNode *node = heap; node != NULL; node = node->next) {
        if (node->object == object) {
            return node;
        }
    }
    return NULL;
}

static void mark_object(void *object, HeapNode **worklist, size_t *work_count) {
    if (object == NULL) {
        return;
    }
    HeapNode *node = find_object(object);
    if (node == NULL || node->marked) {
        return;
    }
    node->marked = 1;
    worklist[(*work_count)++] = node;
}

int simp_gc_push(SimpRootFrame *frame, void *const *slots, uint64_t count) {
    if (frame == NULL || (count != 0 && slots == NULL)) {
        return 0;
    }
    for (SimpRootFrame *active = root_frame; active != NULL; active = active->previous) {
        if (active == frame) {
            return 0;
        }
    }
    for (uint64_t index = 0; index < count; ++index) {
        if (slots[index] == NULL) {
            return 0;
        }
    }
    frame->previous = root_frame;
    frame->count = count;
    frame->slots = slots;
    root_frame = frame;
    return 1;
}

int simp_gc_pop(SimpRootFrame *frame) {
    if (frame == NULL || root_frame != frame) {
        return 0;
    }
    root_frame = frame->previous;
    frame->previous = NULL;
    frame->count = 0;
    frame->slots = NULL;
    return 1;
}

void simp_gc_push_or_abort(SimpRootFrame *frame, void *const *slots, uint64_t count) {
    if (!simp_gc_push(frame, slots, count)) {
        abort();
    }
}

void simp_gc_pop_or_abort(SimpRootFrame *frame) {
    if (!simp_gc_pop(frame)) {
        abort();
    }
}

void simp_gc_require_alive(void *object) {
    if (object == NULL) {
        return;
    }
    HeapNode *node = find_object(object);
    if (node == NULL || node->destroyed) {
        abort();
    }
}

void simp_gc_begin_destroy(void *object) {
    HeapNode *node = find_object(object);
    if (node == NULL || node->destroyed) {
        abort();
    }
    node->destroyed = 1;
}

void simp_gc_collect(void) {
    HeapNode **worklist = NULL;
    if (object_count != 0) {
        if (object_count > SIZE_MAX / sizeof(*worklist)) {
            abort();
        }
        worklist = (HeapNode **)malloc(object_count * sizeof(*worklist));
        if (worklist == NULL) {
            abort();
        }
    }
    for (HeapNode *node = heap; node != NULL; node = node->next) {
        node->marked = 0;
    }

    size_t work_count = 0;
    for (SimpRootFrame *frame = root_frame; frame != NULL; frame = frame->previous) {
        for (uint64_t index = 0; index < frame->count; ++index) {
            if (frame->slots == NULL || frame->slots[index] == NULL) {
                free(worklist);
                abort();
            }
            void *object = NULL;
            memcpy(&object, frame->slots[index], sizeof(object));
            mark_object(object, worklist, &work_count);
        }
    }

    while (work_count != 0) {
        HeapNode *node = worklist[--work_count];
        const SimpClassMeta *metadata = NULL;
        memcpy(&metadata, node->object, sizeof(metadata));
        if (metadata == NULL) {
            free(worklist);
            abort();
        }
        for (uint64_t index = 0; index < metadata->reference_field_count; ++index) {
            const uint64_t offset = metadata->reference_field_offsets[index];
            if (!valid_reference_offset(metadata, offset)) {
                free(worklist);
                abort();
            }
            void *child = NULL;
            memcpy(&child, (const unsigned char *)node->object + offset, sizeof(child));
            mark_object(child, worklist, &work_count);
        }
    }
    free(worklist);

    HeapNode **link = &heap;
    while (*link != NULL) {
        HeapNode *node = *link;
        if (!node->marked) {
            *link = node->next;
            free(node->object);
            free(node);
            --object_count;
        } else {
            link = &node->next;
        }
    }
}

void *simp_gc_alloc(const SimpClassMeta *metadata) {
    if (metadata == NULL || metadata->object_size < sizeof(void *) ||
        metadata->object_size > (uint64_t)SIZE_MAX ||
        (metadata->reference_field_count != 0 &&
         metadata->reference_field_offsets == NULL)) {
        abort();
    }
    for (uint64_t index = 0; index < metadata->reference_field_count; ++index) {
        const uint64_t offset = metadata->reference_field_offsets[index];
        if (!valid_reference_offset(metadata, offset)) {
            abort();
        }
    }
    simp_gc_collect();
    void *object = calloc(1, (size_t)metadata->object_size);
    HeapNode *node = (HeapNode *)malloc(sizeof(*node));
    if (object == NULL || node == NULL) {
        free(object);
        free(node);
        abort();
    }
    memcpy(object, &metadata, sizeof(metadata));
    node->object = object;
    node->marked = 0;
    node->destroyed = 0;
    node->next = heap;
    heap = node;
    ++object_count;
    return object;
}

size_t simp_gc_heap_count(void) {
    return object_count;
}
