/**
 * @file RuntimeGc.c
 * @brief Single-threaded precise mark/sweep collector for generated Simple objects.
 * @author Generated by GitHub Copilot
 */
#include "simp/RuntimeGc.h"

#include <setjmp.h>
#include <stdalign.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct InlineCStringBuffer {
    struct InlineCStringBuffer *next;
    char *bytes;
} InlineCStringBuffer;

static _Thread_local InlineCStringBuffer *inline_cstring_buffers = NULL;

void simp_inline_cstr_end(void) {
    while (inline_cstring_buffers != NULL) {
        InlineCStringBuffer *buffer = inline_cstring_buffers;
        inline_cstring_buffers = buffer->next;
        free(buffer->bytes);
        free(buffer);
    }
}

void simp_inline_cstr_begin(void) {
    simp_inline_cstr_end();
}

const char *simp_string_cstr(const SimpString *text) {
    if (text == NULL || text->length > (uint64_t)(SIZE_MAX - 1) ||
        (text->length != 0 && text->data == NULL)) {
        abort();
    }
    InlineCStringBuffer *buffer =
        (InlineCStringBuffer *)malloc(sizeof(InlineCStringBuffer));
    if (buffer == NULL) abort();
    buffer->bytes = (char *)malloc((size_t)text->length + 1);
    if (buffer->bytes == NULL) {
        free(buffer);
        abort();
    }
    if (text->length != 0) {
        memcpy(buffer->bytes, text->data, (size_t)text->length);
    }
    buffer->bytes[text->length] = '\0';
    buffer->next = inline_cstring_buffers;
    inline_cstring_buffers = buffer;
    return buffer->bytes;
}

typedef struct HeapNode {
    struct HeapNode *next;
    struct HeapNode *destroy_previous;
    struct HeapNode *construct_previous;
    void *object;
    size_t allocation_size;
    int marked;
    int is_array;
    int is_map;
    int destroyed;
    int destroying;
    int constructing;
} HeapNode;

typedef struct SimpExceptionFrame {
    jmp_buf buffer;
    struct SimpExceptionFrame *previous;
    SimpRootFrame *saved_roots;
    HeapNode *saved_destroys;
    HeapNode *saved_constructions;
    size_t message_length;
    char *message;
    size_t file_length;
    char *file;
    uint64_t line;
    uint64_t column;
    int has_exception;
} SimpExceptionFrame;

typedef struct RetainedExceptionMessage {
    struct RetainedExceptionMessage *next;
    char *bytes;
} RetainedExceptionMessage;

_Static_assert(alignof(SimpExceptionFrame) <= 16,
               "generated exception frames require at most 16-byte alignment");

static HeapNode *heap = NULL;
static SimpRootFrame *root_frame = NULL;
static HeapNode *destroy_stack = NULL;
static HeapNode *construction_stack = NULL;
static SimpExceptionFrame *active_exception = NULL;
static size_t object_count = 0;
static int collecting = 0;
static int running_destructor = 0;
static RetainedExceptionMessage *retained_exception_messages = NULL;
static int retained_message_cleanup_registered = 0;
static const SimpClassMeta array_metadata = {
    "array", 5, 0, NULL, 0, sizeof(SimpArray), 0, NULL, NULL
};
static const SimpClassMeta map_metadata = {
    "map", 3, 0, NULL, 0, sizeof(SimpMap), 0, NULL, NULL
};

static HeapNode *find_object(const void *object);

static void release_retained_exception_messages(void) {
    while (retained_exception_messages != NULL) {
        RetainedExceptionMessage *message = retained_exception_messages;
        retained_exception_messages = message->next;
        free(message->bytes);
        free(message);
    }
}

static void uncaught_exception(const char *message, size_t length,
                               const char *file, size_t file_length,
                               uint64_t line, uint64_t column) {
    fputs("simp: uncaught runtime exception", stderr);
    if (file != NULL) {
        fputs(" at ", stderr);
        if (file_length != 0) fwrite(file, 1, file_length, stderr);
        fprintf(stderr, ":%llu:%llu", (unsigned long long)line,
                (unsigned long long)column);
    }
    fputs(": ", stderr);
    if (length != 0) fwrite(message, 1, length, stderr);
    fputc('\n', stderr);
    fflush(stdout);
    fflush(stderr);
    abort();
}

void simp_gc_begin_construction(void *object) {
    HeapNode *node = find_object(object);
    if (node == NULL || node->destroyed || node->constructing) abort();
    node->constructing = 1;
    node->construct_previous = construction_stack;
    construction_stack = node;
}

void simp_gc_end_construction(void *object) {
    HeapNode *node = find_object(object);
    if (node == NULL || !node->constructing || construction_stack != node) abort();
    node->constructing = 0;
    construction_stack = node->construct_previous;
    node->construct_previous = NULL;
}

static void raise_exception(const char *message, uint64_t length,
                            const char *file, uint64_t file_length,
                            uint64_t line, uint64_t column,
                            char *owned_message, char *owned_file) {
    if ((message == NULL && length != 0) || length > (uint64_t)SIZE_MAX ||
        (file == NULL && file_length != 0) || file_length > (uint64_t)SIZE_MAX) abort();
    if (collecting || running_destructor) {
        free(owned_message);
        free(owned_file);
        static const char finalizer_message[] =
            "exceptions cannot escape a GC finalizer";
        uncaught_exception(finalizer_message, sizeof(finalizer_message) - 1,
                           NULL, 0, 0, 0);
    }
    if (active_exception == NULL) {
        uncaught_exception(message == NULL ? "" : message, (size_t)length,
                           file, (size_t)file_length, line, column);
    }
    SimpExceptionFrame *frame = active_exception;
    char *copy = length == 0 ? NULL : (char *)malloc((size_t)length);
    char *file_copy = file_length == 0 ? NULL : (char *)malloc((size_t)file_length);
    if ((length != 0 && copy == NULL) || (file_length != 0 && file_copy == NULL)) {
        free(owned_message);
        free(owned_file);
        free(copy);
        free(file_copy);
        static const char allocation_message[] =
            "out of memory while raising runtime exception";
        uncaught_exception(allocation_message, sizeof(allocation_message) - 1,
                           NULL, 0, 0, 0);
    }
    if (length != 0) memcpy(copy, message, (size_t)length);
    if (file_length != 0) memcpy(file_copy, file, (size_t)file_length);
    free(owned_message);
    free(owned_file);
    free(frame->message);
    free(frame->file);
    frame->message = copy;
    frame->message_length = (size_t)length;
    frame->file = file_copy;
    frame->file_length = (size_t)file_length;
    frame->line = line;
    frame->column = column;
    frame->has_exception = 1;
    active_exception = frame->previous;
    frame->previous = NULL;
    root_frame = frame->saved_roots;
    while (destroy_stack != frame->saved_destroys) {
        if (destroy_stack == NULL) abort();
        destroy_stack->destroying = 0;
        destroy_stack = destroy_stack->destroy_previous;
    }
    while (construction_stack != frame->saved_constructions) {
        if (construction_stack == NULL) abort();
        construction_stack->constructing = 0;
        construction_stack->destroyed = 1;
        construction_stack = construction_stack->construct_previous;
    }
    longjmp(frame->buffer, 1);
}

uint64_t simp_exception_frame_size(void) {
    return (uint64_t)sizeof(SimpExceptionFrame);
}

void simp_exception_frame_init(void *storage) {
    if (storage == NULL ||
        (uintptr_t)storage % alignof(SimpExceptionFrame) != 0) {
        abort();
    }
    memset(storage, 0, sizeof(SimpExceptionFrame));
}

void *simp_exception_frame_buffer(void *storage) {
    if (storage == NULL) abort();
    return ((SimpExceptionFrame *)storage)->buffer;
}

void simp_exception_push(void *storage) {
    SimpExceptionFrame *frame = (SimpExceptionFrame *)storage;
    if (frame == NULL || active_exception == frame) abort();
    frame->previous = active_exception;
    frame->saved_roots = root_frame;
    frame->saved_destroys = destroy_stack;
    frame->saved_constructions = construction_stack;
    free(frame->message);
    frame->message = NULL;
    frame->message_length = 0;
    free(frame->file);
    frame->file = NULL;
    frame->file_length = 0;
    frame->line = 0;
    frame->column = 0;
    frame->has_exception = 0;
    active_exception = frame;
}

void simp_exception_pop(void *storage) {
    SimpExceptionFrame *frame = (SimpExceptionFrame *)storage;
    if (frame == NULL || active_exception != frame) abort();
    active_exception = frame->previous;
    frame->previous = NULL;
    if (frame->has_exception) abort();
    free(frame->message);
    frame->message = NULL;
    free(frame->file);
    frame->file = NULL;
    frame->file_length = 0;
    frame->line = 0;
    frame->column = 0;
}

void simp_exception_clear(void *storage) {
    SimpExceptionFrame *frame = (SimpExceptionFrame *)storage;
    if (frame == NULL) abort();
    free(frame->message);
    frame->message = NULL;
    free(frame->file);
    frame->file = NULL;
    frame->file_length = 0;
    frame->line = 0;
    frame->column = 0;
    frame->message_length = 0;
    frame->has_exception = 0;
}

const char *simp_exception_take_message(void *storage) {
    SimpExceptionFrame *frame = (SimpExceptionFrame *)storage;
    if (frame == NULL || !frame->has_exception) abort();
    if (frame->message == NULL) return "";
    RetainedExceptionMessage *retained =
        (RetainedExceptionMessage *)malloc(sizeof(*retained));
    if (retained == NULL) abort();
    retained->bytes = frame->message;
    retained->next = retained_exception_messages;
    retained_exception_messages = retained;
    if (!retained_message_cleanup_registered) {
        if (atexit(release_retained_exception_messages) != 0) abort();
        retained_message_cleanup_registered = 1;
    }
    frame->message = NULL;
    frame->message_length = 0;
    return retained->bytes;
}

uint64_t simp_exception_message_length(void *storage) {
    SimpExceptionFrame *frame = (SimpExceptionFrame *)storage;
    if (frame == NULL || !frame->has_exception) abort();
    return (uint64_t)frame->message_length;
}

void simp_exception_raise(const char *message, uint64_t length, const char *file,
                          uint64_t file_length, uint64_t line, uint64_t column) {
    raise_exception(message, length, file, file_length, line, column, NULL, NULL);
}

void simp_exception_rethrow(void *storage) {
    SimpExceptionFrame *frame = (SimpExceptionFrame *)storage;
    if (frame == NULL || !frame->has_exception) abort();
    char *message = frame->message;
    const uint64_t length = (uint64_t)frame->message_length;
    char *file = frame->file;
    const uint64_t file_length = (uint64_t)frame->file_length;
    const uint64_t line = frame->line;
    const uint64_t column = frame->column;
    frame->message = NULL;
    frame->message_length = 0;
    frame->file = NULL;
    frame->file_length = 0;
    frame->line = 0;
    frame->column = 0;
    frame->has_exception = 0;
    raise_exception(message, length, file, file_length, line, column,
                    message, file);
}

static int valid_reference_offset(const SimpClassMeta *metadata, uint64_t offset) {
    return metadata->object_size >= sizeof(void *) &&
           offset >= sizeof(void *) &&
           offset <= metadata->object_size - sizeof(void *) &&
           offset % alignof(void *) == 0;
}

static HeapNode *find_object(const void *object) {
    for (HeapNode *node = heap; node != NULL; node = node->next) {
        if (node->object == object) {
            return node;
        }
    }
    return NULL;
}

static HeapNode *find_containing_object(const void *object) {
    const uintptr_t address = (uintptr_t)object;
    for (HeapNode *node = heap; node != NULL; node = node->next) {
        const uintptr_t start = (uintptr_t)node->object;
        if (address < start) continue;
        if (address - start < node->allocation_size) return node;
    }
    return NULL;
}

static void mark_object(void *object, HeapNode **worklist, size_t *work_count) {
    if (object == NULL) {
        return;
    }
    HeapNode *node = find_containing_object(object);
    if (node == NULL || node->marked) {
        return;
    }
    node->marked = 1;
    worklist[(*work_count)++] = node;
}

int simp_gc_push(SimpRootFrame *frame, void *const *slots, uint64_t count) {
    if (frame == NULL || (count != 0 && slots == NULL)) {
        return 0;
    }
    for (SimpRootFrame *active = root_frame; active != NULL; active = active->previous) {
        if (active == frame) {
            return 0;
        }
    }
    for (uint64_t index = 0; index < count; ++index) {
        if (slots[index] == NULL) {
            return 0;
        }
    }
    frame->previous = root_frame;
    frame->count = count;
    frame->slots = slots;
    root_frame = frame;
    return 1;
}

int simp_gc_pop(SimpRootFrame *frame) {
    if (frame == NULL || root_frame != frame) {
        return 0;
    }
    root_frame = frame->previous;
    frame->previous = NULL;
    frame->count = 0;
    frame->slots = NULL;
    return 1;
}

void simp_gc_push_or_abort(SimpRootFrame *frame, void *const *slots, uint64_t count) {
    if (!simp_gc_push(frame, slots, count)) {
        abort();
    }
}

void simp_gc_pop_or_abort(SimpRootFrame *frame) {
    if (!simp_gc_pop(frame)) {
        abort();
    }
}

void simp_gc_require_alive(void *object, const char *file, uint64_t file_length,
                           uint64_t line, uint64_t column) {
    if (object == NULL) {
        return;
    }
    HeapNode *node = find_containing_object(object);
    if (node == NULL)
        simp_exception_raise("invalid object reference", 24, file, file_length, line, column);
    if (node->destroyed && !node->destroying)
        simp_exception_raise("object has been destroyed", 25, file, file_length, line, column);
}

void simp_value_require_tag(uint64_t actual, uint64_t expected, const char *file,
                            uint64_t file_length, uint64_t line, uint64_t column) {
    if (actual != expected) {
        static const char message[] = "'any' value does not hold the requested type";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
}

void simp_value_require_class(uint64_t actual_tag, void *pointer,
                              const SimpClassMeta *expected, const char *file,
                              uint64_t file_length, uint64_t line, uint64_t column) {
    if (actual_tag != SIMP_ARRAY_OBJECT) {
        static const char message[] = "'any' value does not hold an object reference";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    if (pointer == NULL) {
        /* A null object reference is compatible with every class type. */
        return;
    }
    const SimpClassMeta *actual;
    memcpy(&actual, pointer, sizeof(actual));
    if (actual != expected) {
        static const char message[] =
            "'any' value holds a different class than the requested type";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
}

void simp_value_require_map(uint64_t actual_tag, void *pointer, const char *file,
                           uint64_t file_length, uint64_t line, uint64_t column) {
    static const char message[] = "'any' value does not hold a map reference";
    if (actual_tag != SIMP_ARRAY_MAP) {
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    if (pointer == NULL) {
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    HeapNode *node = find_object(pointer);
    if (node == NULL || !node->is_map) {
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
}

void simp_value_require_array(uint64_t actual_tag, void *pointer, const char *file,
                              uint64_t file_length, uint64_t line, uint64_t column) {
    static const char message[] = "'any' value does not hold an array reference";
    if (actual_tag != SIMP_ARRAY_ARRAY) {
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    if (pointer == NULL) {
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    HeapNode *node = find_object(pointer);
    if (node == NULL || !node->is_array) {
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
}


void *simp_gc_root(void *object) {
    HeapNode *node = find_containing_object(object);
    if (node == NULL) abort();
    return node->object;
}

void simp_gc_begin_destroy(void *object, const char *file, uint64_t file_length,
                           uint64_t line, uint64_t column) {
    HeapNode *node = find_containing_object(object);
    if (node == NULL)
        simp_exception_raise("invalid object reference", 24, file, file_length, line, column);
    if (node->destroyed)
        simp_exception_raise("object has already been destroyed", 32,
                             file, file_length, line, column);
    node->destroyed = 1;
    node->destroying = 1;
    node->destroy_previous = destroy_stack;
    destroy_stack = node;
}

void simp_gc_end_destroy(void *object) {
    HeapNode *node = find_containing_object(object);
    if (node == NULL || !node->destroying || destroy_stack != node) {
        abort();
    }
    node->destroying = 0;
    destroy_stack = node->destroy_previous;
    node->destroy_previous = NULL;
}

static HeapNode **allocate_worklist(void) {
    if (object_count > SIZE_MAX / sizeof(HeapNode *)) {
        abort();
    }
    HeapNode **worklist = object_count == 0 ? NULL :
        (HeapNode **)malloc(object_count * sizeof(*worklist));
    if (object_count != 0 && worklist == NULL) abort();
    return worklist;
}

static void mark_roots(HeapNode **worklist, size_t *work_count) {
    for (SimpRootFrame *frame = root_frame; frame != NULL; frame = frame->previous) {
        for (uint64_t index = 0; index < frame->count; ++index) {
            if (frame->slots == NULL || frame->slots[index] == NULL) abort();
            void *object = NULL;
            memcpy(&object, frame->slots[index], sizeof(object));
            mark_object(object, worklist, work_count);
        }
    }
}

static void trace_graph(HeapNode **worklist, size_t *work_count) {
    while (*work_count != 0) {
        HeapNode *node = worklist[--(*work_count)];
        if (node->is_array) {
            const SimpArray *array = (const SimpArray *)node->object;
            for (uint64_t index = 0; index < array->length; ++index) {
                const SimpArrayValue *value = &array->values[index];
                if (value->tag == SIMP_ARRAY_OBJECT || value->tag == SIMP_ARRAY_MAP ||
                    value->tag == SIMP_ARRAY_ARRAY) {
                    mark_object(value->pointer, worklist, work_count);
                }
            }
            continue;
        }
        if (node->is_map) {
            const SimpMap *map = (const SimpMap *)node->object;
            for (uint64_t index = 0; index < map->length; ++index) {
                const SimpArrayValue *value = &map->entries[index].value;
                if (value->tag == SIMP_ARRAY_OBJECT || value->tag == SIMP_ARRAY_MAP ||
                    value->tag == SIMP_ARRAY_ARRAY) {
                    mark_object(value->pointer, worklist, work_count);
                }
            }
            continue;
        }
        const SimpClassMeta *metadata = NULL;
        memcpy(&metadata, node->object, sizeof(metadata));
        if (metadata == NULL) abort();
        for (uint64_t index = 0; index < metadata->reference_field_count; ++index) {
            const uint64_t offset = metadata->reference_field_offsets[index];
            if (!valid_reference_offset(metadata, offset)) abort();
            void *child = NULL;
            memcpy(&child, (const unsigned char *)node->object + offset, sizeof(child));
            mark_object(child, worklist, work_count);
        }
    }
}

void simp_gc_collect(void) {
    if (collecting || running_destructor) abort();
    collecting = 1;
    for (HeapNode *node = heap; node != NULL; node = node->next) {
        node->marked = 0;
    }
    HeapNode **worklist = allocate_worklist();
    size_t work_count = 0;
    mark_roots(worklist, &work_count);
    trace_graph(worklist, &work_count);

    for (HeapNode *node = heap; node != NULL; node = node->next) {
        if (node->marked || node->destroyed) continue;
        const SimpClassMeta *metadata = NULL;
        memcpy(&metadata, node->object, sizeof(metadata));
        if (metadata == NULL) abort();
        node->destroyed = 1;
        if (metadata->finalize != NULL) {
            node->destroying = 1;
            running_destructor = 1;
            metadata->finalize(node->object);
            running_destructor = 0;
            node->destroying = 0;
        }
    }

    /* Finalizers may attach dead objects to live objects; retain, but keep them destroyed. */
    for (HeapNode *node = heap; node != NULL; node = node->next) node->marked = 0;
    work_count = 0;
    mark_roots(worklist, &work_count);
    trace_graph(worklist, &work_count);
    free(worklist);

    HeapNode **link = &heap;
    while (*link != NULL) {
        HeapNode *node = *link;
        if (!node->marked) {
            *link = node->next;
            if (node->is_map) {
                SimpMap *map = (SimpMap *)node->object;
                for (uint64_t index = 0; index < map->length; ++index) {
                    free((void *)map->entries[index].key);
                }
                free(map->entries);
                free(map->buckets);
            }
            free(node->object);
            free(node);
            --object_count;
        } else {
            link = &node->next;
        }
    }
    collecting = 0;
}

void *simp_gc_alloc(const SimpClassMeta *metadata) {
    if (collecting || running_destructor) abort();
    if (metadata == NULL || metadata->object_size < sizeof(void *) ||
        metadata->object_size > (uint64_t)SIZE_MAX ||
        (metadata->reference_field_count != 0 &&
         metadata->reference_field_offsets == NULL)) {
        abort();
    }
    for (uint64_t index = 0; index < metadata->reference_field_count; ++index) {
        const uint64_t offset = metadata->reference_field_offsets[index];
        if (!valid_reference_offset(metadata, offset)) {
            abort();
        }
    }
    simp_gc_collect();
    void *object = calloc(1, (size_t)metadata->object_size);
    HeapNode *node = (HeapNode *)malloc(sizeof(*node));
    if (object == NULL || node == NULL) {
        free(object);
        free(node);
        abort();
    }
    memcpy(object, &metadata, sizeof(metadata));
    node->object = object;
    node->allocation_size = (size_t)metadata->object_size;
    node->is_array = 0;
    node->is_map = 0;
    node->marked = 0;
    node->destroyed = 0;
    node->destroying = 0;
    node->destroy_previous = NULL;
    node->constructing = 0;
    node->construct_previous = NULL;
    node->next = heap;
    heap = node;
    ++object_count;
    return object;
}

void *simp_gc_alloc_array(uint64_t length) {
    if (collecting || running_destructor || length > INT32_MAX ||
        length > (SIZE_MAX - sizeof(SimpArray)) / sizeof(SimpArrayValue)) {
        abort();
    }
    simp_gc_collect();
    const size_t allocation_size =
        sizeof(SimpArray) + (size_t)length * sizeof(SimpArrayValue);
    SimpArray *array = (SimpArray *)calloc(1, allocation_size);
    HeapNode *node = (HeapNode *)malloc(sizeof(*node));
    if (array == NULL || node == NULL) {
        free(array);
        free(node);
        abort();
    }
    array->metadata = &array_metadata;
    array->length = length;
    node->object = array;
    node->allocation_size = allocation_size;
    node->is_array = 1;
    node->is_map = 0;
    node->marked = 0;
    node->destroyed = 0;
    node->destroying = 0;
    node->destroy_previous = NULL;
    node->constructing = 0;
    node->construct_previous = NULL;
    node->next = heap;
    heap = node;
    ++object_count;
    return array;
}

void *simp_gc_alloc_map(void) {
    if (collecting || running_destructor) abort();
    simp_gc_collect();
    SimpMap *map = (SimpMap *)calloc(1, sizeof(*map));
    HeapNode *node = (HeapNode *)malloc(sizeof(*node));
    if (map == NULL || node == NULL) {
        free(map);
        free(node);
        abort();
    }
    map->metadata = &map_metadata;
    node->object = map;
    node->allocation_size = sizeof(*map);
    node->is_array = 0;
    node->is_map = 1;
    node->marked = 0;
    node->destroyed = 0;
    node->destroying = 0;
    node->destroy_previous = NULL;
    node->constructing = 0;
    node->construct_previous = NULL;
    node->next = heap;
    heap = node;
    ++object_count;
    return map;
}

static SimpArray *checked_array(void *object, const char *file, uint64_t file_length,
                                uint64_t line, uint64_t column) {
    if (object == NULL) {
        static const char message[] = "null array reference";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    HeapNode *node = find_object(object);
    if (node == NULL || !node->is_array) {
        static const char message[] = "invalid array reference";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    return (SimpArray *)object;
}

static SimpMap *checked_map(void *object, const char *file, uint64_t file_length,
                            uint64_t line, uint64_t column) {
    if (object == NULL) {
        static const char message[] = "null map reference";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    HeapNode *node = find_object(object);
    if (node == NULL || !node->is_map) {
        static const char message[] = "invalid map reference";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    return (SimpMap *)object;
}

static int map_key_matches(const SimpMapEntry *entry, const char *key,
                           uint64_t key_length) {
    return entry->key_length == key_length &&
           (key_length == 0 || memcmp(entry->key, key, (size_t)key_length) == 0);
}

static uint64_t map_key_hash(const char *key, uint64_t key_length) {
    uint64_t hash = UINT64_C(14695981039346656037);
    for (uint64_t index = 0; index < key_length; ++index) {
        hash ^= (unsigned char)key[index];
        hash *= UINT64_C(1099511628211);
    }
    return hash;
}

static uint64_t map_find_index(const SimpMap *map, const char *key,
                               uint64_t key_length, uint64_t hash) {
    if (map->bucket_capacity == 0) return UINT64_MAX;
    const uint64_t mask = map->bucket_capacity - 1;
    uint64_t bucket = hash & mask;
    for (uint64_t probes = 0; probes < map->bucket_capacity; ++probes) {
        const uint64_t stored = map->buckets[bucket];
        if (stored == 0) return UINT64_MAX;
        const uint64_t index = stored - 1;
        const SimpMapEntry *entry = &map->entries[index];
        if (entry->hash == hash && map_key_matches(entry, key, key_length)) return index;
        bucket = (bucket + 1) & mask;
    }
    return UINT64_MAX;
}

static void map_rebuild_index(SimpMap *map, uint64_t capacity) {
    if (capacity < 8 || (capacity & (capacity - 1)) != 0 ||
        capacity > SIZE_MAX / sizeof(uint64_t)) abort();
    uint64_t *buckets = (uint64_t *)calloc((size_t)capacity, sizeof(*buckets));
    if (buckets == NULL) abort();
    const uint64_t mask = capacity - 1;
    for (uint64_t index = 0; index < map->length; ++index) {
        uint64_t bucket = map->entries[index].hash & mask;
        while (buckets[bucket] != 0) bucket = (bucket + 1) & mask;
        buckets[bucket] = index + 1;
    }
    free(map->buckets);
    map->buckets = buckets;
    map->bucket_capacity = capacity;
}

void *simp_map_get(void *object, const char *key, uint64_t key_length, const char *file,
                   uint64_t file_length, uint64_t line, uint64_t column) {
    SimpMap *map = checked_map(object, file, file_length, line, column);
    if ((key == NULL && key_length != 0) || key_length > (uint64_t)SIZE_MAX) abort();
    const uint64_t index = map_find_index(map, key, key_length,
                                          map_key_hash(key, key_length));
    if (index != UINT64_MAX) return &map->entries[index].value;
    static const char message[] = "map key not found";
    simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    abort();
}

int32_t simp_map_contains(void *object, const char *key, uint64_t key_length,
                          const char *file, uint64_t file_length, uint64_t line,
                          uint64_t column) {
    SimpMap *map = checked_map(object, file, file_length, line, column);
    if ((key == NULL && key_length != 0) || key_length > (uint64_t)SIZE_MAX) abort();
    return map_find_index(map, key, key_length, map_key_hash(key, key_length)) !=
                   UINT64_MAX;
}

void *simp_map_entry_at(void *object, uint64_t index, const char *file,
                        uint64_t file_length, uint64_t line, uint64_t column) {
    SimpMap *map = checked_map(object, file, file_length, line, column);
    if (index >= map->length) {
        static const char message[] = "map iteration index out of bounds";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    return &map->entries[index];
}

void simp_map_set(void *object, const char *key, uint64_t key_length,
                  const SimpArrayValue *value,
                  const char *file, uint64_t file_length, uint64_t line, uint64_t column) {
    SimpMap *map = checked_map(object, file, file_length, line, column);
    if (value == NULL || (key == NULL && key_length != 0) ||
        key_length > (uint64_t)SIZE_MAX) abort();
    const uint64_t hash = map_key_hash(key, key_length);
    const uint64_t existing = map_find_index(map, key, key_length, hash);
    if (existing != UINT64_MAX) {
        map->entries[existing].value = *value;
        return;
    }
    if (map->length >= INT32_MAX) abort();
    char *key_copy = (char *)malloc(key_length == 0 ? 1 : (size_t)key_length);
    if (key_copy == NULL) abort();
    if (key_length != 0) memcpy(key_copy, key, (size_t)key_length);
    if (map->length == map->capacity) {
        const uint64_t capacity = map->capacity == 0 ? 4 : map->capacity * 2;
        if (capacity < map->capacity ||
            capacity > SIZE_MAX / sizeof(SimpMapEntry)) abort();
        SimpMapEntry *entries =
            (SimpMapEntry *)realloc(map->entries, (size_t)capacity * sizeof(*entries));
        if (entries == NULL) {
            free(key_copy);
            abort();
        }
        map->entries = entries;
        map->capacity = capacity;
    }
    if (map->bucket_capacity == 0 ||
        map->length + 1 > map->bucket_capacity / 2) {
        uint64_t bucket_capacity = map->bucket_capacity == 0 ? 8 : map->bucket_capacity;
        while (map->length + 1 > bucket_capacity / 2) {
            if (bucket_capacity > UINT64_MAX / 2) {
                free(key_copy);
                abort();
            }
            bucket_capacity *= 2;
        }
        map_rebuild_index(map, bucket_capacity);
    }
    SimpMapEntry *entry = &map->entries[map->length++];
    entry->key = key_copy;
    entry->key_length = key_length;
    entry->hash = hash;
    entry->value = *value;
    uint64_t bucket = hash & (map->bucket_capacity - 1);
    while (map->buckets[bucket] != 0) {
        bucket = (bucket + 1) & (map->bucket_capacity - 1);
    }
    map->buckets[bucket] = map->length;
}

int32_t simp_map_remove(void *object, const char *key, uint64_t key_length,
                        const char *file, uint64_t file_length, uint64_t line,
                        uint64_t column) {
    SimpMap *map = checked_map(object, file, file_length, line, column);
    if ((key == NULL && key_length != 0) || key_length > (uint64_t)SIZE_MAX) abort();
    const uint64_t index = map_find_index(map, key, key_length,
                                          map_key_hash(key, key_length));
    if (index == UINT64_MAX) return 0;
    free((void *)map->entries[index].key);
    if (index + 1 < map->length) {
        memmove(&map->entries[index], &map->entries[index + 1],
                (size_t)(map->length - index - 1) * sizeof(*map->entries));
    }
    --map->length;
    if (map->bucket_capacity != 0) {
        map_rebuild_index(map, map->bucket_capacity);
    }
    return 1;
}

void *simp_map_slice(void *object, int32_t start, int32_t end, const char *file,
                     uint64_t file_length, uint64_t line, uint64_t column) {
    SimpMap *source = checked_map(object, file, file_length, line, column);
    if (start < 0 || end < start || (uint64_t)end > source->length) {
        static const char message[] = "map slice bounds out of bounds";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    SimpMap *copy = (SimpMap *)simp_gc_alloc_map();
    for (int32_t index = start; index < end; ++index) {
        const SimpMapEntry *entry = &source->entries[index];
        simp_map_set(copy, entry->key, entry->key_length, &entry->value,
                     file, file_length, line, column);
    }
    return copy;
}

void *simp_array_index(void *object, int32_t index, const char *file,
                       uint64_t file_length, uint64_t line, uint64_t column) {
    SimpArray *array = checked_array(object, file, file_length, line, column);
    if (index < 0 || (uint64_t)index >= array->length) {
        static const char message[] = "array index out of bounds";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    return &array->values[index];
}

void *simp_array_slice(void *object, int32_t start, int32_t end, const char *file,
                       uint64_t file_length, uint64_t line, uint64_t column) {
    SimpArray *source = checked_array(object, file, file_length, line, column);
    if (start < 0 || end < start || (uint64_t)end > source->length) {
        static const char message[] = "array slice bounds out of bounds";
        simp_exception_raise(message, sizeof(message) - 1, file, file_length, line, column);
    }
    const uint64_t length = (uint64_t)(end - start);
    SimpArray *copy = (SimpArray *)simp_gc_alloc_array(length);
    if (length != 0) {
        memcpy(copy->values, source->values + start,
               (size_t)length * sizeof(SimpArrayValue));
    }
    return copy;
}

size_t simp_gc_heap_count(void) {
    return object_count;
}

typedef struct SimpDemoNative {
    const SimpClassMeta *metadata;
    void *owner;
    int32_t marker;
} SimpDemoNative;

static void require_demo_native_receiver(void *receiver) {
    const SimpDemoNative *native = (const SimpDemoNative *)receiver;
    if (native == NULL || native->metadata == NULL ||
        native->metadata->name_length != sizeof("Native") - 1 ||
        memcmp(native->metadata->name, "Native", sizeof("Native") - 1) != 0 ||
        native->marker != 91) {
        abort();
    }
}

/* Every shim checks the receiver class and marker, so omitting or misordering
 * the implicit receiver in generated calls fails the end-to-end test. */
int32_t simp_method_demo_abs(void *receiver, int32_t value) {
    require_demo_native_receiver(receiver);
    return abs(value);
}

void simp_method_demo_ignore(void *receiver, int32_t value) {
    require_demo_native_receiver(receiver);
    (void)value;
}

int32_t simp_method_demo_string_length(void *receiver, SimpString text) {
    require_demo_native_receiver(receiver);
    return (int32_t)text.length;
}

SimpString simp_method_demo_string_identity(void *receiver, SimpString text) {
    require_demo_native_receiver(receiver);
    return text;
}

void *simp_method_demo_identity(void *receiver, void *object) {
    require_demo_native_receiver(receiver);
    return object;
}
