/**
 * @file RuntimeDemoShims.c
 * @brief Demonstration C shims for out-of-line native-bound methods.
 * @author Generated by GitHub Copilot
 *
 * See RuntimeDemoShims.h for why this file exists separately from
 * RuntimeGc.c: it has nothing to do with garbage collection and exists only
 * to give tests/functional/positive_extern_functions.simp real C-bound
 * method implementations to link against.
 */
#include "simp/RuntimeDemoShims.h"

#include <stdlib.h>
#include <string.h>

typedef struct SimpDemoNative {
    const SimpClassMeta *metadata;
    void *owner;
    int32_t marker;
} SimpDemoNative;

static void require_demo_native_receiver(void *receiver) {
    const SimpDemoNative *native = (const SimpDemoNative *)receiver;
    if (native == NULL || native->metadata == NULL ||
        native->metadata->name_length != sizeof("Native") - 1 ||
        memcmp(native->metadata->name, "Native", sizeof("Native") - 1) != 0 ||
        native->marker != 91) {
        abort();
    }
}

int32_t simp_method_demo_abs(void *receiver, int32_t value) {
    require_demo_native_receiver(receiver);
    return abs(value);
}

void simp_method_demo_ignore(void *receiver, int32_t value) {
    require_demo_native_receiver(receiver);
    (void)value;
}

int32_t simp_method_demo_string_length(void *receiver, SimpString text) {
    require_demo_native_receiver(receiver);
    return (int32_t)text.length;
}

SimpString simp_method_demo_string_identity(void *receiver, SimpString text) {
    require_demo_native_receiver(receiver);
    return text;
}

void *simp_method_demo_identity(void *receiver, void *object) {
    require_demo_native_receiver(receiver);
    return object;
}
