/**
 * @file RuntimeThreads.c
 * @brief pthread-backed Thread/Semaphore native bindings.
 * @author Generated by GitHub Copilot
 *
 * See RuntimeThreads.h for the Simple-side declarations these symbols are
 * meant to be bound to, and "Threads" in SIMPLE-LANGUAGE-NOTES.md for the
 * cooperative global-lock design these functions participate in via
 * simp_runtime_thread_enter/exit and simp_runtime_gil_release/acquire.
 */
#include "simp/RuntimeThreads.h"

#include <pthread.h>
#include <stdlib.h>
#include <string.h>

typedef struct SimpThreadHandle {
    pthread_t thread;
} SimpThreadHandle;

typedef struct SimpThreadStartArgs {
    void *receiver;
    void (*run_thunk)(void *);
    pthread_mutex_t ready_mutex;
    pthread_cond_t ready_cond;
    int ready;
} SimpThreadStartArgs;

typedef struct SimpSemaphoreObject {
    pthread_mutex_t mutex;
    pthread_cond_t cond;
    int64_t count;
} SimpSemaphoreObject;

static void (*find_run_method(const SimpClassMeta *metadata))(void *) {
    if (metadata == NULL) return NULL;
    for (uint64_t index = 0; index < metadata->method_count; ++index) {
        const SimpMethodMeta *candidate = &metadata->methods[index];
        if (candidate->name_length == 3 &&
            memcmp(candidate->name, "run", 3) == 0) {
            return (void (*)(void *))candidate->code;
        }
    }
    return NULL;
}

static void *simp_thread_trampoline(void *raw_args) {
    SimpThreadStartArgs *args = (SimpThreadStartArgs *)raw_args;
    void *receiver = args->receiver;
    void (*run_thunk)(void *) = args->run_thunk;

    /* Registers this OS thread with the collector and acquires the global
     * lock (see simp_runtime_thread_enter's doc comment): from this point
     * on this thread is a full participant in the single-lock threading
     * model and may safely run Simple code / touch the managed heap. */
    simp_runtime_thread_enter();
    SimpRootFrame frame = {0};
    void *const slots[1] = {&receiver};
    simp_gc_push_or_abort(&frame, slots, 1);

    /* Hand off root-protection of the receiver to this thread's own frame
     * before signaling the spawner, so there is never a window where
     * neither thread's root frame protects it (see simp_thread_start). */
    pthread_mutex_lock(&args->ready_mutex);
    args->ready = 1;
    pthread_cond_signal(&args->ready_cond);
    pthread_mutex_unlock(&args->ready_mutex);

    run_thunk(receiver);

    simp_gc_pop_or_abort(&frame);
    simp_runtime_thread_exit();
    return NULL;
}

void *simp_thread_start(void *receiver) {
    if (receiver == NULL) abort();
    /* `receiver` is whatever subobject view the compiler passed for this
     * (statically Thread-typed) call; its own metadata field only lists
     * Thread's own declared methods. simp_gc_root resolves to the true,
     * most-derived allocated object, whose metadata table is the merged
     * vtable that actually includes the subclass's "run" method. */
    void *root = simp_gc_root(receiver);
    const SimpClassMeta *metadata = *(const SimpClassMeta *const *)root;
    void (*run_thunk)(void *) = find_run_method(metadata);
    if (run_thunk == NULL) abort();

    SimpThreadStartArgs *args = (SimpThreadStartArgs *)malloc(sizeof(*args));
    if (args == NULL) abort();
    args->receiver = root;
    args->run_thunk = run_thunk;
    args->ready = 0;
    if (pthread_mutex_init(&args->ready_mutex, NULL) != 0) abort();
    if (pthread_cond_init(&args->ready_cond, NULL) != 0) abort();

    /* Root the object from this (spawning) thread until the new thread
     * has rooted it on its own stack (see simp_thread_trampoline). */
    SimpRootFrame frame = {0};
    void *const slots[1] = {&root};
    simp_gc_push_or_abort(&frame, slots, 1);

    SimpThreadHandle *handle = (SimpThreadHandle *)malloc(sizeof(*handle));
    if (handle == NULL) abort();

    if (pthread_create(&handle->thread, NULL, simp_thread_trampoline, args) != 0) {
        simp_gc_pop_or_abort(&frame);
        pthread_mutex_destroy(&args->ready_mutex);
        pthread_cond_destroy(&args->ready_cond);
        free(args);
        free(handle);
        abort();
    }

    /* Wait for the child to take over root-protection of the receiver.
     * Release the global lock first: the child cannot make progress (it
     * needs the same lock to register itself) while this thread holds it. */
    simp_runtime_gil_release();
    pthread_mutex_lock(&args->ready_mutex);
    while (!args->ready) {
        pthread_cond_wait(&args->ready_cond, &args->ready_mutex);
    }
    pthread_mutex_unlock(&args->ready_mutex);
    simp_runtime_gil_acquire();

    simp_gc_pop_or_abort(&frame);
    pthread_mutex_destroy(&args->ready_mutex);
    pthread_cond_destroy(&args->ready_cond);
    free(args);
    return handle;
}

void simp_thread_join(void *receiver, void *worker) {
    (void)receiver;
    if (worker == NULL) abort();
    SimpThreadHandle *handle = (SimpThreadHandle *)worker;
    /* Release the global lock so the joined thread (and any other thread)
     * can keep making progress while this thread blocks. */
    simp_runtime_gil_release();
    const int joined = pthread_join(handle->thread, NULL);
    simp_runtime_gil_acquire();
    if (joined != 0) abort();
    free(handle);
}

void *simp_semaphore_create(void *receiver, int32_t initial_count) {
    (void)receiver;
    if (initial_count < 0) abort();
    SimpSemaphoreObject *semaphore =
        (SimpSemaphoreObject *)malloc(sizeof(*semaphore));
    if (semaphore == NULL) abort();
    if (pthread_mutex_init(&semaphore->mutex, NULL) != 0) abort();
    if (pthread_cond_init(&semaphore->cond, NULL) != 0) abort();
    semaphore->count = initial_count;
    return semaphore;
}

void simp_semaphore_wait(void *receiver, void *semaphore) {
    (void)receiver;
    if (semaphore == NULL) abort();
    SimpSemaphoreObject *sem = (SimpSemaphoreObject *)semaphore;
    /* The semaphore's own mutex/condvar synchronize its count independent
     * of the global lock; releasing the global lock here only prevents a
     * blocked wait from starving every other Simple thread, exactly like
     * simp_thread_join above. */
    simp_runtime_gil_release();
    pthread_mutex_lock(&sem->mutex);
    while (sem->count <= 0) {
        pthread_cond_wait(&sem->cond, &sem->mutex);
    }
    --sem->count;
    pthread_mutex_unlock(&sem->mutex);
    simp_runtime_gil_acquire();
}

void simp_semaphore_signal(void *receiver, void *semaphore) {
    (void)receiver;
    if (semaphore == NULL) abort();
    SimpSemaphoreObject *sem = (SimpSemaphoreObject *)semaphore;
    pthread_mutex_lock(&sem->mutex);
    ++sem->count;
    pthread_cond_signal(&sem->cond);
    pthread_mutex_unlock(&sem->mutex);
}

void simp_semaphore_release(void *receiver, void *semaphore) {
    (void)receiver;
    if (semaphore == NULL) abort();
    SimpSemaphoreObject *sem = (SimpSemaphoreObject *)semaphore;
    pthread_mutex_destroy(&sem->mutex);
    pthread_cond_destroy(&sem->cond);
    free(sem);
}
