/**
 * @file SemanticExpressions.cpp
 * @brief Expression and assignment-target semantic analysis.
 * @author Generated by GitHub Copilot
 */
#include "simp/SemanticAnalyzer.hpp"

#include "simp/Diagnostic.hpp"

#include <algorithm>
#include <charconv>
#include <cstdint>
#include <cmath>
#include <iostream>

namespace simp {
namespace {

bool isArrayType(const std::string& type) {
    return type == "array";
}

bool isMapType(const std::string& type) {
    return type == "map";
}

bool isBufferType(const std::string& type) {
    return type == "buffer";
}

bool isOpaqueHandleType(const std::string& type) {
    return type == "handle";
}

bool isDynamicValueType(const std::string& type) {
    return type == "any";
}

bool expressionNamePath(const Expression& expression, std::string& name) {
    if (expression.kind == ExpressionKind::Identifier) {
        name = expression.value;
        return true;
    }
    if (expression.kind != ExpressionKind::Member || !expression.left ||
        !expressionNamePath(*expression.left, name)) {
        return false;
    }
    name += "." + expression.value;
    return true;
}

} // namespace

bool SemanticAnalyzer::resolveBaseQualifier(Expression& receiver,
                                           Expression*& root,
                                           const ClassDeclaration*& view,
                                           std::vector<std::string>& path) {
    std::vector<std::string> reversed;
    Expression* cursor = &receiver;
    while (cursor->kind == ExpressionKind::Member) {
        reversed.push_back(cursor->value);
        cursor = cursor->left.get();
    }
    if (reversed.empty()) return false;
    root = cursor;
    std::string rootType = analyzeExpression(*root);
    const auto found = classes_.find(rootType);
    if (found == classes_.end()) return false;
    view = found->second;
    for (auto name = reversed.rbegin(); name != reversed.rend(); ++name) {
        const auto base = std::find(view->baseClassNames.begin(),
                                    view->baseClassNames.end(), *name);
        if (base == view->baseClassNames.end()) return false;
        const auto baseClass = classes_.find(*name);
        if (baseClass == classes_.end()) return false;
        path.push_back(*name);
        view = baseClass->second;
    }
    return true;
}

std::string SemanticAnalyzer::analyzeExpression(Expression& expression,
                                                const std::string& expectedType) {
    switch (expression.kind) {
    case ExpressionKind::Integer: {
        const auto* begin = expression.value.data();
        const auto* end = begin + expression.value.size();
        // A plain, unsuffixed integer literal is also a valid unsigned
        // literal when the surrounding context expects `unsigned` (the `u`
        // suffix remains required everywhere else, including plain `int`
        // contexts and `any`).
        if (expectedType == "unsigned") {
            std::uint64_t unsignedValue = 0;
            const auto parsedUnsigned = std::from_chars(begin, end, unsignedValue);
            if (parsedUnsigned.ec != std::errc{} || parsedUnsigned.ptr != end) {
                throw DiagnosticError(expression.location,
                                      "integer literal is outside the unsigned 64-bit range");
            }
            return "unsigned";
        }
        std::int32_t value = 0;
        const auto parsed = std::from_chars(begin, end, value);
        if (parsed.ec != std::errc{} || parsed.ptr != end) {
            throw DiagnosticError(expression.location,
                                  "integer literal is outside the signed 32-bit range");
        }
        return "int";
    }
    case ExpressionKind::Unsigned: {
        const auto length = expression.value.size() - 1;
        std::uint64_t value = 0;
        const auto parsed = std::from_chars(expression.value.data(),
                                            expression.value.data() + length, value);
        if (length == 0 || parsed.ec != std::errc{} ||
            parsed.ptr != expression.value.data() + length) {
            throw DiagnosticError(expression.location,
                                  "unsigned literal is outside the 64-bit range");
        }
        return "unsigned";
    }
    case ExpressionKind::Float: {
        double value = 0;
        const auto parsed = std::from_chars(expression.value.data(),
                                            expression.value.data() + expression.value.size(),
                                            value);
        if (parsed.ec != std::errc{} ||
            parsed.ptr != expression.value.data() + expression.value.size() ||
            !std::isfinite(value)) {
            throw DiagnosticError(expression.location,
                                  "floating-point literal is outside the finite double range");
        }
        return "float";
    }
    case ExpressionKind::Boolean:
        return "bool";
    case ExpressionKind::String:
        return "string";
    case ExpressionKind::Null:
        return "null";
    case ExpressionKind::Identifier: {
        const auto index = findSymbolIndex(expression.value);
        if (index != symbols_.size()) {
            if (!symbols_[index].initialized) {
                throw DiagnosticError(expression.location,
                                      "variable '" + expression.value + "' may be uninitialized");
            }
            return symbols_[index].type;
        }
        if (currentClass_ != nullptr) {
            if (countFields(*currentClass_, expression.value) != 0 &&
                accessibleMemberCount(*currentClass_, expression.value, false) == 0) {
                throw DiagnosticError(expression.location,
                                      "field '" + expression.value +
                                          "' is not accessible in this class");
            }
            if (countFields(*currentClass_, expression.value) > 1) {
                throw DiagnosticError(expression.location,
                                      "ambiguous inherited field '" + expression.value +
                                          "'; qualify it through a base class");
            }
            if (const auto* field = findField(*currentClass_, expression.value)) {
                if (!memberAccessible(*currentClass_, expression.value, false)) {
                    throw DiagnosticError(expression.location,
                                          "field '" + expression.value +
                                              "' is not accessible in this class");
                }
                return field->type;
            }
        }
        throw DiagnosticError(expression.location,
                              "undefined variable '" + expression.value + "' or field");
    }
    case ExpressionKind::Member: {
        Expression* root = nullptr;
        const ClassDeclaration* owner = nullptr;
        std::vector<std::string> path;
        const bool qualified = resolveBaseQualifier(*expression.left, root, owner, path);
        if (!qualified) {
            const auto receiverType = analyzeExpression(*expression.left);
            if (isArrayType(receiverType)) {
                if (expression.value == "length") return "int";
                throw DiagnosticError(expression.location,
                                      "arrays support only the read-only 'length' member");
            }
            if (isMapType(receiverType)) {
                if (expression.value == "length") return "int";
                if (expression.value == "contains" || expression.value == "remove") {
                    throw DiagnosticError(expression.location,
                                          "map '" + expression.value +
                                              "' must be called with a string key");
                }
                throw DiagnosticError(expression.location,
                                      "maps support only the read-only 'length' member and "
                                      "'contains' and 'remove' methods");
            }
            if (isBufferType(receiverType)) {
                if (expression.value == "length") return "int";
                throw DiagnosticError(expression.location,
                                      "buffers support only the read-only 'length' member");
            }
            if (isOpaqueHandleType(receiverType)) {
                throw DiagnosticError(expression.location,
                                      "handle has no built-in operations");
            }
            if (isDynamicValueType(receiverType)) {
                throw DiagnosticError(expression.location,
                                      "'any' has no members; assign it to a typed variable "
                                      "first to extract its value");
            }
            owner = findClass(receiverType, expression.location);
        }
        const auto matches = countFields(*owner, expression.value);
        const auto accessibleMatches = accessibleMemberCount(*owner, expression.value, false);
        if (accessibleMatches > 1) {
            throw DiagnosticError(expression.location,
                                  "ambiguous inherited field '" + expression.value +
                                      "'; qualify it through a base class");
        }
        const auto& accessOwner = path.empty() ? *owner : *classes_.at(analyzeExpression(*root));
        if (matches != 0 &&
            (accessibleMatches == 0 ||
             (!path.empty() && !basePathAccessible(accessOwner, path)))) {
            throw DiagnosticError(expression.location,
                                  "field '" + expression.value +
                                      "' is not accessible through this inheritance path");
        }
        if (const auto* field = findField(*owner, expression.value)) {
            return field->type;
        }
        throw DiagnosticError(expression.location,
                              "class '" + owner->name + "' has no field '" + expression.value + "'");
    }
    case ExpressionKind::ArrayLiteral: {
        // Arrays are heterogeneous bags. Collection references remain tagged values,
        // so nested arrays share the same precise GC tracing as maps.
        for (auto& element : expression.arguments) {
            const auto actualType = analyzeExpression(*element);
            const bool validElement = actualType == "int" || actualType == "bool" ||
                                      actualType == "float" || actualType == "unsigned" ||
                                      actualType == "string" ||
                                      actualType == "null" || actualType == "any" ||
                                      isMapType(actualType) || isArrayType(actualType) ||
                                      isBufferType(actualType) ||
                                      isOpaqueHandleType(actualType) ||
                                      classes_.find(actualType) != classes_.end();
            if (!validElement) {
                throw DiagnosticError(element->location,
                                      "array elements must be scalar, string, a class reference, "
                                  "an array, a map, a buffer, a handle, null, or 'any'; found " +
                                      actualType);
            }
        }
        return "array";
    }
    case ExpressionKind::MapLiteral: {
        for (std::size_t index = 0; index < expression.arguments.size(); index += 2) {
            auto& key = *expression.arguments[index];
            if (analyzeExpression(key) != "string") {
                throw DiagnosticError(key.location,
                                      "map keys must have type string");
            }
            const auto valueType = analyzeExpression(*expression.arguments[index + 1]);
            const bool validValue = valueType == "int" || valueType == "bool" ||
                                    valueType == "float" || valueType == "unsigned" ||
                                    valueType == "string" ||
                                    valueType == "null" || valueType == "any" ||
                                    valueType == "array" || valueType == "map" ||
                                    valueType == "buffer" || valueType == "handle" ||
                                    classes_.find(valueType) != classes_.end();
            if (!validValue) {
                throw DiagnosticError(expression.arguments[index + 1]->location,
                                      "map values must be scalar, string, a collection, a class "
                                      "reference, a buffer, a handle, null, or 'any'; found " +
                                          valueType);
            }
        }
        return "map";
    }
    case ExpressionKind::Index:
    case ExpressionKind::Slice: {
        const auto collectionType = analyzeExpression(*expression.left);
        if (isArrayType(collectionType)) {
            for (auto& bound : expression.arguments) {
                if (analyzeExpression(*bound) != "int") {
                    throw DiagnosticError(bound->location,
                                          "array index and slice bounds must be int");
                }
            }
            return expression.kind == ExpressionKind::Slice ? "array" : "any";
        }
        if (isMapType(collectionType) && expression.kind == ExpressionKind::Slice) {
            for (auto& bound : expression.arguments) {
                if (analyzeExpression(*bound) != "int") {
                    throw DiagnosticError(bound->location,
                                          "map index and slice bounds must be int");
                }
            }
            return "map";
        }
        if (isMapType(collectionType) && expression.kind == ExpressionKind::Index) {
            auto& key = *expression.arguments.front();
            if (analyzeExpression(key) != "string") {
                throw DiagnosticError(key.location,
                                      "map keys must have type string");
            }
            return "any";
        }
        if (isBufferType(collectionType)) {
            for (auto& bound : expression.arguments) {
                if (analyzeExpression(*bound) != "int") {
                    throw DiagnosticError(bound->location,
                                          "buffer index and slice bounds must be int");
                }
            }
            return expression.kind == ExpressionKind::Slice ? "buffer" : "unsigned";
        }
        throw DiagnosticError(expression.location,
                              expression.kind == ExpressionKind::Slice
                                  ? "slicing requires an array, map, or buffer"
                                  : "indexing requires an array, map, or buffer");
    }
    case ExpressionKind::BufferConstructor:
        if (expression.arguments.size() != 1) {
            throw DiagnosticError(expression.location,
                                  "buffer constructor expects one int length");
        }
        if (analyzeExpression(*expression.arguments.front()) != "int") {
            throw DiagnosticError(expression.arguments.front()->location,
                                  "buffer length must have type int");
        }
        return "buffer";
    case ExpressionKind::ConstructorCall: {
        expression.value =
            resolveClassName(expression.value, currentNamespace_, expression.location);
        const auto* owner = findClass(expression.value, expression.location);
        const MethodDeclaration* constructor = nullptr;
        for (const auto& method : owner->methods) {
            if (method.constructor) {
                constructor = &method;
                break;
            }
        }
        if (constructor != nullptr &&
            !memberAccessible(*owner, constructor->name, true)) {
            throw DiagnosticError(expression.location,
                                  "constructor for class '" + owner->name +
                                      "' is not accessible here");
        }
        if (constructor == nullptr) {
            if (!expression.arguments.empty()) {
                throw DiagnosticError(expression.location,
                                      "class '" + owner->name + "' has no constructor");
            }
            for (const auto& baseName : virtualBaseNames(*owner)) {
                const auto* base = findClass(baseName, expression.location);
                for (const auto& method : base->methods) {
                    if (method.constructor && !method.parameters.empty()) {
                        throw DiagnosticError(
                            expression.location,
                            "class '" + owner->name +
                                "' needs an explicit constructor to initialize virtual base '" +
                                baseName + "'");
                    }
                }
            }
            return owner->name;
        }
        if (constructor->parameters.size() != expression.arguments.size()) {
            throw DiagnosticError(expression.location,
                                  "constructor argument count does not match class '" + owner->name + "'");
        }
        for (std::size_t index = 0; index < expression.arguments.size(); ++index) {
            const auto argumentType =
                analyzeExpression(*expression.arguments[index], constructor->parameters[index].type);
            if (!isAssignable(constructor->parameters[index].type, argumentType) &&
                !(argumentType == "null" &&
                  classes_.find(constructor->parameters[index].type) != classes_.end())) {
                throw DiagnosticError(expression.arguments[index]->location,
                                      "constructor argument type does not match parameter '" +
                                          constructor->parameters[index].name + "'");
            }
        }
        const auto virtualBases = virtualBaseNames(*owner);
        for (const auto& baseName : virtualBases) {
            const auto* base = findClass(baseName, expression.location);
            const MethodDeclaration* baseConstructor = nullptr;
            for (const auto& method : base->methods) {
                if (method.constructor) {
                    baseConstructor = &method;
                    break;
                }
            }
            if (baseConstructor == nullptr || baseConstructor->parameters.empty()) continue;
            const bool initialized = std::any_of(
                constructor->body.begin(), constructor->body.end(),
                [&baseName](const Statement& statement) {
                    return statement.kind == StatementKind::SuperConstructorCall &&
                           statement.virtualBaseInitializer && statement.name == baseName;
                });
            if (!initialized) {
                throw DiagnosticError(
                    expression.location,
                    "most-derived constructor must initialize virtual base '" + baseName +
                        "' with super.virtual " + baseName + "(...)");
            }
        }
        return owner->name;
    }
    case ExpressionKind::Call: {
        std::string qualifiedName;
        if (expression.left &&
            expressionNamePath(*expression.left, qualifiedName) &&
            expression.left->kind == ExpressionKind::Member) {
            std::string firstName;
            auto firstDot = qualifiedName.find('.');
            firstName = qualifiedName.substr(0, firstDot);
            const bool localBinding = findSymbolIndex(firstName) != symbols_.size() ||
                (currentClass_ != nullptr &&
                 findField(*currentClass_, firstName) != nullptr);
            if (!localBinding && hasNamespaceOrClass(firstName, currentNamespace_)) {
                expression.value = qualifiedName;
                expression.kind = ExpressionKind::ConstructorCall;
                expression.left.reset();
                return analyzeExpression(expression);
            }
        }
        if (expression.left->kind != ExpressionKind::Member) {
            throw DiagnosticError(expression.location, "only object method calls are supported");
        }
        auto& target = *expression.left;
        Expression* root = nullptr;
        const ClassDeclaration* owner = nullptr;
        std::vector<std::string> basePath;
        const bool qualified =
            resolveBaseQualifier(*target.left, root, owner, basePath);
        if (!qualified) {
            const auto receiverType = analyzeExpression(*target.left);
            if (isMapType(receiverType)) {
                if (target.value != "contains" && target.value != "remove") {
                    throw DiagnosticError(target.location,
                                          "maps support only the 'contains' and 'remove' methods");
                }
                if (expression.arguments.size() != 1) {
                    throw DiagnosticError(expression.location,
                                          "map '" + target.value +
                                              "' expects one string key");
                }
                if (analyzeExpression(*expression.arguments.front()) != "string") {
                    throw DiagnosticError(expression.arguments.front()->location,
                                          "map key must have type string");
                }
                return "int";
            }
            if (isBufferType(receiverType)) {
                if (target.value != "resize" && target.value != "clear" &&
                    target.value != "append") {
                    throw DiagnosticError(target.location,
                                          "buffers support only resize(int), clear(), and "
                                          "append(int or unsigned)");
                }
                if (target.value == "resize") {
                    if (expression.arguments.size() != 1 ||
                        analyzeExpression(*expression.arguments.front()) != "int") {
                        throw DiagnosticError(expression.location,
                                              "buffer 'resize' expects one int length");
                    }
                    return "void";
                }
                if (target.value == "clear") {
                    if (!expression.arguments.empty()) {
                        throw DiagnosticError(expression.location,
                                              "buffer 'clear' expects no arguments");
                    }
                    return "void";
                }
                if (target.value == "append") {
                    if (expression.arguments.size() != 1) {
                        throw DiagnosticError(expression.location,
                                              "buffer 'append' expects one int or unsigned value");
                    }
                    const auto valueType = analyzeExpression(*expression.arguments.front());
                    if (valueType != "int" && valueType != "unsigned") {
                        throw DiagnosticError(expression.arguments.front()->location,
                                              "buffer append value must have type int or unsigned");
                    }
                    return "void";
                }
            }
            if (isOpaqueHandleType(receiverType)) {
                throw DiagnosticError(target.location,
                                      "handle has no built-in operations");
            }
            owner = findClass(receiverType, target.location);
        }
        if (target.value == "destroy") {
            if (qualified) {
                throw DiagnosticError(target.location,
                                      "qualified destructor calls are not supported");
            }
            const auto findDestructor = [this](const auto& self,
                                               const ClassDeclaration& declaration)
                -> const MethodDeclaration* {
                for (const auto& candidate : declaration.methods) {
                    if (candidate.destructor) return &candidate;
                }
                for (const auto& baseName : declaration.baseClassNames) {
                    const auto base = classes_.find(baseName);
                    if (base != classes_.end()) {
                        if (const auto* inherited = self(self, *base->second))
                            return inherited;
                    }
                }
                return nullptr;
            };
            const auto* destructor = findDestructor(findDestructor, *owner);
            if (destructor == nullptr) {
                throw DiagnosticError(target.location,
                                      "class '" + owner->name + "' has no destructor");
            }
            if (accessibleMemberCount(*owner, "destroy", true) == 0) {
                throw DiagnosticError(target.location,
                                      "destructor for class '" + owner->name +
                                          "' is not accessible here");
            }
            if (!expression.arguments.empty()) {
                throw DiagnosticError(expression.location, "destructor takes no arguments");
            }
            std::cerr << target.location.file << ":" << target.location.line << ":"
                      << target.location.column
                      << ": warning: explicit destructor call does not reclaim the object\n";
            return "void";
        }
        const auto methodMatches = countMethods(*owner, target.value);
        const auto accessibleMethods = accessibleMemberCount(*owner, target.value, true);
        if (accessibleMethods > 1) {
            throw DiagnosticError(target.location,
                                  "ambiguous inherited method '" + target.value +
                                      "'; qualify it through a base class");
        }
        const auto& accessOwner =
            basePath.empty() ? *owner : *classes_.at(analyzeExpression(*root));
        if (methodMatches != 0 &&
            (accessibleMethods == 0 ||
             (!basePath.empty() && !basePathAccessible(accessOwner, basePath)))) {
            throw DiagnosticError(target.location,
                                  "method '" + target.value +
                                      "' is not accessible through this inheritance path");
        }
        const auto* method = findMethod(*owner, target.value);
        if (method == nullptr) {
            throw DiagnosticError(target.location,
                                  "class '" + owner->name + "' has no method '" + target.value + "'");
        }
        if (method->parameters.size() != expression.arguments.size()) {
            throw DiagnosticError(expression.location,
                                  "method '" + target.value + "' argument count mismatch");
        }
        for (std::size_t index = 0; index < expression.arguments.size(); ++index) {
            const auto argumentType =
                analyzeExpression(*expression.arguments[index], method->parameters[index].type);
            if (!isAssignable(method->parameters[index].type, argumentType) &&
                !(argumentType == "null" &&
                  classes_.find(method->parameters[index].type) != classes_.end())) {
                throw DiagnosticError(expression.arguments[index]->location,
                                      "method argument type does not match parameter '" +
                                          method->parameters[index].name + "'");
            }
        }
        return method->returnType;
    }
    case ExpressionKind::Cast: {
        // Explicit scalar cast (int/unsigned <-> float), same model as C:
        // widening int/unsigned to float is always exact for values in the
        // ordinary range, and narrowing float to int/unsigned truncates
        // toward zero, discarding any fractional part.
        const auto operand = analyzeExpression(*expression.arguments.front());
        const auto& target = expression.value;
        const bool widening = target == "float" && (operand == "int" || operand == "unsigned");
        const bool narrowing = (target == "int" || target == "unsigned") && operand == "float";
        if (!widening && !narrowing) {
            throw DiagnosticError(expression.location,
                                  "cannot cast " + operand + " to " + target +
                                      "; only int/unsigned <-> float conversions are supported");
        }
        return target;
    }
    case ExpressionKind::Unary: {
        const auto operand = analyzeExpression(*expression.left);
        if (expression.value == "!") {
            if (operand != "bool") {
                throw DiagnosticError(expression.location,
                                      "logical negation requires a bool operand");
            }
            return "bool";
        }
        if ((expression.value == "+" && (operand == "int" || operand == "float" ||
                                         operand == "unsigned")) ||
            (expression.value == "-" && (operand == "int" || operand == "float"))) {
            return operand;
        }
        throw DiagnosticError(expression.location,
                              "unary operator '" + expression.value +
                                  "' does not support operand type " + operand);
    }
    case ExpressionKind::Binary: {
        const auto left = analyzeExpression(*expression.left);
        const auto right = analyzeExpression(*expression.right);
        const auto& operation = expression.value;
        if (operation == "&&" || operation == "||") {
            if (left != "bool" || right != "bool") {
                throw DiagnosticError(expression.location,
                                      "logical operator '" + operation +
                                          "' requires bool operands");
            }
            return "bool";
        }
        if (operation == "==" || operation == "!=") {
            // Universal-null model (confirmed): every nullable type (all
            // reference types, plus scalars now that they may hold null as
            // locals) may be compared against the null literal with `==`/
            // `!=`. This is not a general operator-expression exception for
            // buffer/handle/string; it is the same null-check every
            // null-capable type supports.
            const auto isNullComparable = [this](const std::string& type) {
                return type == "buffer" || type == "handle" || type == "string" ||
                       type == "array" || type == "map" || type == "int" ||
                       type == "bool" || type == "float" || type == "unsigned" ||
                       classes_.find(type) != classes_.end();
            };
            if ((isNullComparable(left) && right == "null") ||
                (left == "null" && isNullComparable(right))) {
                return "bool";
            }
            if (left != right ||
                (left != "int" && left != "bool" && left != "float" &&
                 left != "unsigned")) {
                throw DiagnosticError(expression.location,
                                      "equality requires matching int, bool, float, or unsigned "
                                      "operands");
            }
            return "bool";
        }
        const bool sameArithmeticType = left == right &&
            (left == "int" || left == "float" || left == "unsigned");
        if (operation == "<" || operation == "<=" || operation == ">" ||
            operation == ">=") {
            if (!sameArithmeticType) {
                throw DiagnosticError(expression.location,
                                      "comparison operator '" + operation +
                                          "' requires matching int, float, or unsigned operands");
            }
            return "bool";
        }
        if (!sameArithmeticType ||
            (operation == "%" && left == "float")) {
            const auto reason = operation == "%" && left == "float"
                                    ? " (float remainder is unsupported)"
                                    : "";
            throw DiagnosticError(expression.location,
                                  "operator '" + operation +
                                      "' requires matching int, float, or unsigned operands" +
                                      reason);
        }
        return left;
    }
    }
    throw DiagnosticError(expression.location, "invalid expression");
}

std::string SemanticAnalyzer::analyzeLValue(Expression& expression) {
    if (expression.kind == ExpressionKind::Identifier) {
        const auto index = findSymbolIndex(expression.value);
        if (index != symbols_.size()) {
            return symbols_[index].type;
        }
        if (currentClass_ != nullptr) {
            if (countFields(*currentClass_, expression.value) != 0 &&
                accessibleMemberCount(*currentClass_, expression.value, false) == 0) {
                throw DiagnosticError(expression.location,
                                      "field '" + expression.value +
                                          "' is not accessible in this class");
            }
            if (countFields(*currentClass_, expression.value) > 1) {
                throw DiagnosticError(expression.location,
                                      "ambiguous inherited field '" + expression.value +
                                          "'; qualify it through a base class");
            }
            if (const auto* field = findField(*currentClass_, expression.value)) {
                if (!memberAccessible(*currentClass_, expression.value, false)) {
                    throw DiagnosticError(expression.location,
                                          "field '" + expression.value +
                                              "' is not accessible in this class");
                }
                return field->type;
            }
        }
        throw DiagnosticError(expression.location,
                              "undefined variable '" + expression.value + "' or field");
    }
    if (expression.kind == ExpressionKind::Index) {
        const auto collectionType = analyzeExpression(*expression.left);
        if (isArrayType(collectionType)) {
            if (analyzeExpression(*expression.arguments.front()) != "int") {
                throw DiagnosticError(expression.arguments.front()->location,
                                      "array index must be int");
            }
            return "any";
        }
        if (isMapType(collectionType)) {
            auto& key = *expression.arguments.front();
            if (analyzeExpression(key) != "string") {
                throw DiagnosticError(key.location,
                                      "map keys must have type string");
            }
            return "any";
        }
        if (isBufferType(collectionType)) {
            if (analyzeExpression(*expression.arguments.front()) != "int") {
                throw DiagnosticError(expression.arguments.front()->location,
                                      "buffer index must be int");
            }
            return "buffer-byte";
        }
        throw DiagnosticError(expression.location,
                              "index assignment requires an array, map, or buffer");
    }
    if (expression.kind == ExpressionKind::Slice) {
        throw DiagnosticError(expression.location,
                              "slice expressions are copies and are not assignable");
    }
    if (expression.kind == ExpressionKind::Member) {
        Expression* root = nullptr;
        const ClassDeclaration* owner = nullptr;
        std::vector<std::string> path;
        const bool qualified = resolveBaseQualifier(*expression.left, root, owner, path);
        if (!qualified) {
            const auto receiverType = analyzeExpression(*expression.left);
            if (isArrayType(receiverType) && expression.value == "length") {
                throw DiagnosticError(expression.location, "array length is read-only");
            }
            if (isMapType(receiverType) && expression.value == "length") {
                throw DiagnosticError(expression.location, "map length is read-only");
            }
            owner = findClass(receiverType, expression.location);
        }
        const auto matches = countFields(*owner, expression.value);
        const auto accessibleMatches = accessibleMemberCount(*owner, expression.value, false);
        if (accessibleMatches > 1) {
            throw DiagnosticError(expression.location,
                                  "ambiguous inherited field '" + expression.value +
                                      "'; qualify it through a base class");
        }
        const auto& accessOwner = path.empty() ? *owner : *classes_.at(analyzeExpression(*root));
        if (matches != 0 &&
            (accessibleMatches == 0 ||
             (!path.empty() && !basePathAccessible(accessOwner, path)))) {
            throw DiagnosticError(expression.location,
                                  "field '" + expression.value +
                                      "' is not accessible through this inheritance path");
        }
        if (const auto* field = findField(*owner, expression.value)) {
            return field->type;
        }
        throw DiagnosticError(expression.location,
                              "class '" + owner->name + "' has no field '" + expression.value + "'");
    }
    throw DiagnosticError(expression.location, "assignment target must be a variable or object field");
}

} // namespace simp
