/**
 * @file SemanticAnalyzer.cpp
 * @brief Name, type, member, and definite-initialization analysis.
 * @author Generated by GitHub Copilot
 */
#include "simp/SemanticAnalyzer.hpp"

#include "simp/Diagnostic.hpp"

#include <algorithm>
#include <iostream>
#include <ostream>
#include <unordered_set>

namespace simp {
namespace {

bool containsReturn(const Statement& statement) {
    if (statement.kind == StatementKind::Return) return true;
    for (const auto& child : statement.body) {
        if (containsReturn(child)) return true;
    }
    for (const auto& child : statement.alternate) {
        if (containsReturn(child)) return true;
    }
    return false;
}

bool containsSuperCall(const Statement& statement) {
    if (statement.kind == StatementKind::SuperConstructorCall) return true;
    for (const auto& child : statement.body) {
        if (containsSuperCall(child)) return true;
    }
    for (const auto& child : statement.alternate) {
        if (containsSuperCall(child)) return true;
    }
    return false;
}

} // namespace

void SemanticAnalyzer::analyze(const Program& program) {
    scopes_.clear();
    symbols_.clear();
    classes_.clear();
    currentClass_ = nullptr;
    currentMethod_ = nullptr;
    for (const auto& declaration : program.classes) {
        if (!classes_.emplace(declaration.name, &declaration).second) {
            throw DiagnosticError(declaration.location,
                                  "duplicate class '" + declaration.name + "'");
        }
    }
    for (const auto& declaration : program.classes) {
        std::unordered_set<std::string> directBases;
        for (std::size_t index = 0; index < declaration.baseClassNames.size(); ++index) {
            const auto& baseName = declaration.baseClassNames[index];
            if (!directBases.emplace(baseName).second) {
                throw DiagnosticError(declaration.baseLocations[index],
                                      "duplicate base class '" + baseName + "'");
            }
            findClass(baseName, declaration.baseLocations[index]);
        }
        std::unordered_set<std::string> path{declaration.name};
        std::vector<const ClassDeclaration*> pending{&declaration};
        while (!pending.empty()) {
            const auto* ancestor = pending.back();
            pending.pop_back();
            for (std::size_t index = 0; index < ancestor->baseClassNames.size(); ++index) {
                const auto& baseName = ancestor->baseClassNames[index];
                if (!path.emplace(baseName).second) {
                    if (baseName == declaration.name) {
                        throw DiagnosticError(ancestor->baseLocations[index],
                                              "inheritance cycle involving class '" +
                                                  baseName + "'");
                    }
                    continue;
                }
                pending.push_back(findClass(baseName, ancestor->baseLocations[index]));
            }
        }
        const bool declaresDestructor = std::any_of(
            declaration.methods.begin(), declaration.methods.end(),
            [](const MethodDeclaration& method) { return method.destructor; });
        if (declaresDestructor &&
            (!declaration.baseClassNames.empty() ||
             std::any_of(classes_.begin(), classes_.end(), [this, &declaration](const auto& entry) {
                 return entry.first != declaration.name &&
                        isSubclassOf(entry.first, declaration.name);
             }))) {
            throw DiagnosticError(declaration.location,
                                  "destructors in inheritance hierarchies are not supported");
        }
        for (const auto& field : declaration.fields) {
            validateType(field.type, field.location);
        }
        for (const auto& method : declaration.methods) {
            if (method.destructor &&
                (method.returnType != "void" || !method.parameters.empty())) {
                throw DiagnosticError(method.location,
                                      "destructor must return void and take no parameters");
            }
            validateType(method.returnType, method.location, true);
            for (const auto& parameter : method.parameters) {
                validateType(parameter.type, parameter.location);
            }
        }
        for (std::size_t index = 0; index < declaration.fields.size(); ++index) {
            for (std::size_t other = index + 1; other < declaration.fields.size(); ++other) {
                if (declaration.fields[index].name == declaration.fields[other].name) {
                    throw DiagnosticError(declaration.fields[other].location,
                                          "duplicate field '" + declaration.fields[other].name +
                                              "' in class '" + declaration.name + "'");
                }
            }
        }
        if (!declaration.baseClassName.empty()) {
            const auto hasConstructor = std::any_of(
                declaration.methods.begin(), declaration.methods.end(),
                [](const MethodDeclaration& method) { return method.constructor; });
            if (!hasConstructor) {
                for (std::size_t index = 0; index < declaration.baseClassNames.size(); ++index) {
                    const auto* base = findClass(declaration.baseClassNames[index],
                                                 declaration.baseLocations[index]);
                    const bool baseHasConstructor = std::any_of(
                        base->methods.begin(), base->methods.end(),
                        [](const MethodDeclaration& method) { return method.constructor; });
                    if (baseHasConstructor) {
                        throw DiagnosticError(declaration.location,
                                              "class '" + declaration.name +
                                                  "' needs an explicit constructor because base '" +
                                                  base->name + "' has one");
                    }
                }
            }
            for (std::size_t index = 1; index < declaration.baseClassNames.size(); ++index) {
                const auto* base = findClass(declaration.baseClassNames[index],
                                             declaration.baseLocations[index]);
                if (std::any_of(base->methods.begin(), base->methods.end(),
                                [](const MethodDeclaration& method) {
                                    return method.constructor;
                                })) {
                    throw DiagnosticError(declaration.baseLocations[index],
                                          "constructors for secondary bases are not supported");
                }
            }
            for (const auto& field : declaration.fields) {
                for (std::size_t index = 0; index < declaration.baseClassNames.size(); ++index) {
                    const auto* base = findClass(declaration.baseClassNames[index],
                                                 declaration.baseLocations[index]);
                    if (countFields(*base, field.name) != 0) {
                        throw DiagnosticError(field.location,
                                              "field '" + field.name +
                                                  "' duplicates an inherited field");
                    }
                }
            }
            for (const auto& method : declaration.methods) {
                if (method.constructor) continue;
                for (const auto& baseName : declaration.baseClassNames) {
                    const auto* inherited =
                        findMethod(*findClass(baseName, declaration.baseLocation), method.name);
                    if (inherited == nullptr) continue;
                    bool sameSignature = inherited->returnType == method.returnType &&
                                         inherited->parameters.size() == method.parameters.size();
                    for (std::size_t index = 0;
                         sameSignature && index < method.parameters.size(); ++index) {
                        sameSignature = method.parameters[index].type ==
                                        inherited->parameters[index].type;
                    }
                    if (!sameSignature) {
                        throw DiagnosticError(method.location,
                                              "override of '" + method.name +
                                                  "' must preserve the inherited method signature");
                    }
                }
            }
        }
        for (std::size_t index = 0; index < declaration.methods.size(); ++index) {
            for (std::size_t other = index + 1; other < declaration.methods.size(); ++other) {
                if (declaration.methods[index].name == declaration.methods[other].name) {
                    throw DiagnosticError(declaration.methods[other].location,
                                          "duplicate method '" + declaration.methods[other].name +
                                              "' in class '" + declaration.name + "'");
                }
            }
        }
    }
    for (const auto& declaration : program.classes) {
        for (const auto& method : declaration.methods) {
            analyzeMethod(declaration, method);
        }
    }
    currentClass_ = nullptr;
    currentMethod_ = nullptr;
    scopes_.emplace_back();
    analyzeStatements(program.statements);
    scopes_.pop_back();
}

void SemanticAnalyzer::validateType(const std::string& type, const SourceLocation& location,
                                   bool allowVoid) const {
    if (type == "int" || type == "string" || (allowVoid && type == "void")) {
        return;
    }
    if (classes_.find(type) == classes_.end()) {
        throw DiagnosticError(location, "unknown type or class '" + type + "'");
    }
}

const ClassDeclaration* SemanticAnalyzer::findClass(const std::string& name,
                                                    const SourceLocation& location) const {
    const auto found = classes_.find(name);
    if (found == classes_.end()) {
        throw DiagnosticError(location, "unknown class '" + name + "'");
    }
    return found->second;
}

std::size_t SemanticAnalyzer::findSymbolIndex(const std::string& name) const {
    for (auto scope = scopes_.rbegin(); scope != scopes_.rend(); ++scope) {
        const auto found = scope->find(name);
        if (found != scope->end()) {
            return found->second;
        }
    }
    return symbols_.size();
}

std::vector<bool> SemanticAnalyzer::initializationState() const {
    std::vector<bool> state;
    state.reserve(symbols_.size());
    for (const auto& symbol : symbols_) {
        state.push_back(symbol.initialized);
    }
    return state;
}

void SemanticAnalyzer::restoreInitializationState(const std::vector<bool>& state) {
    for (std::size_t index = 0; index < state.size(); ++index) {
        symbols_[index].initialized = state[index];
    }
}

void SemanticAnalyzer::analyzeMethod(const ClassDeclaration& owner,
                                     const MethodDeclaration& method) {
    if (method.constructor && !owner.baseClassName.empty() &&
        (method.body.empty() ||
         method.body.front().kind != StatementKind::SuperConstructorCall)) {
        throw DiagnosticError(method.location,
                              "derived constructor must begin with super." +
                                  owner.baseClassName + "(...);");
    }
    if (method.returnType != "void" &&
        (method.body.empty() || method.body.back().kind != StatementKind::Return)) {
        throw DiagnosticError(method.location,
                              "non-void prototype methods must end with a direct return statement");
    }
    for (std::size_t index = 0; index < method.body.size(); ++index) {
        const bool directLeadingSuper = index == 0 &&
                                        method.body[index].kind ==
                                            StatementKind::SuperConstructorCall &&
                                        method.constructor &&
                                        !owner.baseClassName.empty() &&
                                        method.body[index].name == owner.baseClassName;
        if (containsSuperCall(method.body[index]) && !directLeadingSuper) {
            throw DiagnosticError(method.body[index].location,
                                  "super call must be the first direct constructor statement and name the direct base class");
        }
        const bool finalDirectReturn = index + 1 == method.body.size() &&
                                       method.body[index].kind == StatementKind::Return;
        if (containsReturn(method.body[index]) && !finalDirectReturn) {
            throw DiagnosticError(method.body[index].location,
                                  "return must be the final direct statement in a prototype method");
        }
    }
    currentClass_ = &owner;
    currentMethod_ = &method;
    scopes_.emplace_back();
    scopes_.emplace_back();
    for (const auto& parameter : method.parameters) {
        if (scopes_.back().find(parameter.name) != scopes_.back().end()) {
            throw DiagnosticError(parameter.location, "duplicate parameter '" + parameter.name + "'");
        }
        const auto index = symbols_.size();
        symbols_.push_back({parameter.name, parameter.type, true, parameter.location});
        scopes_.back().emplace(parameter.name, index);
    }
    analyzeStatements(method.body);
    scopes_.pop_back();
    scopes_.pop_back();
    currentClass_ = nullptr;
    currentMethod_ = nullptr;
}

void SemanticAnalyzer::analyzeStatements(const std::vector<Statement>& statements) {
    for (const auto& statement : statements) {
        analyzeStatement(statement);
    }
}

void SemanticAnalyzer::analyzeStatement(const Statement& statement) {
    switch (statement.kind) {
    case StatementKind::Declaration: {
        validateType(statement.declaredType, statement.location);
        auto& scope = scopes_.back();
        if (scope.find(statement.name) != scope.end()) {
            throw DiagnosticError(statement.location,
                                  "variable '" + statement.name + "' is already declared in this scope");
        }
        const auto index = symbols_.size();
        symbols_.push_back({statement.name, statement.declaredType, false, statement.location});
        scope.emplace(statement.name, index);
        if (!statement.expressions.empty()) {
            const auto initializerType = analyzeExpression(*statement.expressions.front());
            if (!isAssignable(statement.declaredType, initializerType) &&
                !(initializerType == "null" && classes_.find(statement.declaredType) != classes_.end())) {
                throw DiagnosticError(statement.expressions.front()->location,
                                      "cannot initialize " + statement.declaredType +
                                          " variable with " + initializerType);
            }
            symbols_[index].initialized = true;
        }
        return;
    }
    case StatementKind::SuperConstructorCall: {
        if (currentClass_ == nullptr || currentMethod_ == nullptr ||
            !currentMethod_->constructor || currentClass_->baseClassName.empty() ||
            statement.name != currentClass_->baseClassName) {
            throw DiagnosticError(statement.location,
                                  "super call must name the direct base class and appear in its constructor");
        }
        const auto* base = findClass(statement.name, statement.location);
        const MethodDeclaration* constructor = nullptr;
        for (const auto& candidate : base->methods) {
            if (candidate.constructor) {
                constructor = &candidate;
                break;
            }
        }
        if (constructor != nullptr &&
            !memberAccessible(*base, constructor->name, true)) {
            throw DiagnosticError(statement.location,
                                  "base constructor for class '" + base->name +
                                      "' is not accessible here");
        }
        const std::size_t expectedCount = constructor == nullptr ? 0 : constructor->parameters.size();
        if (statement.expressions.size() != expectedCount) {
            throw DiagnosticError(statement.location,
                                  "base constructor argument count does not match class '" +
                                      statement.name + "'");
        }
        for (std::size_t index = 0; index < statement.expressions.size(); ++index) {
            const auto actual = analyzeExpression(*statement.expressions[index]);
            const auto expected = constructor->parameters[index].type;
            if (!isAssignable(expected, actual) &&
                !(actual == "null" && classes_.find(expected) != classes_.end())) {
                throw DiagnosticError(statement.expressions[index]->location,
                                      "base constructor argument type does not match parameter '" +
                                          constructor->parameters[index].name + "'");
            }
        }
        return;
    }
    case StatementKind::Assignment: {
        const auto targetType = analyzeLValue(*statement.target);
        const auto valueType = analyzeExpression(*statement.expressions.front());
        if (!isAssignable(targetType, valueType) &&
            !(valueType == "null" && classes_.find(targetType) != classes_.end())) {
            throw DiagnosticError(statement.expressions.front()->location,
                                  "cannot assign " + valueType + " to " + targetType +
                                      " variable '" + statement.target->value + "'");
        }
        if (statement.target->kind == ExpressionKind::Identifier) {
            const auto index = findSymbolIndex(statement.target->value);
            if (index != symbols_.size()) {
                symbols_[index].initialized = true;
            }
        }
        return;
    }
    case StatementKind::Print: {
        std::vector<std::string> types;
        for (const auto& expression : statement.expressions) {
            types.push_back(analyzeExpression(*expression));
        }
        if (types.size() > 1) {
            for (std::size_t index = 1; index < types.size(); ++index) {
                if (types[index] != "int") {
                    throw DiagnosticError(statement.expressions[index]->location,
                                          "formatted print arguments must have type int");
                }
            }
        } else if (!types.empty() && types.front() != "int" && types.front() != "string") {
            throw DiagnosticError(statement.location, "print supports int or string values only");
        }
        return;
    }
    case StatementKind::If: {
        if (analyzeExpression(*statement.expressions.front()) != "int") {
            throw DiagnosticError(statement.expressions.front()->location,
                                  "if condition must have type int");
        }
        const auto before = initializationState();
        scopes_.emplace_back();
        analyzeStatements(statement.body);
        scopes_.pop_back();
        const auto thenState = initializationState();
        if (!statement.hasAlternate) {
            restoreInitializationState(before);
            return;
        }
        restoreInitializationState(before);
        scopes_.emplace_back();
        analyzeStatements(statement.alternate);
        scopes_.pop_back();
        const auto elseState = initializationState();
        for (std::size_t index = 0; index < before.size(); ++index) {
            symbols_[index].initialized = thenState[index] && elseState[index];
        }
        return;
    }
    case StatementKind::While:
        if (analyzeExpression(*statement.expressions.front()) != "int") {
            throw DiagnosticError(statement.expressions.front()->location,
                                  "while condition must have type int");
        } else {
            const auto before = initializationState();
            scopes_.emplace_back();
            analyzeStatements(statement.body);
            scopes_.pop_back();
            restoreInitializationState(before);
        }
        return;
    case StatementKind::Block:
        scopes_.emplace_back();
        analyzeStatements(statement.body);
        scopes_.pop_back();
        return;
    case StatementKind::Return: {
        if (currentMethod_ == nullptr) {
            throw DiagnosticError(statement.location, "return is only valid inside a class method");
        }
        if (currentMethod_->returnType == "void") {
            if (!statement.expressions.empty()) {
                throw DiagnosticError(statement.location, "void method cannot return a value");
            }
        } else {
            if (statement.expressions.empty()) {
                throw DiagnosticError(statement.location, "non-void method must return a value");
            }
            const auto returnType = analyzeExpression(*statement.expressions.front());
            if (!isAssignable(currentMethod_->returnType, returnType) &&
                !(returnType == "null" && classes_.find(currentMethod_->returnType) != classes_.end())) {
                throw DiagnosticError(statement.expressions.front()->location,
                                      "return type does not match method return type");
            }
        }
        return;
    }
    case StatementKind::Expression:
        if (analyzeExpression(*statement.expressions.front()) == "void") {
            return;
        }
        return;
    }
}

void SemanticAnalyzer::dumpSymbolTable(std::ostream& output) const {
    output << "Symbols:\n";
    for (const auto& symbol : symbols_) {
        output << "  " << symbol.type << " " << symbol.name << " ("
               << (symbol.initialized ? "initialized" : "uninitialized") << ") at "
               << symbol.location.line << ":" << symbol.location.column << '\n';
    }
}

} // namespace simp
