include_guard(GLOBAL)

set(CWHIP_SANITIZE "OFF" CACHE STRING "Sanitizers (OFF or address;undefined)")
option(CWHIP_COVERAGE "Enable Clang source-based coverage" OFF)
option(CWHIP_FUZZ "Build the Clang libFuzzer lexer/parser harness" OFF)
if(CWHIP_FUZZ AND NOT CWHIP_SANITIZE STREQUAL "address;undefined")
    message(FATAL_ERROR "CWHIP_FUZZ requires -DCWHIP_SANITIZE=address;undefined")
endif()
if(CWHIP_COVERAGE)
    if(NOT CMAKE_C_COMPILER_ID MATCHES "Clang" OR
       NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        message(FATAL_ERROR "CWHIP_COVERAGE requires Clang for C and C++")
    endif()
    add_compile_options(-fprofile-instr-generate -fcoverage-mapping -g)
    add_link_options(-fprofile-instr-generate)
endif()
if(CWHIP_SANITIZE AND NOT CWHIP_SANITIZE STREQUAL "OFF")
    if(NOT CMAKE_C_COMPILER_ID MATCHES "Clang" OR
       NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        message(FATAL_ERROR "CWHIP_SANITIZE requires Clang for C and C++ (generated programs use Clang too)")
    endif()
    foreach(sanitizer IN LISTS CWHIP_SANITIZE)
        if(NOT sanitizer MATCHES "^(address|undefined)$")
            message(FATAL_ERROR "Unsupported CWHIP_SANITIZE entry: ${sanitizer}")
        endif()
    endforeach()
    list(JOIN CWHIP_SANITIZE "," CWHIP_SANITIZER_LIST)
    add_compile_options("-fsanitize=${CWHIP_SANITIZER_LIST}" -fno-omit-frame-pointer -g)
    add_link_options("-fsanitize=${CWHIP_SANITIZER_LIST}")
endif()
